/* V1.17.0 location/weather adapter. No garment DNA, compatibility or wear writes.
 * API contract: Open-Meteo forecast/geocoding documentation, checked 2026-09-27.
 * Suitability rules: recovered index.html Phase 9 (Ch.129-162), separately named
 * from frozen clothing scores. Unknown material/sole facts are never invented.
 */
(function(root){'use strict';
const KEY='hewrs:weather-context:v1',SCHEMA='hewrs.weather-context.v1',copy=x=>structuredClone(x);
const BANDS=['veryHot','hot','mildWarm','cool','cold','veryCold'],PRECIP=['dry','lightRain','heavyRain','snowIce'],SEASONS=['Spring','Summer','Fall','Winter'];
const LABELS={veryHot:'Very hot (85°F+)',hot:'Hot (75–84°F)',mildWarm:'Mild / warm (65–74°F)',cool:'Cool (55–64°F)',cold:'Cold (40–54°F)',veryCold:'Very cold (below 40°F)',dry:'Dry',lightRain:'Light rain',heavyRain:'Moderate / heavy rain',snowIce:'Snow / ice'};
const need=(v,m)=>{if(!v)throw Error(m);},finite=Number.isFinite;
function validDate(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T00:00:00Z');return finite(+d)&&d.toISOString().slice(0,10)===v;}
function band(f){need(finite(f),'Weather temperature is missing');return f>=85?'veryHot':f>=75?'hot':f>=65?'mildWarm':f>=55?'cool':f>=40?'cold':'veryCold';}
function precipitation(code,mm){need(finite(code)&&finite(mm)&&mm>=0,'Precipitation data is missing');if([56,57,66,67,71,73,75,77,85,86].includes(code))return 'snowIce';if([63,65,81,82,95,96,99].includes(code))return 'heavyRain';if([51,53,55,61,80].includes(code)||mm>0.2)return 'lightRain';need([0,1,2,3,45,48].includes(code),'Unknown weather code; select the weather manually');return 'dry';}
function season(date,latitude){need(validDate(date),'Invalid season date');const m=+date.slice(5,7);let s=m===12||m<=2?'Winter':m<=5?'Spring':m<=8?'Summer':'Fall';if(finite(latitude)&&latitude<0)s={Winter:'Summer',Summer:'Winter',Spring:'Fall',Fall:'Spring'}[s];return s;}
function place(p){need(p&&typeof p.label==='string'&&p.label.length<=200&&finite(p.latitude)&&Math.abs(p.latitude)<=90&&finite(p.longitude)&&Math.abs(p.longitude)<=180,'Invalid selected location');return {label:p.label,latitude:Math.round(p.latitude*100)/100,longitude:Math.round(p.longitude*100)/100};}
function validate(s){need(s&&['manual','live','forecast','not_assessed'].includes(s.source)&&validDate(s.date),'Invalid weather selection');if(s.source==='not_assessed')return {source:s.source,date:s.date};need(BANDS.includes(s.temperatureBand)&&PRECIP.includes(s.precipitation)&&SEASONS.includes(s.season),'Invalid weather bands');if(s.source!=='manual'){need(s.place&&finite(s.fetchedAt)&&typeof s.observedAt==='string'&&s.observedAt.startsWith(s.date),'Missing weather time/location');need(finite(s.airF)&&finite(s.feelsF),'Missing temperatures');need(s.airF>=-150&&s.airF<=160&&s.feelsF>=-180&&s.feelsF<=180,'Weather temperature out of bounds');}if(s.place)place(s.place);return copy(s);}
function fresh(s,date,now=Date.now()){validate(s);if(s.date!==date)return false;return s.source==='manual'||s.source==='not_assessed'||(now-s.fetchedAt>=-60000&&now-s.fetchedAt<=90*60000);}
function parseForecast(j,p,date,now){need(validDate(date)&&j&&!j.error,'Invalid weather response');need(j.current_units?.temperature_2m==='°F'&&j.current_units?.apparent_temperature==='°F'&&j.current_units?.precipitation==='mm','Unexpected weather units');const c=j.current;need(c&&typeof c.time==='string','Missing current weather time');let airF,feelsF,mm,code,source,observedAt,highF=null,lowF=null;
 const i=j.daily?.time?.indexOf(date)??-1;if(i>=0){highF=j.daily.temperature_2m_max?.[i]??null;lowF=j.daily.temperature_2m_min?.[i]??null;}
 if(c.time.slice(0,10)===date){({temperature_2m:airF,apparent_temperature:feelsF,precipitation:mm,weather_code:code}=c);source='live';observedAt=c.time;}
 else{need(i>=0,'Selected work date is outside this forecast; set manual conditions');need(j.daily_units?.temperature_2m_max==='°F'&&j.daily_units?.apparent_temperature_max==='°F'&&j.daily_units?.precipitation_sum==='mm','Unexpected forecast units');airF=j.daily.temperature_2m_max[i];feelsF=j.daily.apparent_temperature_max[i];mm=j.daily.precipitation_sum[i];code=j.daily.weather_code[i];source='forecast';observedAt=date;}
 const s={source,date,place:place(p),fetchedAt:now,observedAt,timezone:j.timezone||'provider local time',airF,feelsF,highF,lowF,temperatureBand:band(feelsF),precipitation:precipitation(code,mm),season:season(date,p.latitude),provider:'Open-Meteo',providerBasis:source==='live'?'Current model estimate; feels-like temperature determines clothing band':'Daily forecast; feels-like HIGH and daily weather code determine clothing band',weatherCode:code,precipitationMm:mm};return validate(s);
}
function create({backend=null,fetchFn=root.fetch?.bind(root),geolocation=root.navigator?.geolocation,now=()=>Date.now()}={}){
 let selected=null,raw=null,blocked=null;
 try{if(backend){raw=backend.getItem(KEY);if(raw!==null){const r=JSON.parse(raw);need(r.schema===SCHEMA,'Different weather storage schema');selected=validate(r.selection);}}}catch(e){blocked='Weather data retained, not reset: '+e.message;}
 async function get(url){need(fetchFn,'Network access is unavailable; use manual weather');const a=new AbortController(),t=setTimeout(()=>a.abort(),12000);try{const r=await fetchFn(url,{signal:a.signal,credentials:'omit',referrerPolicy:'no-referrer',cache:'no-store'});need(r.ok,'Weather service returned HTTP '+r.status);return await r.json();}catch(e){throw Error(e.name==='AbortError'?'Weather request timed out. Manual settings remain available.':'Weather request failed: '+e.message);}finally{clearTimeout(t);}}
 async function search(term){need(typeof term==='string'&&term.trim().length>=2&&term.length<=120,'Enter a city or postal code');const u=new URL('https://geocoding-api.open-meteo.com/v1/search');u.search=new URLSearchParams({name:term.trim(),count:'8',language:'en',format:'json'}).toString();const r=await get(u.href);return (r.results||[]).slice(0,8).map(x=>place({label:[x.name,x.admin1,x.country].filter(Boolean).join(', '),latitude:x.latitude,longitude:x.longitude}));}
 async function fetchAt(p,date){p=place(p);const u=new URL('https://api.open-meteo.com/v1/forecast');u.search=new URLSearchParams({latitude:String(p.latitude),longitude:String(p.longitude),current:'temperature_2m,apparent_temperature,precipitation,weather_code',daily:'temperature_2m_max,temperature_2m_min,apparent_temperature_max,precipitation_sum,weather_code',temperature_unit:'fahrenheit',precipitation_unit:'mm',timezone:'auto',forecast_days:'7'}).toString();return parseForecast(await get(u.href),p,date,now());}
 async function locate(date){need(geolocation,'Location is unavailable; search a city or enter weather manually');const position=await new Promise((resolve,reject)=>{let done=false;const timer=setTimeout(()=>{if(!done){done=true;reject(Error('Location timed out; search a city or use manual weather'));}},15000);function end(fn,x){if(done)return;done=true;clearTimeout(timer);fn(x);}geolocation.getCurrentPosition(p=>end(resolve,p),e=>end(reject,Error(e.code===1?'Location permission denied; search a city or use manual weather':'Location unavailable; search a city or use manual weather')),{enableHighAccuracy:false,timeout:12000,maximumAge:300000});});const p=place({label:'Device location ('+(Math.round(position.coords.latitude*100)/100)+', '+(Math.round(position.coords.longitude*100)/100)+')',latitude:position.coords.latitude,longitude:position.coords.longitude});return fetchAt(p,date);}
 function apply(value){need(!blocked,blocked);const s=validate(value);if(backend){const t=JSON.stringify({schema:SCHEMA,selection:s});need(backend.getItem(KEY)===raw,'Weather settings changed in another tab; reload before saving');backend.setItem(KEY,t);need(backend.getItem(KEY)===t,'Weather save could not be verified');raw=t;}selected=s;return copy(s);}
 function request(date){if(!selected)return {source:'not_assessed',date};need(fresh(selected,date,now()),'Weather is stale or belongs to another date. Refresh Weather or choose manual conditions.');return copy(selected);}
 return Object.freeze({search,fetchAt,locate,apply,request,snapshot:()=>copy(selected),status:()=>({blocked,persistent:!!backend}),key:KEY});
}
// Explicit material words only. The lookup is operational evidence, not a DNA edit.
// Table/class values are recovered from historical Phase 9; no fibre imputation.
const CLASSES={'Fine Worsted':'transitional','Poplin':'transitional','Twill':'transitional','End-on-End':'transitional','Fine Herringbone':'transitional','Micro-Basket':'transitional','Textured Weave':'transitional','Grenadine':'transitional','Hopsack':'transitional','Fresco':'warm','Oxford Cloth':'transitional','Mélange':'transitional','Flannel':'cold','Cashmere':'cold','Suede':'transitional','Heavy Tweed':'cold','Chunky Knit':'cold','Calfskin':'transitional','Polished Leather':'transitional','Embossed Leather':'transitional','Burnished Patina':'transitional','Canvas':'warm','Denim':'transitional','Knit Textile':'transitional','Woven Silk':'transitional'};
function material(item,role){if(!item)return null;if(role==='tie')return 'Woven Silk';let t=[item.name,item.color,item.texture,item.material,item._weatherText].filter(Boolean).join(' ').toLowerCase();/* A visual 'tweed-like' descriptor is not evidence of tweed cloth. Trim does not identify the body fabric. */t=t.replace(/\b(?:tweed|boucl[eé]|suede|cashmere|flannel)[ -](?:like|look(?:ing)?)\b/g,'unconfirmed surface');if(role==='topwear')t=t.replace(/\b(?:taupe |brown |black )?suede\s+(?:elbow\s+)?(?:patches|patch|trim|collar)\b/g,'separate trim');for(const [re,name] of [[/suede/,'Suede'],[/cashmere/,'Cashmere'],[/flannel/,'Flannel'],[/tweed|boucl[eé]/,'Heavy Tweed'],[/fresco/,'Fresco'],[/canvas/,'Canvas'],[/denim/,'Denim'],[/knit trainer|knit textile/,'Knit Textile'],[/herringbone/,'Fine Herringbone'],[/micro.basket|birdseye/,'Micro-Basket'],[/twill/,'Twill'],[/polished leather/,'Polished Leather'],[/embossed.*leather/,'Embossed Leather'],[/calfskin|calf leather/,'Calfskin'],[/burnished.*patina/,'Burnished Patina'],[/m[eé]lange/,'Mélange'],[/textured weave|micro.texture/,'Textured Weave']])if(re.test(t))return name;return null;}
function assess(items,env,context){if(!env||env.source==='not_assessed')return {status:'not_assessed',eligible:true,score:null,reasons:['Weather not assessed'],unassessed:['weather'],compatibility_adjustment:0};validate(env);
 const temp=env.temperatureBand,precip=env.precipitation,idx=BANDS.indexOf(temp),mats={},unknown=[];for(const role of ['topwear','shirt','tie','shoes'])if(items[role]){mats[role]=material(items[role],role);if(!mats[role])unknown.push(role+' material');}
 const reasons=[],penalties=[];let hard=false,T=10,M=10,F=10,P=10,E=10,W=10;const matNotes=[],footNotes=[],precipNotes=[];
 const seasonal=[];for(const [role,item]of Object.entries(items)){if(!item||!Array.isArray(item.seasons))continue;if(!item.seasons.includes('All Year')&&!item.seasons.includes(env.season)){seasonal.push(role+': recorded seasons exclude '+env.season);}}
 if(temp==='veryHot'&&CLASSES[mats.topwear]==='cold'){T-=4;penalties.push(-2.5);reasons.push('Cold-weather topwear material in very hot conditions');}else if(temp==='veryCold'&&CLASSES[mats.topwear]==='warm'){T-=2;if(['clinic','hospital','work'].includes(context.occasion))T=Math.min(10,T+1);}
 const known=Object.entries(mats).filter(([,v])=>v&&CLASSES[v]);for(const [role,m]of known){if(idx<=1&&CLASSES[m]==='cold'){M-=3;matNotes.push(role+' '+m+' in hot conditions');}else if(idx>=4&&CLASSES[m]==='warm'){M-=2;matNotes.push(role+' '+m+' in cold conditions');}}M=Math.max(0,M);
 if(!(temp==='veryHot'&&CLASSES[mats.topwear]==='cold')&&matNotes.length)penalties.push(M<=6?-1.25:-0.5);reasons.push(...matNotes);
 if(precip==='snowIce'){if(items.shoes?.subcategory==='Dress Shoes'){F-=4;hard=true;footNotes.push('Existing snow/ice dress-shoe category exclusion; exact sole/grip is unverified');}else if(mats.shoes==='Suede'){F-=3;footNotes.push('Suede exposed to snow / salt');}}else if(precip==='heavyRain'&&mats.shoes==='Suede'){F-=2.5;footNotes.push('Suede footwear in moderate/heavy rain');}else if(precip==='lightRain'&&mats.shoes==='Suede'){F-=0.5;footNotes.push('Suede footwear caution in light rain');}
 if(footNotes.length)penalties.push(F<=6?-1.25:-0.5);reasons.push(...footNotes);
 for(const role of ['topwear','tie'])if(mats[role]==='Suede'&&precip==='heavyRain'){P-=2;precipNotes.push(role+' suede exposed to rain');}if(precipNotes.length)penalties.push(-0.5);reasons.push(...precipNotes);
 if(['weekend','date'].includes(context.occasion)){if(['veryHot','veryCold'].includes(temp))E-=1.5;if(['heavyRain','snowIce'].includes(precip))E-=1;}else if(precip==='snowIce')E-=0.5;
 const weights=known.length?{T:.3,M:.2,F:.2,P:.15,E:.1,W:.05}:{T:.375,M:0,F:.25,P:.1875,E:.125,W:.0625};
 const sh=items.shirt?._family,colour=env.season==='Summer'&&['white','cream','blue','lavender','pink','grey'].includes(sh)||env.season==='Winter'&&['burgundy','black','navy'].includes(sh)?.25:0;
 let score=Math.round(Math.max(0,Math.min(10,weights.T*T+weights.M*M+weights.F*F+weights.P*P+weights.E*E+weights.W*W+penalties.reduce((a,b)=>a+b,0)+colour))*100)/100;if(hard)score=Math.min(score,3);
 return {status:hard||seasonal.length||score<7?'ineligible':unknown.length?'eligible_with_unassessed_materials':'eligible_by_recorded_rules',eligible:!hard&&!seasonal.length&&score>=7,score,reasons:[...seasonal,...reasons],unassessed:[...unknown,'Exact shoe sole / traction','Wind and humidity modifiers not assessed'],materials:mats,compatibility_adjustment:0,policy:'Recovered Phase 9 weather criteria + recorded season eligibility. Weather domain minimum 7 from historical Ch.179; not a frozen aesthetic score or safety certification.'};
}
root.HEWRSWeather=Object.freeze({create,band,precipitation,season,place,validate,fresh,parseForecast,assess,BANDS,PRECIP,SEASONS,LABELS,KEY});
})(globalThis);
