'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const R=path.resolve(__dirname,'..'),OUT=process.env.HEWRS_V116_FUNCTIONAL||R+'/evidence/batch16_v1_16/FUNCTIONAL.json';
function context(root=R){const scripts=JSON.parse(fs.readFileSync(root+'/tools/build.py','utf8').match(/SCRIPTS=(\[[^\n]+\])/)[1].replaceAll("'",'"')),c=vm.createContext({console,structuredClone,Date,Math,JSON,setTimeout,clearTimeout,Uint8ClampedArray});for(const s of scripts.filter(x=>x!=='src/application.js'))vm.runInContext(fs.readFileSync(root+'/'+s,'utf8'),c,{filename:s});return c;}
const root=context(),c=root.HEWRSCleanConnection.create(root.HEWRS_INPUTS),ui=root.HEWRSFaceliftModel.create(c),checks=[];
const eq=(a,b)=>assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));
const S=(shirtId='DS036',state='T017',suitId='S05')=>({suitId,shirtId,state,shoeId:'shoe-8',watchId:null});
const B=(shirtId='DS023',state='NO_TIE',blazerId='B03',pantId='PG002',shoeId='shoe-8')=>({blazerId,pantId,shirtId,state,shoeId,watchId:null});
const O=(shirtId='DS023',state='NO_TIE',pantId='PG002',shoeId='shoe-8')=>({shirtOnly:true,pantId,shirtId,state,shoeId,watchId:null});
function test(name,fn){try{checks.push({name,passed:true,result:fn()??null});}catch(e){checks.push({name,passed:false,error:e.stack});}}
const ids=['DS002','DS004','DS005','DS006','DS007','DS008','DS015','DS018','DS019','DS021','DS022','DS023','DS024','DS025','DS027','DS047'];
const derivedCuffIds=['DS002','DS004','DS005','DS015','DS022'];
test('Sixteen exact added IDs, eighteen total connected non-suit IDs, thirty-two gated',()=>{eq(c.batch10.ids,ids);assert.equal(c.nonSuitSources.connectedIds.length,18);assert.equal(c.nonSuitSources.ids.length,50);assert.equal(c.nonSuitSources.registry.counts.newly_connected_visual_ids,16);assert.equal(c.implementationVersion,'1.16-batch16');});
test('Added shirt-state-mode selections validate without substitutions',()=>{let n=0;for(const id of ids)for(const t of c.batch10.shirts[id].states){for(const b of c.blazerConnection.availableIds){eq(c.validateSelection(B(id,t,b)),B(id,t,b));n++;}eq(c.validateSelection(O(id,t)),O(id,t));n++;}assert.equal(n,ids.length*48*(c.blazerConnection.availableIds.length+1));return n;});
test('All suit/state routes remain valid, including single REFERENCE route',()=>{let n=0;for(const suit of c.suitSources.ids)for(const id of c.manifest.shirt_order)for(const t of c.manifest.shirts[id].available_modes){if(t==='REFERENCE'&&suit!=='S05')continue;c.validateSelection(S(id,t,suit));n++;}assert.equal(n,39817);return n;});
test('All original component references remain hash-matching',()=>{let n=0;for(const r of Object.values(c.nonSuitSources.registry.shirts))for(const parts of Object.values(r.components))for(const d of Object.values(parts)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/'+d.runtime_path)).digest('hex'),d.sha256);n++;}assert.equal(n,576);return n;});
test('Every registered runtime path contains exact declared bytes',()=>{for(const [hash,p]of Object.entries(c.batch10.assetPaths))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/'+p)).digest('hex'),hash);return Object.keys(c.batch10.assetPaths).length;});
test('Uploaded donors retain their exact bytes and separate catalogue identities',()=>{for(const id of ids){const d=c.batch10.shirts[id];assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/provenance/batch16_v1_16/'+d.source_file)).digest('hex'),d.source_sha256);assert.equal(d.history_id,c.records[id].history_id);}assert.equal(c.batch10.shirts.DS024.source_sha256,c.batch10.shirts.DS025.source_sha256);assert.notEqual(c.records.DS024.history_id,c.records.DS025.history_id);});
test('Current front-collar references are unchanged for all added IDs',()=>{let n=0;for(const id of ids)for(const mode of ['tied','no_tie'])for(const role of ['left','right']){eq(c.batch10.shirts[id].modes[mode][role],c.manifest.shirts[id].states[mode][role]);n++;}assert.equal(n,ids.length*2*2);return n;});
test('Only the disclosed empty-cuff IDs use derived cuffs',()=>{for(const id of ids){const derived=c.batch10.shirts[id].derived_cuffs_for_empty_current_components;assert.equal(Object.keys(derived).length,derivedCuffIds.includes(id)?2:0);}});
test('All 32 source-only shirts remain blocked in both modes',()=>{let n=0;for(const id of c.nonSuitSources.ids.filter(id=>!c.nonSuitSources.connectedIds.includes(id)))for(const m of ['blazer','shirt-only']){assert.equal(c.nonSuitSources.inspect(id,m,'NO_TIE').visual_available,false);assert.throws(()=>c.validateSelection(m==='blazer'?B(id):O(id)));n++;}assert.equal(n,64);return n;});
test('Suit, blazer and shirt-only pickers keep all 50 IDs with correct enablement',()=>{for(const [s,n]of [[S(),50],[B(),18],[O(),18]]){ui.fromSelection(s);const a=ui.filter('shirt');assert.equal(a.length,50);assert.equal(a.filter(x=>x.available).length,n);assert.equal(new Set(a.map(x=>x.id)).size,50);}});
test('New Anchor selections round-trip through existing picker model',()=>{for(const id of ids)for(const s of [B(id,'T047'),O(id,'NO_TIE')]){ui.fromSelection(s);eq(ui.operation('anchor',{localDate:'2026-09-24'}).selection,s);}});
test('Every new shirt has explicit No Tie and all 47 independent tied selections',()=>{for(const id of ids){ui.fromSelection(O(id));assert.equal(ui.filter('tie').filter(x=>x.available).length,47);assert.equal(c.batch10.shirts[id].states.length,48);}});
test('Added numerical results use the unchanged raw blazer model, including holds',()=>{let n=0;for(const id of ids)for(const t of ['NO_TIE','T017']){const s=B(id,t),ctx={occasion:'clinic',requiredFormality:'any'},profile=c.trouserProfiles.binding('PG002');eq(c.scoreSelection(s,ctx),c.rawEngine.evaluate({topwearId:'B03',shirtId:id,tieId:t==='NO_TIE'?null:t,pantProfileId:profile.profileId,context:ctx,versionPolicy:'strict'}));n++;}return n;});
test('Shirt-only ranking remains absent; manual rendering is independent',()=>{for(const id of ids){assert.equal(c.scoreSelection(O(id)).score,null);assert.throws(()=>c.makeRequest({shirtOnly:true,shirt:id,pantId:'PG002',tie:'NO_TIE',shoeId:'shoe-8'}));}});
const result={schema:'hewrs.batch16.functional.v1_16',passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(result.failed)process.exitCode=1;
