'use strict';const fs=require('fs'),path=require('path'),A=require('assert/strict'),R=path.resolve(__dirname,'..'),g=require('./core-loader.cjs')(R),c=g.HEWRSCleanConnection.create(g.HEWRS_INPUTS),L=g.HEWRSOutfitLearning,P=g.HEWRSOptionSetPolicy,E=R+'/evidence/acceptability_v1_23_0';
const old=JSON.parse(fs.readFileSync(process.env.HEWRS_BASELINE+'/evidence/performance_v1_22_1/MATRIX_cold.json')).rows;const neutral=JSON.parse(fs.readFileSync(E+'/SYNTHETIC_MODEL.json'));
const rows=[],checks=[],cp=x=>JSON.parse(JSON.stringify(x)),cfg=(top,p={})=>({automatic:true,stylistMode:'research',preferences:{...Object.fromEntries(['topwear','shirt','tie','shoes','bottoms','watch'].map(k=>[k,{mode:'any'}])),...(top?{topwear:{mode:'item',id:c.aliases.get(top)||c.blazerConnection.knownBlazer(top).historyId}}:{}),...p},occasion:'clinic',formality:'any',style:'AUTO',localDate:'2026-09-29',environment:{source:'not_assessed',date:'2026-09-29'}});
function verify(res,q){A.ok(c.controller.verifyOptionSet(res.options,q));const ex=new Set(P.exactLocks(q)),counts={},keys=new Set();let nt=0;for(const o of res.options){for(const it of Object.values(o.items))if(it?.id)counts[it.id]=(counts[it.id]||0)+1;nt+=!o.items.tie;const key=['topwear','shirt','tie','pants'].map(k=>o.items[k]?.id||null).join('|');A.ok(!keys.has(key));keys.add(key);A.ok(Math.abs(o._hewrsConnected.preference.learning.adjustment)<=.350001);}for(const [k,n]of Object.entries(counts))A.ok(ex.has(k)||n<=(/^T\d{3}$/.test(k)?1:2));A.ok(nt<=2||q.prefs.tie.mode==='none');return {counts,no_tie:nt};}
function save(){fs.writeFileSync(E+'/GENERATION_MATRIX.json',JSON.stringify({scope:'Current code; synthetic acceptability labels, not user feedback. Cold compared with preserved V1.22.1 fixture.',checks,rows},null,2));}
for(const mode of ['cold','synthetic_acceptability']){c.hybrid.setLearningModel(mode==='cold'?L.empty():neutral);for(const top of ['FREE',...c.suitSources.ids,...c.blazerConnection.availableIds]){const t=performance.now(),q=c.makeRequest(cfg(top==='FREE'?null:top)),res=c.controller.generate(q,c.catalogue,[]),cnt=verify(res,q),selections=res.options.map(o=>o._hewrsConnected.canonical_selection),prior=old.find(r=>r.id===top);
 A.equal(res.options.length,top==='B14'?16:20);if(mode==='cold')A.deepEqual(cp(selections),prior.selections);
 const row={mode,id:top,count:res.options.length,seconds:(performance.now()-t)/1000,selections,constraints:cnt,changed_from_cold:mode==='cold'?false:JSON.stringify(selections)!==JSON.stringify(rows.find(r=>r.mode==='cold'&&r.id===top).selections)};
 if(['S10','FREE','B14'].includes(top))row.options=res.options;
 rows.push(row);save();console.log(mode,top,row.count,row.seconds.toFixed(2),row.changed_from_cold);}}
checks.push({name:'All18 suits/14blazers/FREE evaluated cold and acceptance-active; complete IDs/caps revalidated',passed:true});
c.hybrid.setLearningModel(neutral);for(const prefs of [{tie:{mode:'item',id:'T017'}},{shirt:{mode:'item',id:'DS022'}},{tie:{mode:'family',id:'grey'}},{shoes:{mode:'item',id:'shoe-4'},watch:{mode:'none'}},{tie:{mode:'none'}}]){const q=c.makeRequest(cfg('S10',prefs)),r=c.controller.generate(q,c.catalogue,[]);verify(r,q);checks.push({name:'Acceptability respects locks '+JSON.stringify(prefs),passed:true,count:r.options.length});}
const q=c.makeRequest(cfg('S10')),res=c.controller.generate(q,c.catalogue,[]);c.hybrid.setLearningModel(L.empty());A.equal(c.controller.verifyOptionSet(res.options,q),false);checks.push({name:'Model change rejects cached results',passed:true});save();console.log('COMPLETED',rows.length);
