'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),R=path.resolve(__dirname,'..'),g=require('./core-loader.cjs')(R),W=g.HEWRSWeather,A=g.HEWRSAutoWeather;
const D='2026-09-27',NOW=Date.parse(D+'T12:00:00Z'),P={label:'Device location (42.1, -71.2)',latitude:42.1,longitude:-71.2};
const fixture=()=>({timezone:'America/New_York',current_units:{temperature_2m:'°F',apparent_temperature:'°F',precipitation:'mm'},current:{time:D+'T08:00',temperature_2m:68,apparent_temperature:67,precipitation:0,weather_code:3},daily_units:{temperature_2m_max:'°F',apparent_temperature_max:'°F',precipitation_sum:'mm'},daily:{time:[D,'2026-09-28'],temperature_2m_max:[72,75],temperature_2m_min:[48,52],apparent_temperature_max:[70,73],precipitation_sum:[0,0],weather_code:[3,3]}});
const manual={source:'manual',date:D,temperatureBand:'mildWarm',precipitation:'dry',season:'Fall'},checks=[];
const eq=(a,b)=>assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));
function rig(opts={}){
 const map=opts.map||new Map([['wear-sentinel','ORIGINAL'],['favorites-sentinel','ORIGINAL']]),writes=[],calls={gps:0,http:0,permission:0,applied:0};let time=NOW;
 const backend={getItem:k=>map.get(k)??null,setItem:(k,v)=>{writes.push(k);if(opts.quotaKey===k)throw Error('QuotaExceededError');map.set(k,v);}};
 const weather=W.create({backend,now:()=>time,requestTimeoutMs:40,locationTimeoutMs:40,
  geolocation:{getCurrentPosition:(ok,fail)=>{calls.gps++;if(opts.gpsDenied)fail({code:1});else if(!opts.gpsNever)ok({coords:{latitude:42.12645,longitude:-71.23657}});}},
  fetchFn:async(url,params)=>{calls.http++;if(opts.httpNever)return new Promise(()=>{});if(opts.fetch)return opts.fetch(url,params);if(opts.offline)throw Error('offline');return {ok:true,json:async()=>fixture()};}});
 if(opts.selection)weather.apply(opts.selection);
 if(opts.setting){map.set(A.KEY,JSON.stringify({schema:A.SCHEMA,mode:opts.setting,dateMode:opts.dateMode||'today'}));}
 let mode=opts.permission??'granted';const permissions=opts.unsupported?{}:{query:async()=>{calls.permission++;if(opts.queryError)throw Error('unsupported');return {state:mode};}};
 const auto=A.create({weather,backend,permissions,now:()=>time,today:()=>D,permissionTimeoutMs:15,onApplied:()=>calls.applied++});
 return {map,writes,calls,weather,auto,setTime:n=>time=n,setPermission:v=>mode=v};
}
async function test(name,fn){try{const r=await fn();checks.push({name,passed:true,result:r??null});console.log('PASS',name);}catch(e){checks.push({name,passed:false,error:e.stack});console.log('FAIL',name,e.message);}}
(async()=>{
 await test('First visit with prompt permission does not call GPS or any provider until Enable',async()=>{const r=rig({permission:'prompt'});const z=await r.auto.refresh();assert.equal(z.status,'needs_permission');assert.equal(r.calls.gps,0);assert.equal(r.calls.http,0);assert.equal(r.weather.snapshot(),null);});
 await test('Enable explicitly requests once, fetches real transport format, persists weather and opt-in',async()=>{const r=rig({permission:'prompt'}),out=await r.auto.enable();assert.equal(out.status,'ready');assert.equal(r.calls.gps,1);assert.equal(r.calls.http,1);assert.equal(r.auto.settings().mode,'device');assert.equal(r.weather.snapshot().locationBasis,'current_device_fix');assert.equal(r.weather.snapshot().place.latitude,42.13);assert.equal(r.calls.applied,1);});
 await test('Reload with granted permission refreshes automatically without an app modal or Apply',async()=>{const one=rig({permission:'prompt'});await one.auto.enable();const two=rig({map:one.map,permission:'granted'});await two.auto.refresh({trigger:'startup'});assert.equal(two.calls.gps,1);assert.equal(two.calls.http,1);assert.equal(two.calls.applied,1);assert.equal(two.weather.snapshot().date,D);});
 await test('Already-granted browser permission enables silent first refresh without a saved config',async()=>{const r=rig();const z=await r.auto.refresh();assert.equal(z.status,'ready');assert.equal(r.calls.gps,1);assert.equal(r.calls.http,1);});
 for(const permission of ['prompt','denied'])await test('Reopened '+permission+' permission uses saved coordinates with an honest fallback label, zero GPS prompts',async()=>{const r=rig({permission,selection:W.parseForecast(fixture(),P,D,NOW)});const z=await r.auto.refresh();assert.equal(z.status,'ready');assert.equal(z.usingSavedLocation,true);assert.equal(r.calls.gps,0);assert.equal(r.calls.http,1);assert.equal(r.weather.snapshot().locationBasis,'saved_coordinates');});
 await test('Unsupported Permissions API does not attempt silent GPS; saved place only',async()=>{const r=rig({unsupported:true,selection:W.parseForecast(fixture(),P,D,NOW)});await r.auto.refresh();assert.equal(r.calls.gps,0);assert.equal(r.calls.http,1);assert.equal(r.auto.status().permission,'unsupported');});
 await test('Unsupported/denied with no saved place does not fabricate location or weather',async()=>{for(const opts of [{unsupported:true},{permission:'denied'},{queryError:true}]){const r=rig(opts);await r.auto.refresh();assert.equal(r.calls.gps+r.calls.http,0);assert.equal(r.weather.snapshot(),null);}});
 await test('Saved named city refreshes automatically without replacing it with GPS',async()=>{const r=rig({selection:W.parseForecast(fixture(),{...P,label:'Named city test'},D,NOW)});await r.auto.refresh();assert.equal(r.calls.gps,0);assert.equal(r.weather.snapshot().place.label,'Named city test');});
 await test('Manual weather and explicit not-assessed choice never get overwritten automatically',async()=>{for(const s of [manual,{source:'not_assessed',date:D}]){const r=rig({selection:s});await r.auto.refresh({force:true});eq(r.weather.snapshot(),s);assert.equal(r.calls.gps+r.calls.http,0);}});
 await test('Explicitly turning auto off survives recreation without revoking or asking browser permission',async()=>{const r=rig();await r.auto.enable();r.auto.disable();const second=rig({map:r.map});await second.auto.refresh({force:true});assert.equal(second.calls.gps+second.calls.http+second.calls.permission,0);});
 await test('Fresh foreground/generate checks throttle requests; older readings refresh',async()=>{const r=rig();await r.auto.enable();await r.auto.refresh({trigger:'generate'});await r.auto.refresh({trigger:'resume'});assert.equal(r.calls.http,1);r.setTime(NOW+16*60000);await r.auto.refresh();assert.equal(r.calls.http,2);});
 await test('Follow-today mode uses today without overwriting the saved historical outfit ledger',async()=>{const r=rig({setting:'device'});await r.auto.refresh({date:'2026-09-01'});assert.equal(r.weather.snapshot().date,D);assert.equal(r.map.get('wear-sentinel'),'ORIGINAL');});
 await test('Explicit fixed work date is honored; daily forecast is not mislabeled current',async()=>{const r=rig({setting:'device',dateMode:'selected'});await r.auto.refresh({date:'2026-09-28'});assert.equal(r.weather.snapshot().date,'2026-09-28');assert.equal(r.weather.snapshot().source,'forecast');});
 await test('Out-of-forecast date retains the previous weather and reports the transport error',async()=>{const r=rig({setting:'device',dateMode:'selected',selection:W.parseForecast(fixture(),P,D,NOW)});const old=r.weather.snapshot(),z=await r.auto.refresh({date:'2026-09-01'});assert.equal(z.status,'error');assert.equal(z.errorCode,'DATE_OUTSIDE_FORECAST');eq(r.weather.snapshot(),old);});
 await test('Offline and timeout responses retain good previous data; no false successful weather',async()=>{for(const opts of [{offline:true},{httpNever:true},{gpsNever:true}]){const r=rig({...opts,setting:'device',selection:W.parseForecast(fixture(),P,D,NOW)}),old=r.weather.snapshot();const z=await r.auto.refresh({force:true});assert.equal(z.status,'error');eq(r.weather.snapshot(),old);assert.equal(r.calls.applied,0);}});
 await test('Explicit denied permission does not save auto opt-in or replace prior manual weather',async()=>{const r=rig({gpsDenied:true,selection:manual}),z=await r.auto.enable();assert.equal(z.status,'permission_denied');eq(r.weather.snapshot(),manual);assert.equal(r.map.has(A.KEY),false);});
 await test('Cancellation stops late responses from overwriting manual weather',async()=>{let finish;const r=rig({fetch:async()=>{await new Promise(res=>finish=res);return {ok:true,json:async()=>fixture()};}});const job=r.auto.refresh();while(!finish)await new Promise(r=>setTimeout(r,0));r.auto.disable();r.weather.apply(manual);finish();await job;eq(r.weather.snapshot(),manual);assert.equal(r.auto.settings().mode,'off');assert.equal(r.calls.applied,0);});
 await test('Manual weather changed during lookup wins even without explicit cancellation',async()=>{let finish;const r=rig({fetch:async()=>{await new Promise(res=>finish=res);return {ok:true,json:async()=>fixture()};}});const job=r.auto.refresh();while(!finish)await new Promise(r=>setTimeout(r,0));r.weather.apply(manual);finish();const z=await job;assert.equal(z.status,'error');eq(r.weather.snapshot(),manual);});
 await test('Corrupt settings and cross-tab modifications are retained rather than reset',async()=>{const map=new Map([[A.KEY,'{bad']]),r=rig({map});await r.auto.refresh();assert.ok(r.auto.status().blocked);assert.equal(map.get(A.KEY),'{bad');assert.equal(r.calls.http,0);const t=rig();t.map.set(A.KEY,'OTHER TAB');assert.throws(()=>t.auto.disable(),/another tab/);assert.equal(t.map.get(A.KEY),'OTHER TAB');});
 await test('Repeated concurrent refresh calls share one location/weather request',async()=>{const r=rig();await Promise.all([r.auto.refresh(),r.auto.refresh(),r.auto.refresh()]);assert.equal(r.calls.gps,1);assert.equal(r.calls.http,1);});
 await test('Only separate weather keys are written; wear and Favorites remain identical',async()=>{const r=rig();await r.auto.enable();r.auto.disable();assert.ok(r.writes.every(k=>[W.KEY,A.KEY].includes(k)));assert.equal(r.map.get('wear-sentinel'),'ORIGINAL');assert.equal(r.map.get('favorites-sentinel'),'ORIGINAL');});
 fs.writeFileSync(R+'/evidence/suits_auto_weather_v1_17_4/AUTO_WEATHER_FUNCTIONAL.json',JSON.stringify({passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks,scope:'Simulated permission states and provider replies through actual transport code, not actual iOS permission or a live Open-Meteo check.'},null,2)+'\n');if(checks.some(x=>!x.passed))process.exitCode=1;
})();
