#!/usr/bin/env python3
"""Exact-source V1.9 browser checks. Memory-loaded Chromium, not hosted/iPhone."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json,base64,importlib.util,os,time,traceback
R=Path(__file__).resolve().parents[1];E=Path(os.environ.get('HEWRS_BROWSER_OUTPUT',R/'evidence/blazers_v1_9/browser'));E.mkdir(parents=True,exist_ok=True)
checks=[];rows=[];errors=[];started=time.monotonic()
def check(name,ok,detail=None):
 checks.append({'name':name,'pass':bool(ok),'detail':detail});print(('PASS ' if ok else 'FAIL ')+name,flush=True)
 if not ok:raise AssertionError(name+' '+str(detail))
def save():
 (E/'BROWSER.json').write_text(json.dumps({'version':'V1.9','passed':sum(x['pass'] for x in checks),'failed':sum(not x['pass'] for x in checks),'checks':checks,'renders':rows,'page_errors':errors,'seconds':round(time.monotonic()-started,2),'scope':'Exact packaged code and PNGs supplied to Chromium in memory. Not hosted, Safari, physical iPhone or real-origin restart persistence.'},indent=2)+'\n')
with sync_playwright() as pw:
 b=pw.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage']);p=b.new_page(viewport={'width':390,'height':844},device_scale_factor=1);p.on('pageerror',lambda e:errors.append(str(e)))
 try:
  spec=importlib.util.spec_from_file_location('build',R/'tools/build.py');build=importlib.util.module_from_spec(spec);spec.loader.exec_module(build)
  p.set_content((R/'app.template.html').read_text().replace('<!--STYLE-->','<style>'+(R/'src/application.css').read_text()+'</style>').replace('<!--SCRIPTS-->',''));p.evaluate('globalThis.HEWRS_EMBEDDED_IMAGES={}');batch={};n=0
  for f in sorted([*(R/'assets').glob('*.png'),*(R/'assemblies').glob('*.png')]):
   v=base64.b64encode(f.read_bytes()).decode();batch[f.stem]=v;n+=len(v)
   if n>4_000_000:p.evaluate('(x)=>{Object.assign(HEWRS_EMBEDDED_IMAGES,x);}',batch);batch={};n=0
  if batch:p.evaluate('(x)=>{Object.assign(HEWRS_EMBEDDED_IMAGES,x);}',batch)
  for f in build.SCRIPTS:p.add_script_tag(content=(R/f).read_text())
  p.wait_for_function('() => (globalThis.HEWRS_READY===true)');check('App opens with twelve connected blazers and eighteen suits',p.evaluate("HEWRSApp.version==='HEWRS_CONNECTED_APP_V1_9'&&HEWRSApp.connection.blazerConnection.availableIds.length===12&&HEWRSApp.connection.suitSources.ids.length===18"))
  p.evaluate('''()=>{globalThis.pix=c=>c.getContext('2d',{willReadFrequently:true}).getImageData(0,0,996,2748).data;globalThis.visible=()=>pix(document.getElementById('avatar'));globalThis.same=(a,b)=>{const x=new Uint32Array(a.buffer,a.byteOffset,a.length/4),y=new Uint32Array(b.buffer,b.byteOffset,b.length/4);return x.length===y.length&&x.every((v,i)=>v===y[i]);};globalThis.CFG={blazerId:'B06',pantId:'PG002',shirt:'DS001',tie:'T017',shoeId:'shoe-8',watchId:null,localDate:'2026-09-23',occasion:'clinic',style:'AUTO'};globalThis.SEL={blazerId:'B06',pantId:'PG002',shirtId:'DS001',state:'T017',shoeId:'shoe-8',watchId:null};globalThis.saved={d:HEWRS_BLAZER_CONNECTION_DATA,c:HEWRSCleanConnection,s:HEWRSSuitConnectionV16,r:HEWRSBlazerRenderer};}''')
  for f in ['blazer-connection_v18.js','connection_v18.js','blazer-connection_code_v18.js','blazer-renderer_v18.js']:p.add_script_tag(content=(R/'vendor/blazers-v1_9'/f).read_text())
  p.evaluate('''()=>{globalThis.oldConnection=HEWRSCleanConnection.create(HEWRS_INPUTS);globalThis.oldCanvas=document.createElement('canvas');globalThis.oldRenderer=HEWRSAtomicRenderer.create(oldCanvas,oldConnection,{resolveUrl:HEWRSApp.resolveUrl});globalThis.HEWRS_BLAZER_CONNECTION_DATA=saved.d;globalThis.HEWRSCleanConnection=saved.c;globalThis.HEWRSSuitConnectionV16=saved.s;globalThis.HEWRSBlazerRenderer=saved.r;}''')
  proof=json.loads((R/'evidence/blazers_v1_9/SOURCE_CONNECTION.json').read_text())
  p.evaluate('(x)=>{globalThis.cp46Records=Object.fromEntries(x.map(r=>[r.id,r]));}',proof['newly_connected'])
  # Compare original source receipts directly; do not call the modified plan as the oracle.
  p.evaluate('''()=>{const cache=new Map();let lastKey=null,prefix=null;
   async function source(d){if(cache.has(d.sha256)){const v=cache.get(d.sha256);cache.delete(d.sha256);cache.set(d.sha256,v);return v;}const promise=new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{const cv=document.createElement('canvas');cv.width=996;cv.height=2748;cv.getContext('2d',{willReadFrequently:true}).drawImage(im,0,0);const data=pix(cv);cv.width=cv.height=1;resolve({im,data});};im.onerror=reject;im.src=HEWRSApp.resolveUrl(d);});cache.set(d.sha256,promise);while(cache.size>22)cache.delete(cache.keys().next().value);return promise;}
   globalThis.expected=async s=>{const c=HEWRSApp.connection,a=c.blazerConnection.data.assembly,r=cp46Records[s.blazerId],key=[s.blazerId,s.pantId,s.shoeId].join('/');
    if(key!==lastKey){const [base,jack,shirt,lh,rh,lc,rc,avatar,pants,shoes]=await Promise.all([r.control,r.layer,a.ties.T001,...a.hands,...a.cuffs,c.manifest.static.avatar,c.blazerConnection.knownPant(s.pantId).layer,c.shoeLayers[s.shoeId]].map(source));
     const cv=document.createElement('canvas');cv.width=996;cv.height=2748;const ct=cv.getContext('2d',{willReadFrequently:true});ct.drawImage(avatar.im,0,0);ct.drawImage(shoes.im,0,0);ct.drawImage(pants.im,0,0);const out=pix(cv),o32=new Uint32Array(out.buffer),f32=new Uint32Array(base.data.buffer),role=[jack,shirt,lh,rh,lc,rc].map(x=>x.data);for(let i=0;i<o32.length;i++){const a=i*4+3;if(base.data[a]&&role.some(x=>x[a]))o32[i]=f32[i];}cv.width=cv.height=1;prefix=out;lastKey=key;}
    const out=prefix.slice();if(s.state!=='T001'){const [mask,tie]=await Promise.all([a.tie_mask,a.ties[s.state]].map(source));for(let i=0;i<out.length;i+=4)if(mask.data[i]){out[i]=tie.data[i];out[i+1]=tie.data[i+1];out[i+2]=tie.data[i+2];}}const cv=document.createElement('canvas');cv.width=996;cv.height=2748;cv.getContext('2d',{willReadFrequently:true}).putImageData(new ImageData(out,996,2748),0,0);const visible=pix(cv);cv.width=cv.height=1;return visible;
   };}''')
  if os.environ.get('HEWRS_BROWSER_UI_ONLY')!='1':
   for num in range(4,15):
    bid=f'B{num:02d}';result=p.evaluate('''async id=>{const out=[];for(const state of Object.keys(HEWRSApp.connection.blazerConnection.data.assembly.ties)){const s={...SEL,blazerId:id,state},before=visible(),events=HEWRSApp.store.snapshot().events.length,pending=HEWRSApp.apply(s,{save:false}),held=same(before,visible());await pending;out.push({kind:'all_ties',blazerId:id,state,exact:same(visible(),await expected(s)),held,identity:JSON.stringify(HEWRSApp.state().selection)===JSON.stringify(s),noWear:events===HEWRSApp.store.snapshot().events.length});}return out;}''',bid);rows+=result;check(bid+' all 47 ties match original source composition',all(x['exact'] and x['held'] and x['identity'] and x['noWear'] for x in result),47);save()
   pants=p.evaluate("Object.values(HEWRSApp.connection.blazerConnection.data.pants).filter((v,i,a)=>a.findIndex(x=>x.layer.sha256===v.layer.sha256)===i).map(x=>x.id)")
   for num in range(4,15):
    result=p.evaluate('''async arg=>{const out=[];for(const pantId of arg.pants){const s={...SEL,blazerId:arg.id,pantId};await HEWRSApp.apply(s,{save:false});out.push({kind:'pants',blazerId:s.blazerId,pantId,exact:same(visible(),await expected(s))});}return out;}''',{'id':f'B{num:02d}','pants':pants});rows+=result
   check('Nine distinct trouser layers match under all eleven new blazers',all(x['exact'] for x in rows if x['kind']=='pants'),len([x for x in rows if x['kind']=='pants']))
   result=p.evaluate('''async()=>{const out=[];for(const shoeId of Object.keys(HEWRSApp.connection.shoeLayers)){const s={...SEL,shoeId};await HEWRSApp.apply(s,{save:false});out.push({kind:'shoes',shoeId,exact:same(visible(),await expected(s))});}return out;}''');rows+=result;check('35 registered footwear selections match exact originals',all(x['exact'] for x in result),35)
   controls=[{'blazerId':'B03','pantId':pa,'shirtId':'DS001','state':t,'shoeId':'shoe-8','watchId':None} for pa,t in [('PG002','T001'),('PN007','T017'),('PT001','T022'),('PB001','T047')]]
   controls += [{'suitId':f'S{i:02d}','shirtId':sh,'state':st,'shoeId':'shoe-8','watchId':None} for i,sh,st in [(i,'DS036','T017') for i in range(1,19)]+[(5,'DS035','T017'),(5,'DS035','REFERENCE'),(5,'DS051','NO_TIE'),(11,'DS035','T017'),(18,'DS017','NO_TIE'),(11,'DS041','NO_TIE')]]
   for s in controls:rows.append(p.evaluate('''async s=>{await HEWRSApp.apply(s,{save:false});await oldRenderer.render(s);return {kind:'v18_regression',selection:s,exact:same(visible(),pix(oldCanvas))};}''',s))
   check('Original B03 and suit images remain pixel-identical to V1.8',all(x['exact'] for x in rows if x['kind']=='v18_regression'),len(controls))
   for num in range(4,15):rows.append(p.evaluate('''async id=>{const res=await HEWRSApp.generate({...CFG,blazerId:id}),s=HEWRSApp.state().selection;return {kind:'engine',blazerId:id,hasResult:res.options.length>0,exact:same(visible(),await expected(s)),identity:s.blazerId===id&&s.pantId==='PG002'&&s.shirtId==='DS001'&&s.state==='T017'};}''',f'B{num:02d}'))
   check('Every new blazer has a working Engine-to-avatar connection',all(x['hasResult'] and x['exact'] and x['identity'] for x in rows if x['kind']=='engine'),11)
  p.evaluate("HEWRSApp.showPage('home')");p.click('#mode-engine');p.select_option('#topwear-kind','blazer');p.select_option('#blazer-select','B06');p.select_option('#pant-select','PG002');p.select_option('#shirt-select','DS001');p.select_option('#tie-select','T017');p.select_option('#shoe-select','shoe-8');p.select_option('#watch-select','');p.fill('#local-date','2026-09-23');p.click('#apply-selection');p.wait_for_function("() => (!document.getElementById('selection-dialog').open&&HEWRSApp.state().selection.blazerId==='B06'&&document.getElementById('avatar').dataset.loading==='false')")
  check('Engine controls display requested B06/PG002/DS001/T017',p.evaluate("HEWRSApp.state().origin==='engine'&&HEWRSApp.state().selection.pantId==='PG002'&&HEWRSApp.state().selection.state==='T017'"))
  p.click('#full-view');p.screenshot(path=str(E/'APP_B06_ENGINE_PHONE.png'));p.click('#detail-view');p.screenshot(path=str(E/'APP_B06_COLLAR.png'));p.click('#full-view')
  p.click('[data-page="outfits"]');check('Outfits contains selectable generated alternatives',p.locator('#results .card').count()>0);p.locator('#results .card button').first.click();p.wait_for_function("() => (document.getElementById('avatar').dataset.loading==='false')")
  p.click('#mode-anchor');p.select_option('#topwear-kind','blazer');p.select_option('#blazer-select','B14');p.select_option('#shirt-select','DS036');check('Unconnected shirt cannot silently substitute DS001',p.locator('#apply-selection').is_disabled());p.select_option('#shirt-select','DS001');p.select_option('#tie-select','T022');p.select_option('#pant-select','PN007');p.click('#apply-selection');p.wait_for_function("() => (!document.getElementById('selection-dialog').open&&HEWRSApp.state().selection.blazerId==='B14'&&document.getElementById('avatar').dataset.loading==='false')")
  check('Anchor displays an unscored trouser without blocking its approved image',p.evaluate("HEWRSApp.state().selection.pantId==='PN007'&&HEWRSApp.state().selection.state==='T022'"));p.screenshot(path=str(E/'APP_B14_PN007_ANCHOR_PHONE.png'))
  check('Generation and viewing never fabricate wear',p.evaluate('HEWRSApp.store.snapshot().events.length')==0);p.click('#record-wear');p.fill('#wear-date','2026-09-23');p.click('#confirm-wear');check('Confirmed wear retains exact namespaced blazer and physical pants',p.evaluate("HEWRSApp.store.snapshot().events[0].items.topwear.id==='blazer-source-B14'&&HEWRSApp.store.snapshot().events[0].items.pants.id==='pants-PN007'"))
  p.click('#data-button')
  with p.expect_download() as dl:p.click('#export-backup')
  dl.value.save_as(str(E/'TEST_BACKUP.json'));before=p.evaluate('JSON.stringify(HEWRSApp.store.snapshot())');p.set_input_files('#backup-file',str(E/'TEST_BACKUP.json'));p.wait_for_function("() => (!document.getElementById('confirm-restore').disabled)");check('Backup import preview is read-only',before==p.evaluate('JSON.stringify(HEWRSApp.store.snapshot())'));p.click('#confirm-restore');p.wait_for_function("() => (!document.getElementById('backup-dialog').open&&document.getElementById('avatar').dataset.loading==='false')");check('Backup restoration retains canonical blazer and physical pants',p.evaluate("HEWRSApp.store.snapshot().events[0].items.topwear.id==='blazer-source-B14'&&HEWRSApp.state().selection.pantId==='PN007'"))
  check('Rapid cross-blazer requests commit only the latest selection',p.evaluate('''async()=>{await Promise.all([HEWRSApp.apply({...SEL,blazerId:'B04'},{save:false}),HEWRSApp.apply({...SEL,blazerId:'B07'},{save:false}),HEWRSApp.apply({...SEL,blazerId:'B12'},{save:false})]);return HEWRSApp.state().selection.blazerId==='B12'&&same(visible(),await expected({...SEL,blazerId:'B12'}));}'''))
  check('Cancellation retains previous complete outfit',p.evaluate('''async()=>{const before=visible(),s=JSON.stringify(HEWRSApp.state().selection),pending=HEWRSApp.generate({...CFG,tie:'ANY'});HEWRSApp.cancel();await pending;return same(before,visible())&&s===JSON.stringify(HEWRSApp.state().selection);}'''))
  check('Invalid selection leaves pixels and visible identity intact',p.evaluate('''async()=>{const before=visible(),s=JSON.stringify(HEWRSApp.state().selection);try{await HEWRSApp.apply({...SEL,shirtId:'DS036'},{save:false});return false;}catch(e){return same(before,visible())&&s===JSON.stringify(HEWRSApp.state().selection);}}'''))
  check('Wardrobe retains all fourteen canonical blazer records',p.evaluate("()=>{HEWRSApp.showPage('wardrobe');document.getElementById('wardrobe-category').value='blazers';document.getElementById('wardrobe-category').dispatchEvent(new Event('change'));return document.querySelectorAll('#wardrobe-list .card').length===14;}"));p.evaluate("HEWRSApp.showPage('home')")
  layout=[]
  for width,height in [(375,667),(390,844),(430,932)]:
   p.set_viewport_size({'width':width,'height':height});m=p.evaluate("()=>{const a=document.getElementById('avatar').getBoundingClientRect(),n=document.querySelector('.bottom-nav').getBoundingClientRect();return {bottom:a.bottom,navTop:n.top,scrollWidth:document.documentElement.scrollWidth,viewport:innerWidth};}");layout.append({'width':width,'height':height,**m})
  check('Full avatar fits at three phone viewport sizes',all(x['bottom']<=x['navTop']+1 and x['scrollWidth']<=x['viewport'] for x in layout),layout);check('No script errors',not errors,errors);save()
 except Exception as e:errors.append('TEST_ERROR '+str(e));save();traceback.print_exc();raise
 finally:b.close()
