'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const R=path.resolve(__dirname,'..'),out=process.env.HEWRS_TEST_OUTPUT||R+'/evidence/blazers_v1_9/FUNCTIONAL.json';
const scripts=JSON.parse(fs.readFileSync(R+'/tools/build.py','utf8').match(/SCRIPTS=(\[[^\n]+\])/)[1].replaceAll("'",'"')).filter(f=>f!=='src/application.js');
function load(old=false){const cx=vm.createContext({console,structuredClone,Date,Math,JSON,setTimeout,clearTimeout,Uint8ClampedArray});const sub={'src/connection.js':'connection_v18.js','src/blazer-connection.js':'blazer-connection_v18.js','src/blazer-renderer.js':'blazer-renderer_v18.js','data/blazer-connection.js':'blazer-connection_v18.js'};for(const file of scripts){let f=file;if(old&&sub[file]){f='vendor/blazers-v1_9/'+sub[file];if(file==='src/blazer-connection.js')f='vendor/blazers-v1_9/blazer-connection_code_v18.js';}vm.runInContext(fs.readFileSync(R+'/'+f,'utf8'),cx,{filename:f});}return cx;}
const cx=load(),ox=load(true),c=cx.HEWRSCleanConnection.create(cx.HEWRS_INPUTS),old=ox.HEWRSCleanConnection.create(ox.HEWRS_INPUTS);
const eq=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b)),tests=[];
function check(name,fn){try{tests.push({name,pass:true,detail:fn()??null});}catch(e){tests.push({name,pass:false,error:String(e.stack).slice(0,1800)});}}
const ids=Array.from({length:11},(_,i)=>'B'+String(i+4).padStart(2,'0'));
const cfg={blazerId:'B04',pantId:'PG002',shirt:'DS001',tie:'T017',shoeId:'shoe-8',watchId:null,localDate:'2026-09-23',occasion:'clinic',style:'AUTO'};
const sel={blazerId:'B04',pantId:'PG002',shirtId:'DS001',state:'T017',shoeId:'shoe-8',watchId:null};
const req=(id,p,t)=>c.makeRequest({...cfg,blazerId:id,pantId:p,tie:t});
check('All fourteen canonical IDs preserved; B03–B14 have exact connected source routes',()=>{eq(c.blazerConnection.ids,old.blazerConnection.ids);eq(c.blazerConnection.availableIds,['B03',...ids]);});
check('All historical runtime records retained in original order; exactly ten source keys appended',()=>{eq(c.catalogue.blazers.slice(0,old.catalogue.blazers.length),old.catalogue.blazers);eq(c.catalogue.blazers.slice(old.catalogue.blazers.length).map(x=>x.id),ids.slice(1).map(x=>'blazer-source-'+x));for(const k of Object.keys(old.catalogue))if(k!=='blazers')eq(c.catalogue[k],old.catalogue[k]);});
check('Original numerical source inputs and source lock unchanged',()=>{eq(cx.HEWRS_INPUTS,ox.HEWRS_INPUTS);assert.equal(cx.HEWRS_INPUT_SHA256,ox.HEWRS_INPUT_SHA256);});
check('24 exact trouser IDs, 15 profiles and nine unscored entries unchanged',()=>{eq(c.blazerConnection.pantIds,old.blazerConnection.pantIds);eq(c.trouserProfiles.report,old.trouserProfiles.report);assert.equal(c.trouserProfiles.boundIds.length,15);assert.equal(c.trouserProfiles.unboundIds.length,9);});
check('Original CP46 source layer, full assembly and opening mask hashes resolve',()=>{const proof=JSON.parse(fs.readFileSync(R+'/evidence/blazers_v1_9/SOURCE_CONNECTION.json'));for(const b of proof.newly_connected){assert.equal(b.exact_cp47_phone_match,true);for(const d of [b.layer,b.control,b.opening])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/'+d.url)).digest('hex'),d.sha256);}return proof.newly_connected.length;});
check('12408 source plans carry the requested canonical jacket/tie/physical trousers',()=>{let n=0;const render=cx.HEWRSBlazerRenderer.create({getContext:()=>({})},c,()=>{});for(const id of ids)for(const pantId of c.blazerConnection.pantIds)for(const t of Object.keys(c.blazerConnection.data.assembly.ties)){const s={...sel,blazerId:id,pantId,state:t},p=render.plan(s),b=c.blazerConnection.knownBlazer(id);assert.equal(p.blazerId,id);assert.equal(p.base.sha256,b.checkpoint_control.sha256);assert.equal(p.jacket.sha256,b.checkpoint_layer.sha256);assert.equal(p.tie.sha256,c.blazerConnection.data.assembly.ties[t].sha256);assert.equal(p.pants.sha256,c.blazerConnection.knownPant(pantId).layer.sha256);const hi=c.historyIds(s);assert.equal(hi.topwear,b.historyId);assert.equal(hi.pants,'pants-'+pantId);n++;}assert.equal(n,12408);return n;});
let exact=0,numeric=0,optionCount=0;const states={},digest=crypto.createHash('sha256');
check('7755 Engine requests match the inherited canonical score calculations',()=>{for(const id of ids)for(const p of c.trouserProfiles.boundIds)for(const t of Object.keys(c.blazerConnection.data.assembly.ties)){const q=req(id,p,t),r=c.controller.generate(q,c.catalogue,[]),reference=old.engine.evaluate({topwearId:id,shirtId:'DS001',tieId:t,pantProfileId:c.trouserProfiles.binding(p).profileId,context:q.context,versionPolicy:'strict'});eq(c.scoreSelection({...sel,blazerId:id,pantId:p,state:t},q.context),reference);assert.equal(r.diagnostics.examined,1);assert.equal(r.diagnostics.mapping_holds.length,0);for(const o of r.options){const s=c.selectionFromOption(o,q).selection;assert.equal(s.blazerId,id);assert.equal(s.pantId,p);assert.equal(s.state,t);assert.equal(o._hewrsConnected.compatibility.score,reference.score);optionCount++;}numeric+=typeof reference.score==='number';states[r.status]=(states[r.status]||0)+1;digest.update(JSON.stringify(r));exact++;}assert.equal(exact,7755);return {exact_requests:exact,numerical: numeric,returned_options:optionCount,statuses:states,results_sha256:digest.digest('hex')};});
check('Every new blazer generates tie options; NO_TIE is excluded before ranking',()=>{for(const id of ids){const q=req(id,'PG002','ANY');q.limit=100;const r=c.controller.generate(q,c.catalogue,[]);assert.equal(r.diagnostics.examined,47);assert.equal(r.diagnostics.configuration_counts.independent_no_tie,0);assert.ok(r.options.length);for(const o of r.options)c.selectionFromOption(o,q);}});
check('Tie-family choices and exact accessories survive Engine routing',()=>{for(const id of ids){const q=req(id,'PG002','FAMILY:navy'),r=c.controller.generate(q,c.catalogue,[]);for(const o of r.options){assert.equal(o.items.tie.colorFamily,'navy');assert.equal(o.items.shoes.id,'shoe-8');assert.equal(c.selectionFromOption(o,q).selection.blazerId,id);}}});
check('Nine unscored trousers remain usable manually, without invented scores',()=>{for(const id of ids)for(const p of c.trouserProfiles.unboundIds){const s={...sel,blazerId:id,pantId:p};c.validateSelection(s);assert.equal(c.scoreSelection(s,cfg).score,null);const r=c.controller.generate(req(id,p,'T017'),c.catalogue,[]);assert.equal(r.status,'mapping_required');assert.equal(r.options.length,0);}});
for(const [name,patch]of [['B01 without matching final layer',{blazerId:'B01'}],['B02 without matching final layer',{blazerId:'B02'}],['Other shirt',{shirtId:'DS036'}],['NO_TIE',{state:'NO_TIE'}],['Unregistered shoe',{shoeId:'shoe-50'}],['Retired trouser',{pantId:'PW001'}],['Nonexistent blazer',{blazerId:'B15'}],['Mixed suit/blazer request',{suitId:'S05'}]])check('Reject '+name+' without substitution',()=>assert.throws(()=>c.validateSelection({...sel,...patch})));
check('Altered namespaced ID cannot be used as a legacy identity mapping',()=>{const q=req('B05','PG002','T017');const o=c.controller.generate(q,c.catalogue,[]).options[0];const stale=structuredClone(q);stale.topwear.id='blazer-4';assert.equal(c.controller.generate(stale,c.catalogue,[]).status,'request_blocked');assert.equal(c.controller.verifyCachedOption(o,stale,c.catalogue),false);const altered=structuredClone(o);altered.items.topwear.id='blazer-4';assert.throws(()=>c.selectionFromOption(altered,q));});
check('Stale, wrong-profile and forged provenance requests remain blocked',()=>{const q=req('B06','PG002','T017'),o=c.controller.generate(q,c.catalogue,[]).options[0];for(const mutate of [q=>q.pantBindings[0].profileId='P07',q=>q.pantBindings[0].evidence.source_sha256='forged',q=>q.shirt.id='shirt-DS002',q=>q.topwear.id='blazer-0']){const bad=structuredClone(q);mutate(bad);assert.equal(c.controller.generate(bad,c.catalogue,[]).status,'request_blocked');assert.equal(c.controller.verifyCachedOption(o,bad,c.catalogue),false);}});
check('B03 Engine and 18 exact suit Engine outputs remain identical to V1.8',()=>{for(const conf of [{...cfg,blazerId:'B03'},...Array.from({length:18},(_,i)=>({suitId:'S'+String(i+1).padStart(2,'0'),shirt:'DS036',tie:'T017',shoeId:'shoe-8',watchId:null,localDate:'2026-09-23'}))]){const qa=c.makeRequest(conf),qb=old.makeRequest(conf);eq(qa,qb);eq(c.controller.generate(qa,c.catalogue,[]),old.controller.generate(qb,old.catalogue,[]));}});
function backend(){const map=new Map(),calls=[];return {map,calls,getItem:k=>map.get(k)??null,setItem:(k,v)=>{calls.push(k);map.set(k,v);}};}
check('Original B03/suit backup reopens without rewriting or migration',()=>{const db=backend(),s=ox.HEWRSLocalState.create(old,ox.HEWRS_INPUT_SHA256,db);s.addEvent(old.createHistoryEvent({...sel,blazerId:'B03'},{id:'baseline',localDate:'2026-09-22'}));const before=s.exportText(),n=db.calls.length,next=cx.HEWRSLocalState.create(c,cx.HEWRS_INPUT_SHA256,db);assert.equal(next.exportText(),before);assert.equal(db.calls.length,n);});
check('Eleven explicit wear events preserve canonical identity and physical pants through restore',()=>{const db=backend(),s=cx.HEWRSLocalState.create(c,cx.HEWRS_INPUT_SHA256,db);for(const id of ids){s.addEvent(c.createHistoryEvent({...sel,blazerId:id},{id:'wear_'+id,localDate:'2026-09-23'}));}const text=s.exportText(),n=db.calls.length,preview=s.previewImport(text);assert.equal(db.calls.length,n);s.restore(preview);assert.equal(s.snapshot().events.length,11);for(const e of s.snapshot().events){assert.equal(e.items.topwear.id,c.blazerConnection.knownBlazer(e.canonical_selection.blazerId).historyId);assert.equal(e.items.pants.id,'pants-PG002');}});
check('No input data mutated after all operations',()=>eq(cx.HEWRS_INPUTS,ox.HEWRS_INPUTS));
(async()=>{check('Ranked style filtering uses the unchanged inherited classification',()=>{for(const style of ['AUTO','CLASSIC','HYBRID','MODERN']){const q=c.makeRequest({...cfg,blazerId:'B06',tie:'ANY',style}),r=c.controller.generate(q,c.catalogue,[]);for(const o of r.options)if(style!=='AUTO')assert.equal(o._hewrsConnected.compatibility.style.classification,style);}});const q=req('B06','PG002','ANY'),sync=c.controller.generate(q,c.catalogue,[]),asyncResult=await c.controller.generateAsync(q,c.catalogue,[],{});check('Async and synchronous Engine routes agree',()=>eq(sync,asyncResult));const result={version:'V1.9',passed:tests.filter(x=>x.pass).length,failed:tests.filter(x=>!x.pass).length,checks:tests,scope:'Connection regression, not new garment approval or exhaustive browser rendering'};fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:tests.filter(x=>!x.pass)}));if(result.failed)process.exitCode=1;})();
