'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const R=path.resolve(__dirname,'..'),OUT=process.env.HEWRS_V1162_FUNCTIONAL||R+'/evidence/ds023_v1_16_2/FUNCTIONAL.json';
function context(root=R){const scripts=JSON.parse(fs.readFileSync(root+'/tools/build.py','utf8').match(/SCRIPTS=(\[[^\n]+\])/)[1].replaceAll("'",'"')),c=vm.createContext({console,structuredClone,Date,Math,JSON,setTimeout,clearTimeout,Uint8ClampedArray});for(const s of scripts.filter(x=>x!=='src/application.js'))vm.runInContext(fs.readFileSync(root+'/'+s,'utf8'),c,{filename:s});return c;}
const root=context(),c=root.HEWRSCleanConnection.create(root.HEWRS_INPUTS),ui=root.HEWRSFaceliftModel.create(c),checks=[];
const eq=(a,b)=>assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));
const S=(shirtId='DS036',state='T017',suitId='S05')=>({suitId,shirtId,state,shoeId:'shoe-8',watchId:null});
const B=(shirtId='DS023',state='NO_TIE',blazerId='B03',pantId='PG002',shoeId='shoe-8')=>({blazerId,pantId,shirtId,state,shoeId,watchId:null});
const O=(shirtId='DS023',state='NO_TIE',pantId='PG002',shoeId='shoe-8')=>({shirtOnly:true,pantId,shirtId,state,shoeId,watchId:null});
function test(name,fn){try{checks.push({name,passed:true,result:fn()??null});}catch(e){checks.push({name,passed:false,error:e.stack});}}
const ids=["DS004","DS005","DS007","DS015","DS018","DS019","DS023","DS024","DS025","DS047","DS002","DS006","DS008","DS021","DS022","DS027"];
test('Sixteen exact registered donors, eighteen connected non-suit IDs, thirty-two gated',()=>{eq(c.batch10.ids,ids);assert.equal(c.nonSuitSources.connectedIds.length,18);assert.equal(c.nonSuitSources.ids.length,50);assert.equal(c.nonSuitSources.registry.counts.newly_connected_visual_ids,16);assert.equal(c.implementationVersion,'1.16-batch16');});
test('11,520 registered shirt-state-mode selections validate without substitutions',()=>{let n=0;for(const id of ids)for(const t of c.batch10.shirts[id].states){for(const b of c.blazerConnection.availableIds){eq(c.validateSelection(B(id,t,b)),B(id,t,b));n++;}eq(c.validateSelection(O(id,t)),O(id,t));n++;}assert.equal(n,11520);return n;});
test('26,880 exact registered shirt/pant/footwear mode selections validate',()=>{let n=0;for(const id of ids)for(const p of c.blazerConnection.pantIds)for(const h of Object.keys(c.shoeLayers)){c.validateSelection(B(id,'NO_TIE','B03',p,h));c.validateSelection(O(id,'NO_TIE',p,h));n+=2;}assert.equal(n,26880);return n;});
test('All 39,817 suit/state routes remain valid, including single REFERENCE route',()=>{let n=0;for(const suit of c.suitSources.ids)for(const id of c.manifest.shirt_order)for(const t of c.manifest.shirts[id].available_modes){if(t==='REFERENCE'&&suit!=='S05')continue;c.validateSelection(S(id,t,suit));n++;}assert.equal(n,39817);return n;});
test('All 576 original component references remain hash-matching',()=>{let n=0;for(const r of Object.values(c.nonSuitSources.registry.shirts))for(const parts of Object.values(r.components))for(const d of Object.values(parts)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/'+d.runtime_path)).digest('hex'),d.sha256);n++;}assert.equal(n,576);return n;});
test('Every registered runtime path contains exact declared bytes',()=>{for(const [hash,p]of Object.entries(c.batch10.assetPaths))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/'+p)).digest('hex'),hash);return Object.keys(c.batch10.assetPaths).length;});
test('Uploaded donors retain their exact bytes and separate catalogue identities',()=>{for(const id of ids){const d=c.batch10.shirts[id];assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/provenance/batch16_v1_16/'+d.source_file)).digest('hex'),d.source_sha256);assert.equal(d.history_id,c.records[id].history_id);}assert.equal(c.batch10.shirts.DS024.source_sha256,c.batch10.shirts.DS025.source_sha256);assert.notEqual(c.records.DS024.history_id,c.records.DS025.history_id);});
test('Sixty-four exact current front-collar references are unchanged',()=>{let n=0;for(const id of ids)for(const mode of ['tied','no_tie'])for(const role of ['left','right']){eq(c.batch10.shirts[id].modes[mode][role],c.manifest.shirts[id].states[mode][role]);n++;}return n;});
test('Only DS002/DS004/DS005/DS015/DS022 use disclosed derived cuffs for empty current parts',()=>{for(const id of ids){const derived=c.batch10.shirts[id].derived_cuffs_for_empty_current_components;assert.equal(Object.keys(derived).length,['DS002','DS004','DS005','DS015','DS022'].includes(id)?2:0);}});
test('All 32 source-only shirts remain blocked in both modes',()=>{let n=0;for(const id of c.nonSuitSources.ids.filter(id=>!c.nonSuitSources.connectedIds.includes(id)))for(const m of ['blazer','shirt-only']){assert.equal(c.nonSuitSources.inspect(id,m,'NO_TIE').visual_available,false);assert.throws(()=>c.validateSelection(m==='blazer'?B(id):O(id)));n++;}assert.equal(n,64);return n;});
test('Suit, blazer and shirt-only pickers keep all 50 IDs with correct enablement',()=>{for(const [s,n]of [[S(),50],[B(),18],[O(),18]]){ui.fromSelection(s);const a=ui.filter('shirt');assert.equal(a.length,50);assert.equal(a.filter(x=>x.available).length,n);assert.equal(new Set(a.map(x=>x.id)).size,50);}});
test('Apply changes exactly one preference; Cancel changes nothing',()=>{ui.fromSelection(B());const before=ui.snapshot();ui.begin('shirt');ui.choose({mode:'item',id:'DS025'});ui.cancel();eq(ui.snapshot(),before);ui.begin('shirt');ui.choose({mode:'item',id:'DS025'});ui.commit();const after=ui.snapshot();assert.equal(after.shirt.id,'DS025');for(const k of Object.keys(before).filter(k=>k!=='shirt'))eq(before[k],after[k]);});
test('New Anchor selections round-trip through existing picker model',()=>{for(const id of ids)for(const s of [B(id,'T047'),O(id,'NO_TIE')]){ui.fromSelection(s);eq(ui.operation('anchor',{localDate:'2026-09-24'}).selection,s);}});
test('Every new shirt has explicit No Tie and all 47 independent tied selections',()=>{for(const id of ids){ui.fromSelection(O(id));assert.equal(ui.filter('tie').filter(x=>x.available).length,47);assert.equal(c.batch10.shirts[id].states.length,48);}});
test('Four existing NO_TIE-only restrictions, DS035 mask and DS051 profile survive',()=>{for(const id of ['DS040','DS041','DS042','DS043']){eq(c.nonSuitSources.registry.shirts[id].states,['NO_TIE']);assert.throws(()=>c.validateSelection(S(id,'T017')));}assert.equal(c.nonSuitSources.componentPlan('DS051','T017').compositing_profile,'PARENT_DS051_STORED_RGB');eq(c.nonSuitSources.componentPlan('DS035','T017').layers.find(x=>x.role==='body').descriptor.display_alpha_mask,c.manifest.shirts.DS035.body_keep_for_selectable_ties);});
test('New exact blazer Engine queries preserve shirt/tie identities',()=>{let requests=0,options=0;for(const id of ids)for(const tie of ['NO_TIE','T017']){const q=c.makeRequest({blazerId:'B03',pantId:'PG002',shirt:id,tie,shoeId:'shoe-8',localDate:'2026-09-24'});assert.equal(q.shirt.id,'shirt-'+id);if(tie==='NO_TIE')eq(q.tie,{mode:'none'});const out=c.controller.generate(q,c.catalogue,[]);for(const op of out.options){const sel=c.selectionFromOption(op,q).selection;assert.equal(sel.shirtId,id);assert.equal(sel.state,tie);options++;}requests++;}assert.ok(options>0);return {requests,options};});
test('Added numerical results use the unchanged raw blazer model, including holds',()=>{let n=0;for(const id of ids)for(const t of ['NO_TIE','T017']){const s=B(id,t),ctx={occasion:'clinic',requiredFormality:'any'},profile=c.trouserProfiles.binding('PG002');eq(c.scoreSelection(s,ctx),c.rawEngine.evaluate({topwearId:'B03',shirtId:id,tieId:t==='NO_TIE'?null:t,pantProfileId:profile.profileId,context:ctx,versionPolicy:'strict'}));n++;}return n;});
test('Nine unbound trouser profiles remain visual, not fabricated numerical values',()=>{for(const pant of c.trouserProfiles.unboundIds)for(const id of ids){assert.equal(c.scoreSelection(B(id,'NO_TIE','B03',pant)).score,null);}});
test('Shirt-only ranking remains absent; manual rendering is independent',()=>{for(const id of ids){assert.equal(c.scoreSelection(O(id)).score,null);assert.throws(()=>c.makeRequest({shirtOnly:true,shirt:id,pantId:'PG002',tie:'NO_TIE',shoeId:'shoe-8'}));}});
test('Watch ID/name and physical wearer history are retained',()=>{for(const id of ids){const z={...B(id),watchId:'watch-P05'},e=c.createHistoryEvent(z,{id:'test_'+id,localDate:'2026-09-24',origin:'manual'});assert.equal(e.items.watch.id,'watch-P05');assert.equal(e.items.shirt.id,'shirt-'+id);assert.equal(e.items.tie,null);assert.equal(e.items.pants.id,'pants-PG002');}});
test('New events export/reload/import without ID changes in isolated test storage',()=>{const m=new Map([['sentinel','UNCHANGED']]),backend={getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)},store=root.HEWRSLocalState.create(c,root.HEWRS_INPUT_SHA256,backend);for(const id of ids)store.addEvent(c.createHistoryEvent(O(id),{id:'V1161_'+id,localDate:'2026-09-24',origin:'manual'}));const before=store.snapshot(),text=store.exportText();const reloaded=root.HEWRSLocalState.create(c,root.HEWRS_INPUT_SHA256,backend);eq(reloaded.snapshot(),before);eq(reloaded.previewImport(text).events,before.events);assert.equal(m.get('sentinel'),'UNCHANGED');return {events:before.events.length,backend:'synthetic Map, not real-origin/browser restart'};});
test('Tampered added ID, current collar, and missing renderer are rejected',()=>{const a=context();a.HEWRS_BATCH10.ids[0]='DS049';assert.throws(()=>a.HEWRSCleanConnection.create(a.HEWRS_INPUTS));const b=context();b.HEWRS_BATCH10.shirts.DS004.modes.tied.left=b.HEWRS_BATCH10.shirts.DS005.modes.tied.left;assert.throws(()=>b.HEWRSCleanConnection.create(b.HEWRS_INPUTS));const d=context();d.HEWRSBatch10Renderer=null;assert.throws(()=>d.HEWRSCleanConnection.create(d.HEWRS_INPUTS));});
test('Unsupported or mixed requests do not mutate the isolated ledger',()=>{const m=new Map(),be={getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)},store=root.HEWRSLocalState.create(c,root.HEWRS_INPUT_SHA256,be);store.addEvent(c.createHistoryEvent(B(),{id:'sentinel_event',localDate:'2026-09-24',origin:'manual'}));const before=store.exportText();for(const s of [B('DS049'),B('DS036'),O('DS004','REFERENCE'),{...O(),suitId:'S05'}])assert.throws(()=>c.validateSelection(s));assert.equal(store.exportText(),before);});

const baselinePath=process.env.HEWRS_BASELINE_V1161;
if(baselinePath)test('V1.16.1 rollback can retain and render all 18 exact-ID ledger entries',()=>{
 const oldRoot=context(baselinePath),old=oldRoot.HEWRSCleanConnection.create(oldRoot.HEWRS_INPUTS),m=new Map(),be={getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};
 const store=root.HEWRSLocalState.create(c,root.HEWRS_INPUT_SHA256,be);
 for(const id of c.nonSuitSources.connectedIds)store.addEvent(c.createHistoryEvent(O(id),{id:'ROLLBACK_'+id,localDate:'2026-09-24',origin:'manual'}));
 const raw=m.get(store.key),rollback=oldRoot.HEWRSLocalState.create(old,oldRoot.HEWRS_INPUT_SHA256,be);
 assert.equal(rollback.status().blocked,null);eq(rollback.snapshot(),store.snapshot());assert.equal(m.get(store.key),raw);
 return {events:18,storage:'isolated synthetic Map; no device/origin claim'};
});
test('Registration order preserves the ten prior IDs and appends the six additions',()=>{
 eq(c.batch10.ids,['DS004','DS005','DS007','DS015','DS018','DS019','DS023','DS024','DS025','DS047','DS002','DS006','DS008','DS021','DS022','DS027']);
 const physical=c.nonSuitSources.ids;assert.equal(new Set(physical).size,50);for(const id of physical)assert.equal(c.records[id].history_id,'shirt-'+id);
});
test('Only six new shirt identities were added relative to V1.15; DS001/DS014 remain separate',()=>{
 const added=c.nonSuitSources.connectedIds.filter(id=>!['DS001','DS014','DS004','DS005','DS007','DS015','DS018','DS019','DS023','DS024','DS025','DS047'].includes(id));
 eq(added.slice().sort(),['DS002','DS006','DS008','DS021','DS022','DS027']);assert.notEqual(c.historyIds(O('DS001')).shirt,c.historyIds(O('DS014')).shirt);
});
test('Synthetic concurrent writer is detected without overwriting external storage',()=>{
 const m=new Map(),be={getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)},store=root.HEWRSLocalState.create(c,root.HEWRS_INPUT_SHA256,be);
 m.set(store.key,'foreign-tab-value');assert.throws(()=>store.addEvent(c.createHistoryEvent(O('DS022'),{id:'STALE_TAB',localDate:'2026-09-24',origin:'manual'})));assert.equal(m.get(store.key),'foreign-tab-value');
});

test('DS023 cleanup is pinned to unchanged registry bytes and exact owner donor',()=>{const d=c.ds023Cleanup;assert.equal(d.id,'DS023');assert.equal(d.history_id,'shirt-DS023');assert.equal(d.baseline_registration_sha256,crypto.createHash('sha256').update(fs.readFileSync(R+'/data/batch10.json')).digest('hex'));assert.equal(d.owner_source_sha256,c.batch10.shirts.DS023.source_sha256);assert.equal(Object.keys(d.assetPaths).length,2);});
test('Both DS023 correction descriptors bind exact separately named PNGs',()=>{for(const m of Object.values(c.ds023Cleanup.modes)){assert.equal(c.assetPaths[m.base.sha256],m.base.url);assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/'+m.base.url)).digest('hex'),m.base.sha256);assert.notEqual(m.base.sha256,m.baseline.sha256);}return 2;});
test('All original runtime images remain unchanged against V1.16.1',()=>{assert.ok(baselinePath);const man=JSON.parse(fs.readFileSync(baselinePath+'/PACKAGE_SHA256.json'));let n=0;for(const f of man.files.filter(f=>/^(assets|assemblies)\//.test(f.path)&&/\.(png|webp|jpe?g)$/.test(f.path))){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/'+f.path)).digest('hex'),f.sha256);n++;}assert.equal(n,699);return n;});
test('Cleanup cannot be attached to a different ID, altered input lock or replaced original base',()=>{for(const mutate of [q=>q.id='DS025',q=>q.source_input_sha256='bad',q=>q.modes.tied.baseline.sha256='0'.repeat(64),q=>q.owner_source_sha256='1'.repeat(64)]){const ctx=context();mutate(ctx.HEWRS_DS023_CLEANUP);assert.throws(()=>ctx.HEWRSCleanConnection.create(ctx.HEWRS_INPUTS));}});
test('DS023 compatibility and history output remain exactly equal to V1.16.1',()=>{const z=context(baselinePath),b=z.HEWRSCleanConnection.create(z.HEWRS_INPUTS);let n=0;for(const t of c.batch10.shirts.DS023.states)for(const s of [S('DS023',t),B('DS023',t),O('DS023',t)]){eq(c.historyIds(s),b.historyIds(s));eq(c.scoreSelection(s,{occasion:'clinic',requiredFormality:'any'}),b.scoreSelection(s,{occasion:'clinic',requiredFormality:'any'}));n++;}return n;});
test('No other shirt registration, catalogue, scoring input, geometry or storage code changed',()=>{for(const f of ['data/batch10.json','data/inputs.json','data/blazer-connection.json','data/shirt-only.json','src/local-state.js','src/application.css','src/facelift-state.js','vendor/hewrs-logic.js','vendor/approved-scores.js'])assert.equal(fs.readFileSync(R+'/'+f).compare(fs.readFileSync(baselinePath+'/'+f)),0);});
const result={schema:'hewrs.ds023.functional.v1_16_2',passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(result.failed)process.exitCode=1;
