'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('crypto');
const R=path.resolve(__dirname,'..'),E=R+'/evidence/edges_v1_16_3';
function context(){const scripts=JSON.parse(fs.readFileSync(R+'/tools/build.py','utf8').match(/SCRIPTS=(\[[^\n]+\])/)[1].replaceAll("'",'"'));const c=vm.createContext({console,structuredClone,Date,Math,JSON,setTimeout,clearTimeout,Uint8ClampedArray});for(const s of scripts.filter(s=>s!=='src/application.js'))vm.runInContext(fs.readFileSync(R+'/'+s,'utf8'),c,{filename:s});return c;}
const ctx=context(),c=ctx.HEWRSCleanConnection.create(ctx.HEWRS_INPUTS),checks=[];const eq=(a,b)=>assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const O=(shirtId='DS023',state='T017')=>({shirtOnly:true,shirtId,state,pantId:'PG002',shoeId:'shoe-8',watchId:null});const B=(shirtId='DS023',state='T017')=>({blazerId:'B03',shirtId,state,pantId:'PG002',shoeId:'shoe-8',watchId:null});
function test(name,f){try{checks.push({name,passed:true,result:f()??null});}catch(e){checks.push({name,passed:false,error:e.stack});}}
function renderer(kind){const cv={width:0,height:0,getContext:()=>({})};return (kind==='blazer'?ctx.HEWRSBlazerRenderer:ctx.HEWRSShirtOnlyRenderer).create(cv,c,d=>d.url);}
test('Four exact original descriptors and unchanged source input lock',()=>{const d=c.ds023Edges;assert.equal(d.id,'DS023');assert.equal(d.history_id,'shirt-DS023');assert.equal(d.source_input_sha256,sha(fs.readFileSync(R+'/data/inputs.json')));assert.equal(Object.keys(d.layers).length,4);});
test('Four added layer files resolve by exact SHA256; zero source RGB edits in derivation receipt',()=>{for(const [h,p]of Object.entries(c.ds023Edges.assetPaths))assert.equal(sha(fs.readFileSync(R+'/'+p)),h);const rows=JSON.parse(fs.readFileSync(E+'/DERIVATION.json')).checks;for(const r of rows){assert.equal(r.rgb_changed_pixels,0);assert.equal(r.alpha_added_pixels,0);assert.equal(r.outside_bounded_matte_changed_pixels,0);}return rows.length;});
test('DS023 T017 uses all four new edge mattes in both non-suit render plans',()=>{for(const k of ['blazer','shirt-only']){const p=renderer(k).plan(k==='blazer'?B():O());assert.ok(p.ds023Edges);eq(p.body,c.ds023Edges.layers.base.layer);eq(p.leaves,[c.ds023Edges.layers.left.layer,c.ds023Edges.layers.right.layer]);eq(p.tie,c.ds023Edges.layers.T017.layer);} });
test('Other DS023 ties use the neck mattes but retain each exact existing tie',()=>{let n=0;for(const id of Object.keys(c.batch10.ties).filter(k=>k!=='T017')){const p=renderer('shirt-only').plan(O('DS023',id));assert.ok(p.ds023Edges);eq(p.tie,c.batch10.ties[id]);n++;}return n;});
test('DS023 NO_TIE retains the V1.16.2 base and current collar leaves',()=>{for(const k of ['blazer','shirt-only']){const p=renderer(k).plan(k==='blazer'?B('DS023','NO_TIE'):O('DS023','NO_TIE'));assert.ok(!p.ds023Edges);eq(p.body,c.ds023Cleanup.modes.no_tie.base);assert.equal(p.tie,null);eq(p.leaves,[c.batch10.shirts.DS023.modes.no_tie.left,c.batch10.shirts.DS023.modes.no_tie.right]);}});
test('T017 for every other registered donor remains the original batch tie',()=>{for(const id of c.batch10.ids.filter(k=>k!=='DS023')){const p=renderer('shirt-only').plan(O(id));assert.ok(!p.ds023Edges);eq(p.tie,c.batch10.ties.T017);eq(p.body,c.batch10.shirts[id].modes.tied.base);}});
test('701 V1.16.2 runtime image files retain exact bytes',()=>{const files=JSON.parse(fs.readFileSync(R+'/rollback/edges_v1_16_3/BASELINE_FILES.json')).files;let n=0;for(const [p,f] of Object.entries(files))if(/^(assets|assemblies)\//.test(p)&&/\.(png|webp|jpe?g)$/.test(p)){assert.equal(sha(fs.readFileSync(R+'/'+p)),f.sha256);n++;}assert.equal(n,701);return n;});
test('No changes to source data, scoring, masks, storage, or facelift styling',()=>{const files=JSON.parse(fs.readFileSync(R+'/rollback/edges_v1_16_3/BASELINE_FILES.json')).files;const names=['data/inputs.json','data/batch10.json','data/ds023-cleanup.json','data/non-suit-sources.json','data/blazer-connection.json','data/suit-assembly.json','src/local-state.js','src/facelift-state.js','src/source-aware-pickers.js','src/application.css','vendor/hewrs-logic.js','vendor/approved-scores.js'];for(const p of names)assert.equal(sha(fs.readFileSync(R+'/'+p)),files[p].sha256);return names.length;});
test('Malformed edge ID, source, scope, and layer transforms are rejected',()=>{for(const f of [d=>d.id='DS025',d=>d.source_input_sha256='bad',d=>d.applies_to_neck='ALL_SHIRTS',d=>d.layers.left.baseline.sha256='1'.repeat(64),d=>d.layers.T017.layer.rect[0]=1,d=>d.assetPaths={}]){const z=context();f(z.HEWRS_DS023_EDGES);assert.throws(()=>z.HEWRSCleanConnection.create(z.HEWRS_INPUTS));}});
test('Current supported IDs and gating remain 18 connected plus 32 unavailable non-suit',()=>{assert.equal(c.nonSuitSources.connectedIds.length,18);assert.equal(c.nonSuitSources.ids.length,50);assert.equal(c.scoreSelection(O()).score,null);assert.throws(()=>c.validateSelection(O('DS036')));});
const out={schema:'hewrs.ds023-edges.functional.v1_16_3',passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length,checks};fs.writeFileSync(E+'/FUNCTIONAL.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));if(out.failed)process.exitCode=1;
