'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const R=path.resolve(__dirname,'..'),build=fs.readFileSync(R+'/tools/build.py','utf8'),files=JSON.parse(build.match(/SCRIPTS=(\[[^\n]+\])/)[1].replaceAll("'",'"'));
const cx=vm.createContext({console,structuredClone,Date,Math,JSON,setTimeout,clearTimeout,Uint8ClampedArray});
for(const f of files.filter(f=>f!=='src/application.js'))vm.runInContext(fs.readFileSync(R+'/'+f,'utf8'),cx,{filename:f});
const raw=JSON.stringify(cx.HEWRS_INPUTS),c=cx.HEWRSCleanConnection.create(cx.HEWRS_INPUTS),m=cx.HEWRSFaceliftModel.create(c),tests=[];
const eq=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b));
function test(name,fn){try{fn();tests.push({name,status:'PASS'});}catch(e){tests.push({name,status:'FAIL',error:String(e.stack)});}}
const sel={suitId:'S05',shirtId:'DS036',state:'T017',shoeId:'shoe-8',watchId:null},ctx={occasion:'clinic',formality:'any',style:'AUTO',localDate:'2026-09-23'};
function init(){m.reset();m.fromSelection(sel);}
test('All six preference categories present',()=>eq([...m.categories],['topwear','shirt','tie','shoes','bottoms','watch']));
test('33 explicit topwear view records: 18 suits, 14 blazers, 1 no-jacket route',()=>assert.equal(m.rows.topwear.length,33));
test('Topwear IDs map through current aliases, not position arithmetic',()=>{for(const r of m.rows.topwear.filter(r=>r.kind==='suit'))assert.equal(c.aliases.get(r.sourceId),r.id);});
test('Current 50 active shirts; no retired DS049',()=>{assert.equal(m.rows.shirt.length,50);assert.ok(!m.rows.shirt.some(r=>r.id==='DS049'));});
test('47 current ties and 35 exact registered shoes',()=>{assert.equal(m.rows.tie.length,47);assert.equal(m.rows.shoes.length,35);});
test('24 individual trouser IDs retained despite shared images',()=>assert.equal(new Set(m.rows.bottoms.map(r=>r.id)).size,24));
test('Every current watch ID and name retained without images',()=>eq(m.rows.watch.map(r=>[r.id,r.label]),c.catalogue.watches.map(r=>[r.id,r.name])));
test('No sample/demo IDs are created for garments',()=>assert.ok(Object.values(m.rows).flat().every(r=>!String(r.id).startsWith('demo-'))));
test('Read-only construction does not mutate current engine/catalogue data',()=>assert.equal(JSON.stringify(cx.HEWRS_INPUTS),raw));
for(const cat of m.categories)test('Draft/Cancel leaves '+cat+' unchanged',()=>{init();if(cat==='bottoms')m.set('topwear',{mode:'item',id:m.rows.topwear.find(r=>r.sourceId==='B03').id});const before=m.snapshot();m.begin(cat);m.choose({mode:'any'});m.cancel();eq(m.snapshot(),before);});
for(const cat of m.categories)test('Apply changes only '+cat,()=>{init();if(cat==='bottoms')m.set('topwear',{mode:'item',id:m.rows.topwear.find(r=>r.sourceId==='B03').id});const before=m.snapshot();m.begin(cat);m.choose({mode:'item',id:m.rows[cat].find(r=>r.available).id});m.commit();for(const k of m.categories)if(k!==cat)eq(m.snapshot()[k],before[k]);});
test('Cancel after an empty draft does not choose a fallback',()=>{init();const before=m.snapshot();m.begin('shirt');m.choose(null);assert.throws(()=>m.commit());m.cancel();eq(before,m.snapshot());});
test('No Tie differs from Engine / Any in exact effective engine request',()=>{init();m.set('tie',{mode:'none'});const no=m.operation('engine',ctx);assert.equal(no.request.tie.mode,'none');m.set('tie',{mode:'any'});assert.equal(m.operation('engine',ctx).request.tie,undefined);});
test('Category preference retains FAMILY semantics',()=>{init();m.set('shirt',{mode:'family',id:'brown'});const q=m.operation('engine',ctx).request;assert.equal(q.shirt.mode,'category');assert.equal(q.shirt.category,'brown');});
test('Invalid family does not become a current score attribute',()=>{assert.throws(()=>m.set('shirt',{mode:'family',id:'invented'}));});
test('Any topwear does not silently fall back to S05',()=>{init();m.set('topwear',{mode:'any'});assert.throws(()=>m.operation('engine',ctx));});
test('Any shoes do not silently fall back to shoe-8',()=>{init();m.set('shoes',{mode:'any'});assert.throws(()=>m.operation('engine',ctx));});
test('Anchor after Reset fabricates no clothing lock',()=>{m.reset();assert.equal(m.lockCount(),0);assert.throws(()=>m.operation('anchor',ctx));});
test('Reset does not touch source data',()=>assert.equal(JSON.stringify(cx.HEWRS_INPUTS),raw));
test('Suit includes trousers without consuming saved separate preference',()=>{init();m.set('bottoms',{mode:'item',id:'PG002'});assert.ok(m.included());assert.throws(()=>m.begin('bottoms'));const op=m.operation('anchor',ctx);eq(op.selection,sel);assert.ok(!Object.hasOwn(op.config,'pantId'));assert.equal(m.snapshot().bottoms.id,'PG002');});
test('Blazer restores the same physical separate trousers',()=>{m.set('topwear',{mode:'item',id:m.rows.topwear.find(r=>r.sourceId==='B03').id});assert.equal(m.included(),false);m.set('shirt',{mode:'item',id:'DS001'});const s=m.operation('anchor',ctx).selection;assert.equal(s.blazerId,'B03');assert.equal(s.pantId,'PG002');assert.ok(!Object.hasOwn(s,'suitId'));});
test('Blazer Engine uses exact inherited request unchanged',()=>{const op=m.operation('engine',ctx);eq(op.request,c.makeRequest(op.config));assert.equal(op.request.pants.id,'pants-PG002');assert.equal(op.request.pantBindings.length,1);});
test('Nine null scoring mappings stay null; Anchor still accepts PN007',()=>{m.set('bottoms',{mode:'item',id:'PN007'});assert.equal(m.operation('anchor',ctx).selection.pantId,'PN007');assert.equal(m.operation('engine',ctx).request.pantBindings.length,0);});
test('Unsupported B01 remains explicit, not another blazer',()=>{m.set('topwear',{mode:'item',id:m.rows.topwear.find(r=>r.sourceId==='B01').id});assert.throws(()=>m.operation('anchor',ctx));});
test('Shirt-only route carries no fictitious topwear identifier',()=>{init();m.set('topwear',{mode:'item',id:'ui:shirt-only'});m.set('shirt',{mode:'item',id:'DS001'});m.set('bottoms',{mode:'item',id:'PG002'});const s=m.operation('anchor',ctx).selection;assert.equal(s.shirtOnly,true);assert.ok(!('suitId'in s)&&!('blazerId'in s));assert.equal(c.historyIds(s).topwear,null);});
test('Unimplemented shirt-only ranking is not invented by facade',()=>assert.throws(()=>m.operation('engine',ctx)));
test('Unsupported no-tie source is rejected, not forced to T001',()=>{m.set('tie',{mode:'none'});assert.throws(()=>m.operation('anchor',ctx));});
test('No-tie-only shirt restrictions remain current engine rules',()=>{init();m.set('shirt',{mode:'item',id:'DS041'});assert.throws(()=>m.operation('anchor',ctx));m.set('tie',{mode:'none'});assert.equal(m.operation('anchor',ctx).selection.state,'NO_TIE');});
test('Search by current ID and current name',()=>{assert.equal(m.filter('shirt',{query:'DS036'})[0].id,'DS036');assert.ok(m.filter('watch',{query:'5712'}).some(r=>r.id==='watch-P05'));});
test('Cross-category lookups never reuse a Shirt result as Suit',()=>{m.filter('shirt',{query:'DS036'});assert.ok(m.filter('topwear',{type:'suit'}).every(r=>r.kind==='suit'));});
test('Unknown category fails explicitly',()=>assert.throws(()=>m.begin('not-a-category')));
test('Model returns isolated copies of preferences',()=>{init();const v=m.snapshot();v.shirt.id='DS049';assert.equal(m.snapshot().shirt.id,'DS036');});
test('Replacing malformed preferences is atomic',()=>{const before=m.snapshot(),bad=m.snapshot();bad.watch={mode:'item',id:'bad'};assert.throws(()=>m.replace(bad));eq(m.snapshot(),before);});
test('No source catalogue, scoring rule or numerical mapping was changed',()=>assert.equal(JSON.stringify(cx.HEWRS_INPUTS),raw));
const out={scope:'UI draft/identity adapter only; no rendered/device certification',passed:tests.filter(r=>r.status==='PASS').length,failed:tests.filter(r=>r.status==='FAIL').length,tests};const p=process.env.HEWRS_FACELIFT_TEST_OUTPUT||R+'/evidence/facelift_v1_11/FUNCTIONAL.json';fs.writeFileSync(p,JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));if(out.failed)process.exitCode=1;
