#!/usr/bin/env python3
"""Exact-source facelift regression; memory-loaded browser, not hosted/iPhone."""
import os,json,time,traceback,hashlib,base64,io
from pathlib import Path
from PIL import Image
from playwright.sync_api import sync_playwright
from facelift_harness import R,load,ensure
E=Path(os.environ.get('HEWRS_FACELIFT_BROWSER_OUTPUT',R/'evidence/facelift_v1_11/browser'));E.mkdir(parents=True,exist_ok=True)
checks=[];renders=[];errors=[];start=time.monotonic()
def ck(name,ok,detail=None):
 checks.append(dict(name=name,pass_=bool(ok),detail=detail));print(('PASS ' if ok else 'FAIL ')+name,flush=True)
 save()
 if not ok:raise AssertionError(name+' '+str(detail))
def save():
 (E/'BROWSER.json').write_text(json.dumps(dict(scope='Actual packaged scripts and PNG bytes in memory-loaded Chromium. Reopen tests use an explicit memory-backed storage fixture; not hosted, native iOS/Safari or real-browser restart persistence.',passed=sum(x['pass_'] for x in checks),failed=sum(not x['pass_'] for x in checks),checks=checks,native_render_comparisons=renders,page_errors=errors,seconds=round(time.monotonic()-start,2)),indent=2)+'\n')
def sha(p):
 data=base64.b64decode(p.evaluate("document.getElementById('avatar').toDataURL('image/png')").split(',')[1]);return hashlib.sha256(Image.open(io.BytesIO(data)).convert('RGBA').tobytes()).hexdigest()
def S(s='S05',h='DS036',t='T017',sh='shoe-8',w=None):return dict(suitId=s,shirtId=h,state=t,shoeId=sh,watchId=w)
def B(b='B03',p='PG002',t='T017',sh='shoe-8',w=None):return dict(blazerId=b,pantId=p,shirtId='DS001',state=t,shoeId=sh,watchId=w)
def O(p='PG002',t='T017',sh='shoe-8'):return dict(shirtOnly=True,pantId=p,shirtId='DS001',state=t,shoeId=sh,watchId=None)
controls=[S(),S('S05','DS035','NO_TIE'),S('S05','DS035','REFERENCE'),S('S05','DS051','T001'),S('S01','DS017'),S('S11','DS035'),S('S11','DS035','NO_TIE'),S('S18','DS036','T022'),S('S11','DS041','NO_TIE'),S('S04','DS047','T022'),S('S10','DS015'),S('S16','DS051','NO_TIE'),B(),B('B06','PN007','T017','shoe-6','watch-P05'),B('B14','PT001','T001'),O(),O('PN007','T022','shoe-6')]
with sync_playwright() as pw:
 browser=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage']);p=browser.new_page(viewport=dict(width=390,height=844));p.on('pageerror',lambda e:errors.append(str(e)))
 def choose(cat,item):
  p.click('#pref-'+cat);p.fill('#picker-search',item);p.locator('[data-item-id="'+item+'"]').click();p.click('#picker-apply')
 try:
  load(p,storage={'production_sentinel':'UNCHANGED'},preload=controls+[S('S11',w='watch-P05')]);ck('V1.11 loads without errors',p.evaluate("HEWRS_READY&&HEWRSApp.version==='HEWRS_CONNECTED_APP_V1_11'") and not errors)
  ck('Opening writes no storage or production key',p.evaluate("__STORAGE_CALLS.every(x=>x[0]==='get'&&x[1]===HEWRSApp.store.key)&&__STORAGE_MAP.get('production_sentinel')==='UNCHANGED'"))
  ck('One router nav, one native canvas, unique DOM identifiers',p.evaluate("()=>{const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);return new Set(ids).size===ids.length&&document.querySelectorAll('.bottom-nav').length===1&&document.querySelectorAll('#avatar').length===1;}"))
  ck('Original palette tokens match handoff',p.evaluate("getComputedStyle(document.getElementById('app')).getPropertyValue('--bg').trim()==='#060E19'&&getComputedStyle(document.getElementById('app')).getPropertyValue('--gold').trim()==='#D8A247'"))
  ck('No ancestor filter/blend/opacity changes garment colors',p.evaluate("()=>{let e=document.getElementById('avatar');while(e){const s=getComputedStyle(e);if(s.filter!=='none'||s.opacity!=='1'||s.mixBlendMode!=='normal')return false;e=e.parentElement;}return true;}"))
  before=p.evaluate('HEWRSApp.ui.snapshot()');p.click('#pref-shirt');p.fill('#picker-search','DS017');p.locator('[data-item-id="DS017"]').click();ck('Item click remains draft until Apply',p.evaluate('HEWRSApp.ui.snapshot()')==before);p.keyboard.press('Escape');ck('Escape cancels and restores tile focus',p.evaluate('HEWRSApp.ui.snapshot()')==before and p.evaluate('document.activeElement.id')=='pref-shirt')
  choose('shirt','DS017');after=p.evaluate('HEWRSApp.ui.snapshot()');ck('Apply changes only the selected category',after['shirt']['id']=='DS017' and all(after[k]==v for k,v in before.items() if k!='shirt'))
  p.click('#pref-shirt');p.select_option('#picker-color','brown');ck('Incompatible exact draft is cleared on filter change',p.evaluate('HEWRSApp.ui.draft().choice===null') and p.locator('#picker-apply').is_disabled());p.keyboard.press('Escape')
  p.click('#pref-tie');p.locator('[data-item-id="NO_TIE"]').click();p.click('#picker-apply');ck('No Tie stays distinct from Engine',p.evaluate("HEWRSApp.ui.snapshot().tie.mode==='none'"))
  p.click('#work-button');p.select_option('#occasion-select','hospital');p.get_by_role('button',name='Cancel',exact=True).click();ck('Context Cancel does not commit',p.evaluate("HEWRSApp.state().context.occasion==='clinic'"))
  p.click('#style-button');p.select_option('#style-select','CLASSIC');p.get_by_role('button',name='Apply',exact=True).click();ck('Style maps to existing CLASSIC value',p.evaluate("HEWRSApp.state().context.style==='CLASSIC'"))
  choose('topwear','B03');choose('bottoms','PG002');snapshot=p.evaluate('HEWRSApp.ui.snapshot()');pairs=[]
  for first in ['topwear','shirt','tie','shoes','bottoms','watch']:
   for second in ['topwear','shirt','tie','shoes','bottoms','watch']:
    p.evaluate('(c)=>HEWRSApp.openPicker(c)',first);p.keyboard.press('Escape');p.evaluate('(c)=>HEWRSApp.openPicker(c)',second)
    pairs.append(p.evaluate('c=>{const ids=new Set(HEWRSApp.ui.rows[c].map(r=>r.sourceId||r.id));return [...document.querySelectorAll("#picker-list [data-item-id]")].every(x=>["NO_TIE","NO_WATCH"].includes(x.dataset.itemId)||ids.has(x.dataset.itemId))&&document.querySelectorAll("dialog[open]").length===1;}',second));p.keyboard.press('Escape')
  ck('All 36 directed category-opening pairs keep current identities isolated',all(pairs),len(pairs));ck('Picker browsing/cancel creates no anchors or wear',p.evaluate('HEWRSApp.ui.snapshot()')==snapshot and p.evaluate('HEWRSApp.store.snapshot().events.length')==0)
  choose('watch','watch-P05');ck('Watch accepts ID/name without photo',p.evaluate("HEWRSApp.ui.snapshot().watch.id==='watch-P05'"));choose('topwear','S11');ck('Suit includes trousers but preserves dormant separate selection',p.locator('#pref-bottoms').is_disabled() and p.evaluate("HEWRSApp.ui.snapshot().bottoms.id==='PG002'"));choose('topwear','B03');ck('Blazer restores same independent Bottoms',not p.locator('#pref-bottoms').is_disabled() and p.evaluate("HEWRSApp.ui.snapshot().bottoms.id==='PG002'"))
  p.click('#reset-preferences');p.get_by_role('button',name='Cancel',exact=True).click();ck('Reset Cancel preserves preferences',p.evaluate('HEWRSApp.ui.lockCount()>0'));p.click('#reset-preferences');p.get_by_role('button',name='Confirm reset',exact=True).click();p.click('#mode-anchor');p.click('#generate-options');ck('Anchor without choices does not invent S05/shoes',p.evaluate('HEWRSApp.ui.lockCount()')==0 and 'exact' in p.inner_text('#home-notice').lower())
  for cat,item in [('topwear','S11'),('shirt','DS036'),('tie','T017'),('shoes','shoe-8'),('watch','watch-P05')]:choose(cat,item)
  p.click('#mode-engine');prefs=p.evaluate('HEWRSApp.ui.snapshot()');p.click('#generate-options');p.wait_for_function('() => !HEWRSApp.state().busy&&HEWRSApp.state().page==="outfits"',timeout=30000)
  ck('Generate uses real Engine and current renderer',p.evaluate("HEWRSApp.state().origin==='engine'&&HEWRSApp.state().selection.suitId==='S11'&&HEWRSApp.state().selection.shirtId==='DS036'&&HEWRSApp.state().optionCount>0"))
  ck('Actual /10 score and watch ID/name displayed',p.evaluate("document.getElementById('score-value').textContent===HEWRSApp.state().score.display_score.toFixed(2)&&document.getElementById('representation').textContent.includes('watch-P05')&&document.getElementById('representation').textContent.includes('5712')"))
  p.click('#back-home');ck('Returning Home restores producing preferences',p.evaluate('HEWRSApp.ui.snapshot()')==prefs);p.click('#view-current');p.click('#regenerate');p.wait_for_function('() => !HEWRSApp.state().busy',timeout=30000);ck('Regenerate retains same producing inputs',p.evaluate('HEWRSApp.ui.snapshot()')==prefs);ck('Generation/navigation never log wear',p.evaluate('HEWRSApp.store.snapshot().events.length')==0)
  p.evaluate('HEWRSApp.showPage("wardrobe")');ck('All nine current catalogue groups remain, including Jeans/T-Shirts',p.locator('#wardrobe-groups [data-category]').count()==9);snapshot=p.evaluate('HEWRSApp.ui.snapshot()');p.click('[data-category="watches"]');p.fill('#wardrobe-search','5712');p.locator('[data-record-id="watch-P05"]').click();ck('Watch details show name/ID without made-up image','5712' in p.inner_text('#fx-sheet-body') and p.locator('#fx-sheet-body img').count()==0);p.keyboard.press('Escape');ck('Wardrobe browse leaves preferences/history unchanged',p.evaluate('HEWRSApp.ui.snapshot()')==snapshot and p.evaluate('HEWRSApp.store.snapshot().events.length')==0)
  p.evaluate('HEWRSApp.showPage("outfits")');p.click('#quick-log');p.evaluate('document.getElementById("record-wear").click()');ck('Both Log controls share one confirmation',p.locator('dialog[open]').count()==1 and p.locator('#confirm-wear').count()==1);p.evaluate('()=>{const b=document.getElementById("confirm-wear");b.click();b.click();}');ck('Repeated same-confirmation activation creates one event',p.evaluate('HEWRSApp.store.snapshot().events.length')==1)
  event=p.evaluate('HEWRSApp.store.snapshot().events[0]');ck('Logged event retains current exact IDs',event['canonical_selection']['suitId']=='S11' and event['items']['watch']['id']=='watch-P05' and event['items']['pants'] is None)
  p.evaluate('HEWRSApp.showPage("wardrobe")');p.click('#data-button');backup=p.evaluate('HEWRSApp.store.exportText()');writes=p.evaluate("__STORAGE_CALLS.filter(x=>x[0]==='set').length");p.set_input_files('#backup-file',dict(name='TEST_BACKUP.json',mimeType='application/json',buffer=backup.encode()));p.wait_for_function('() => !document.getElementById("confirm-restore").disabled');ck('Import preview does not write',p.evaluate("__STORAGE_CALLS.filter(x=>x[0]==='set').length")==writes);p.get_by_role('button',name='Cancel',exact=True).click();ck('Cancelling import retains exact saved bytes',p.evaluate('HEWRSApp.store.exportText()')==backup)
  p.click('#data-button');p.set_input_files('#backup-file',dict(name='INVALID.json',mimeType='application/json',buffer=b'{broken'));p.wait_for_function('() => document.getElementById("fx-sheet-error").textContent.length>0');ck('Invalid import keeps history unchanged',p.locator('#confirm-restore').is_disabled() and p.evaluate('HEWRSApp.store.exportText()')==backup);p.keyboard.press('Escape');p.click('#data-button');p.set_input_files('#backup-file',dict(name='TEST_BACKUP.json',mimeType='application/json',buffer=backup.encode()));p.wait_for_function('() => !document.getElementById("confirm-restore").disabled');p.click('#confirm-restore');p.wait_for_function('() => !document.getElementById("fx-sheet").open&&!HEWRSApp.state().busy');ck('Explicit restore uses inherited validation and keeps event identities',p.evaluate('HEWRSApp.store.snapshot().events[0]')==event)
  p.evaluate('HEWRSApp.showPage("rotation")');p.click('#clear-log');p.get_by_role('button',name='Cancel',exact=True).click();ck('Clear Cancel preserves wear data',p.evaluate('HEWRSApp.store.snapshot().events.length')==1);ck('Production sentinel unaffected',p.evaluate("__STORAGE_MAP.get('production_sentinel')==='UNCHANGED'"))
  seed=p.evaluate('Object.fromEntries(__STORAGE_MAP)');reopen=browser.new_page(viewport=dict(width=390,height=844));load(reopen,storage=seed,preload=[S('S11',w='watch-P05')]);ck('Fresh document restores existing schema via memory storage fixture',reopen.evaluate('HEWRSApp.state().selection')==p.evaluate('HEWRSApp.state().selection') and reopen.evaluate('HEWRSApp.store.snapshot().events[0]')==event);reopen.close()
  old=browser.new_page(viewport=dict(width=390,height=844));load(old,baseline=True,preload=controls)
  for i,s in enumerate(controls):
   p.evaluate('(s)=>HEWRSApp.apply(s,{save:false})',s);old.evaluate('(s)=>HEWRSApp.apply(s,{save:false})',s);ha,hb=sha(p),sha(old);renders.append(dict(selection=s,before_rgba_sha256=hb,after_rgba_sha256=ha,equal=ha==hb));print('RENDER',i+1,ha==hb,flush=True)
  ck('All 17 native render comparisons match V1.10 pixel-for-pixel',all(x['equal'] for x in renders),dict(count=len(renders),canvas=[996,2748]));old.close()
  before=sha(p);rej=p.evaluate('''async()=>{try{await HEWRSApp.apply({blazerId:'B01',pantId:'PG002',shirtId:'DS001',state:'T017',shoeId:'shoe-8',watchId:null},{save:false});return false;}catch(e){return true;}}''');ck('Unsupported source request retains prior native frame',rej and sha(p)==before)
  cfg=dict(blazerId='B03',pantId='PN007',shirt='DS001',tie='T017',shoeId='shoe-8',watchId=None,localDate='2026-09-23',occasion='clinic',formality='any',style='AUTO');out=p.evaluate('(c)=>HEWRSApp.generate(c)',cfg);ck('Empty scoring output hides the previous frame as a new result',not out.get('options') and p.locator('#outfit-output').is_hidden() and p.locator('#outfit-empty').is_visible())
  out=p.evaluate('''async()=>{const task=HEWRSApp.generate({suitId:'S05',shirt:'ANY',tie:'ANY',shoeId:'shoe-8',watchId:null,localDate:'2026-09-23',occasion:'clinic',formality:'any',style:'AUTO'});HEWRSApp.cancel();return await task;}''');ck('Cancellation uses existing generator tokens',out.get('cancelled') is True and p.evaluate('!HEWRSApp.state().busy'))
  p.evaluate('HEWRSApp.ui.fromSelection({suitId:"S05",shirtId:"DS036",state:"T017",shoeId:"shoe-8",watchId:null});HEWRSApp.showPage("home");document.getElementById("home-notice").textContent="";');layouts=[]
  for w,h in [(320,640),(360,740),(375,667),(390,844),(393,852),(402,874),(414,896),(430,932),(440,956)]:
   p.set_viewport_size(dict(width=w,height=h));layouts.append(p.evaluate('''()=>{const a=document.getElementById('page-home'),r=a.getBoundingClientRect(),g=document.getElementById('generate-options').getBoundingClientRect(),n=document.querySelector('.bottom-nav').getBoundingClientRect();return {width:innerWidth,height:innerHeight,homeWidth:r.width,client:a.clientHeight,scroll:a.scrollHeight,generateBottom:g.bottom,navTop:n.top,docWidth:document.documentElement.scrollWidth};}'''))
  ck('Nine normal portrait Home layouts fit without clipping/scroll',all(x['scroll']<=x['client']+1 and x['generateBottom']<=x['navTop'] and x['docWidth']<=x['width'] for x in layouts),layouts);ck('Approved 89% Home column retained',all(abs(x['homeWidth']/x['width']-.89)<.002 for x in layouts))
  p.set_viewport_size(dict(width=390,height=844));p.click('#pref-shirt');focus=[]
  for _ in range(20):p.keyboard.press('Tab');focus.append(p.evaluate("document.getElementById('fx-sheet').contains(document.activeElement)"))
  ck('Native modal keyboard focus stays contained',all(focus));p.keyboard.press('Escape');p.set_viewport_size(dict(width=844,height=390));p.click('#pref-watch');p.locator('#picker-list').evaluate('(n)=>n.scrollTop=n.scrollHeight');ck('Short landscape sheet keeps Apply reachable',p.locator('#picker-apply').is_visible() and p.locator('#picker-apply').bounding_box()['y']<390);p.keyboard.press('Escape')
  p.set_viewport_size(dict(width=390,height=844));p.add_style_tag(content='.hewrs-ui button,.hewrs-ui p,.hewrs-ui span{font-size:20px!important;}');p.click('#pref-watch');p.locator('#picker-apply').scroll_into_view_if_needed();ck('Synthetic large text preserves access to Apply via scrolling',p.locator('#picker-apply').bounding_box()['y']<844);p.keyboard.press('Escape');ck('No unexpected script errors',not errors,errors);save()
  shot=browser.new_page(viewport=dict(width=390,height=844));load(shot,preload=[S('S11',w='watch-P05')]);shot.screenshot(path=str(E/'HOME_390x844.png'));shot.evaluate('HEWRSApp.ui.fromSelection({suitId:"S11",shirtId:"DS036",state:"T017",shoeId:"shoe-8",watchId:"watch-P05"});HEWRSApp.showPage("home");HEWRSApp.setMode("engine")');shot.click('#generate-options');shot.wait_for_function('() => !HEWRSApp.state().busy&&HEWRSApp.state().page==="outfits"');shot.screenshot(path=str(E/'OUTFITS_390x844.png'));shot.click('[data-page="wardrobe"]');shot.screenshot(path=str(E/'WARDROBE_390x844.png'));shot.click('[data-page="rotation"]');shot.screenshot(path=str(E/'ROTATION_390x844.png'));shot.click('[data-page="home"]');shot.click('#pref-watch');shot.fill('#picker-search','5712');shot.screenshot(path=str(E/'WATCH_PICKER_390x844.png'));shot.close()
  no=browser.new_page(viewport=dict(width=390,height=844),java_script_enabled=False);no.set_content((R/'app.template.html').read_text().replace('<!--STYLE-->','<style>'+(R/'src/application.css').read_text()+'</style>').replace('<!--SCRIPTS-->',''));ck('No-script Home remains visible and honestly unavailable',no.locator('noscript').is_visible() and no.locator('[data-picker]').count()==6 and no.locator('#generate-options').is_disabled());no.screenshot(path=str(E/'NO_SCRIPT_390x844.png'));no.close();save()
 except Exception as e:errors.append('TEST_ERROR: '+str(e));save();traceback.print_exc();raise
 finally:browser.close()
