'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),load=require('./core-loader.cjs');
const R=path.resolve(__dirname,'..'),B=process.env.HEWRS_BASELINE||'/mnt/data/hybrid1190/baseline',root=load(R),c=root.HEWRSCleanConnection.create(root.HEWRS_INPUTS),oldRoot=load(B),old=oldRoot.HEWRSCleanConnection.create(oldRoot.HEWRS_INPUTS),checks=[];
const clone=x=>JSON.parse(JSON.stringify(x)),eq=(a,b)=>assert.deepEqual(clone(a),clone(b));
const cfg=(patch={},style='curated')=>({automatic:true,stylistMode:style,preferences:{...Object.fromEntries(['topwear','shirt','tie','shoes','bottoms','watch'].map(k=>[k,{mode:'any'}])),...patch},localDate:'2026-09-28',style:'AUTO',occasion:'clinic',formality:'any',environment:{source:'not_assessed',date:'2026-09-28'}});
root.setInterval=setInterval;root.clearInterval=clearInterval;
const q=c.makeRequest(cfg()),base=c.controller.generate(q,c.catalogue,[]);
function test(name,fn){try{const result=fn();checks.push({name,passed:true,result:result??null});}catch(e){checks.push({name,passed:false,error:e.stack});}}
function independentCaps(rows,p){const counts=new Map(),exempt=new Set(root.HEWRSOptionSetPolicy.exactLocks(p));let nt=0;const clothes=new Set();for(let o of rows){for(const item of Object.values(o.items))if(item?.id)counts.set(item.id,(counts.get(item.id)||0)+1);if(!o.items.tie)nt++;const k=['topwear','shirt','tie','pants'].map(k=>o.items[k]?.id||'-').join('|');assert.ok(!clothes.has(k));clothes.add(k);}for(let [id,n]of counts)assert.ok(exempt.has(id)||n<=2,id+':'+n);assert.ok(p.prefs.tie.mode==='none'||nt<=2);return {counts:Object.fromEntries(counts),no_tie:nt};}
test('Baseline exact source scope preserved; 18 nonsuit /50 suit shirts /47 ties /32 tops',()=>{eq(c.records,old.records);eq(c.catalogue,old.catalogue);eq(c.nonSuitSources.connectedIds,old.nonSuitSources.connectedIds);assert.equal(c.nonSuitSources.connectedIds.length,18);assert.equal(c.manifest.shirt_order.length,50);assert.equal(Object.keys(c.manifest.ties).length,47);});
test('94 explicit complete-look references; unchanged source lock',()=>{assert.equal(c.hybrid.library.records.length,94);assert.equal(c.hybrid.library.source_lock,root.HEWRS_INPUT_SHA256);assert.equal(new Set(c.hybrid.library.records.map(x=>x.id)).size,94);});
test('No-anchor default returns15 reference outfits, not relabelled heuristic or AI',()=>{assert.equal(base.options.length,15);assert.ok(Object.values(q.prefs).every(x=>x.mode==='any'));assert.equal(base.option_policy.exact_anchor_exemptions.length,0);assert.equal(base.stylist.live_ai_used,false);assert.ok(base.options.every(o=>o._hewrsConnected.stylist.method==='curated'&&!o._hewrsConnected.preference));return independentCaps(base.options,q);});
test('14 independently preferred no-anchor references retained exactly; held reference excluded',()=>{const selected=base.options.map(x=>x._hewrsConnected.stylist.reference_id);for(let i=1;i<=15;i++)assert.equal(selected.includes('REF_FREE_'+String(i).padStart(2,'0')),i!==12);assert.ok(base.diagnostics.rejected.some(x=>x.id==='REF_FREE_12'&&x.code==='SOURCE_HOLD'));});
test('Every returned item and unchanged source score revalidates; all15 exact canonical selections',()=>{assert.ok(c.controller.verifyOptionSet(base.options,q));for(let o of base.options){eq(c.selectionFromOption(o,q).selection,o._hewrsConnected.canonical_selection);eq(o._hewrsConnected.compatibility,old.scoreSelection(o._hewrsConnected.canonical_selection,q.context));}});
test('Forged model/grade/explanation and changed IDs cannot be recalled as issued options',()=>{for(let key of ['explanation','model','grade']){let o=clone(base.options[0]);o._hewrsConnected.stylist[key]='forged';assert.equal(c.controller.verifyCachedOption(o,q,c.catalogue),false);}let o=clone(base.options[0]);o._hewrsConnected.canonical_selection.shirtId='DS034';assert.equal(c.controller.verifyCachedOption(o,q,c.catalogue),false);});
test('All32 exact jacket anchors keep locks/caps; limited-library counts disclosed',()=>{let results=[];for(let id of [...c.suitSources.ids,...c.blazerConnection.availableIds]){let top=id[0]==='S'?c.aliases.get(id):c.blazerConnection.knownBlazer(id).historyId,p=c.makeRequest(cfg({topwear:{mode:'item',id:top}})),r=c.controller.generate(p,c.catalogue,[]);assert.ok(r.options.length>0,id);for(let o of r.options)assert.equal(o.items.topwear.id,top);independentCaps(r.options,p);assert.ok(c.controller.verifyOptionSet(r.options,p));if(r.options.length<15)assert.ok(r.reason.includes('no heuristic filler'));results.push({id,options:r.options.length});}fs.writeFileSync(R+'/evidence/hybrid_v1_19_0/ALL32_CURATED_ANCHORS.json',JSON.stringify(results,null,2));return results;});
test('Explicit shoes/watch anchors adapt references only to exact selected items',()=>{const p=c.makeRequest(cfg({shoes:{mode:'item',id:'shoe-3'},watch:{mode:'item',id:'watch-P05'}})),r=c.controller.generate(p,c.catalogue,[]);assert.equal(r.options.length,15);for(let o of r.options){assert.equal(o.items.shoes.id,'shoe-3');assert.equal(o.items.watch.id,'watch-P05');}independentCaps(r.options,p);});
test('Family preferences are not exact exemptions',()=>{let p=c.makeRequest(cfg({shirt:{mode:'family',id:'lavender'}})),r=c.controller.generate(p,c.catalogue,[]);assert.ok(r.options.length);assert.equal(r.option_policy.exact_anchor_exemptions.length,0);for(let o of r.options)assert.ok(c.preference.matchesFamily(o._hewrsConnected.canonical_selection.shirtId,'lavender'));independentCaps(r.options,p);});
test('Explicit No Tie lifts only No Tie count; physical caps still apply',()=>{let p=c.makeRequest(cfg({tie:{mode:'none'}})),r=c.controller.generate(p,c.catalogue,[]);assert.ok(r.options.length>2);assert.ok(r.options.every(x=>x.items.tie===null));independentCaps(r.options,p);});
test('Unknown items, unconnected nonsuit shirts and No-Tie-only guards stay explicit',()=>{assert.throws(()=>c.makeRequest(cfg({shirt:{mode:'item',id:'DS999'}})));let s={blazerId:'B03',pantId:'PG002',shirtId:'DS035',state:'T017',shoeId:'shoe-3',watchId:null};assert.equal(c.hybrid.assess(s,q).eligible,false);assert.throws(()=>c.validateSelection({suitId:'S10',shirtId:'DS042',state:'T017',shoeId:'shoe-3',watchId:null}));});
test('Unresolved watch slot preserved in inventory/history but excluded from recommendations',()=>{assert.ok(c.catalogue.watches.some(x=>x.id==='watch-R18'));assert.equal(c.hybrid.identifiedWatch(c.catalogue.watches.find(x=>x.id==='watch-R18')),false);assert.throws(()=>c.makeRequest(cfg({watch:{mode:'item',id:'watch-R18'}})));assert.equal(c.hybrid.assess({...base.options[0]._hewrsConnected.canonical_selection,watchId:'watch-R18'},q).code,'UNRESOLVED_WATCH');});
test('Weather rules apply to every curated result without touching environment or source data',()=>{let input=cfg();input.environment={source:'manual',date:'2026-09-28',season:'Fall',temperatureBand:'mildWarm',precipitation:'dry',latitude:42,locationLabel:'Manual'};try{const p=c.makeRequest(input),r=c.controller.generate(p,c.catalogue,[]);for(let o of r.options)assert.equal(o._hewrsConnected.environment.eligible,true);return {options:r.options.length};}catch(e){throw e;}});
test('Source/premise conflicts are not filled with invented numerical grades',()=>{const s=c.hybrid.library.records.find(x=>x.id==='REF_FREE_12').selection;assert.equal(c.hybrid.assess(s,q).code,'SOURCE_HOLD');eq(old.scoreSelection(s,q.context),c.scoreSelection(s,q.context));});
test('Unreadable/stale ledger guard remains byte-identical to accepted V1.18.0',()=>{assert.equal(fs.readFileSync(R+'/src/local-state.js','utf8'),fs.readFileSync(B+'/src/local-state.js','utf8'));const be={getItem:()=>'{broken',setItem:()=>{throw Error('Unexpected write');}},st=root.HEWRSLocalState.create(c,root.HEWRS_INPUT_SHA256,be);assert.throws(()=>st.readForGeneration());});
test('Generation changes neither catalogue, raw score data nor passed history',()=>{const before=JSON.stringify([c.catalogue,root.HEWRS_INPUTS]);c.controller.generate(q,c.catalogue,[]);assert.equal(JSON.stringify([c.catalogue,root.HEWRS_INPUTS]),before);});
test('All39,817 supported suit routes remain valid',()=>{let n=0;for(let id of c.suitSources.ids)for(let shirt of c.manifest.shirt_order)for(let state of c.manifest.shirts[shirt].available_modes){if(state==='REFERENCE'&&id!=='S05')continue;c.validateSelection({suitId:id,shirtId:shirt,state,shoeId:'shoe-3',watchId:null});n++;}assert.equal(n,39817);return n;});
(async()=>{
 async function at(name,fn){try{checks.push({name,passed:true,result:await fn()});}catch(e){checks.push({name,passed:false,error:e.stack});}}
 await at('Unconfigured visual mode fails before any render/provider call; no fallback relabelled AI',async()=>{const p=c.makeRequest(cfg({},'visual'));let count=0;await assert.rejects(c.controller.generateAsync(p,c.catalogue,[],{renderForStylist:()=>{count++;}}),/not connected/);assert.equal(count,0);});
 await at('Live workflow carries fixture renderer payloads for every candidate; rejects malicious rank IDs',async()=>{
  const p=c.makeRequest(cfg({},'visual'));let posted,rendered=0;
  const service={ready:()=>true,propose:async()=>({job_id:'fixture-job',proposals:[{selection:base.options[0]._hewrsConnected.canonical_selection,rationale:'Fixture proposal'}]}),evaluate:async(q,images)=>{posted=images;return {method:'live_visual',provider:'TEST FIXTURE — not provider execution',model:'FIXTURE_MODEL',job_id:'fixture-job',ranking:images.map((x,i)=>({candidate_id:x.candidate_id,grade:'strong',explanation:'Fixture response to test routing only.'}))};}};
  c.hybrid.setService(service);const r=await c.controller.generateAsync(p,c.catalogue,[],{renderForStylist:async()=>{rendered++;return 'data:image/jpeg;base64,FIXTURE';}});assert.equal(posted.length,rendered);assert.ok(rendered>15);assert.ok(c.controller.verifyOptionSet(r.options,p));independentCaps(r.options,p);assert.equal(r.stylist.live_ai_used,true);
  service.evaluate=async()=>({method:'live_visual',ranking:new Array(rendered).fill({candidate_id:'FORGED',grade:'strong',explanation:'x'})});await assert.rejects(c.controller.generateAsync(p,c.catalogue,[],{renderForStylist:async()=>''}),/Unknown, duplicate/);c.hybrid.setService(null);return {candidates:rendered,external_provider_calls:0};});
 await at('Visual cancellation does not generate partial results',async()=>{const p=c.makeRequest(cfg({},'visual'));let off=false;c.hybrid.setService({ready:()=>true,propose:async()=>{off=true;return {proposals:[]};}});let r=await c.controller.generateAsync(p,c.catalogue,[],{isCancelled:()=>off,renderForStylist:async()=>{throw Error('should not render');}});assert.equal(r.status,'cancelled');c.hybrid.setService(null);});
 await at('Service client sends no ledger/coordinates; rejects provider keys in browser',async()=>{let sent=[];const client=root.HEWRSVisualStylistClient.create({config:{endpoint:'https://stylist.example.test'},fetcher:async(url,o)=>{sent.push([url,JSON.parse(o.body),o]);return {ok:true,status:200,text:async()=>JSON.stringify({schema:'hewrs.visual-stylist.v1',token:'a'.repeat(40),expires_at:Date.now()/1000+1000,live_ready:true})};}});await assert.rejects(client.login('sk-'+'a'.repeat(50)),/provider API key/);assert.equal(sent.length,0);await client.login('private-service-password-123');assert.ok(client.ready());let pub=client.publicRequest(q);assert.equal(JSON.stringify(pub).includes('latitude'),false);assert.equal(JSON.stringify(pub).includes('events'),false);assert.ok(!pub.environment);client.disconnect();assert.equal(client.ready(),false);});
 const out={schema:'hewrs.hybrid.functional.v1_19_0',passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks,scope:'Node VM, exact local modules, isolated fixture transport; no live API calls'};fs.writeFileSync(R+'/evidence/hybrid_v1_19_0/FUNCTIONAL.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));if(out.failed)process.exitCode=1;
})();
