'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto'),assert=require('node:assert/strict');
const R=path.resolve(__dirname,'..'),B=process.env.HEWRS_BASELINE;assert(B,'HEWRS_BASELINE required');
const checks=[];function ck(name,fn){try{checks.push({name,passed:true,result:fn()??null});}catch(e){checks.push({name,passed:false,error:e.stack});}}
const raw=fs.readFileSync(R+'/src/option-cards.js','utf8'),ctx=vm.createContext({structuredClone});vm.runInContext(raw,ctx);const model=ctx.HEWRSOptionCards.model;
const p=JSON.parse(fs.readFileSync(R+'/data/inputs.json')),m=p.manifest,t=JSON.parse(fs.readFileSync(R+'/data/option-card-thumbnails.json'));
function items(s){return [{role:'Suit / Blazer',id:s.suitId||s.blazerId||null,name:'Exact topwear'},{role:'Shirt',id:s.shirtId,name:m.shirts[s.shirtId].label},{role:'Tie',id:s.state==='NO_TIE'?null:s.state,name:s.state},{role:'Shoes',id:s.shoeId,name:s.shoeId},{role:'Bottoms',id:s.pantId||null,name:'Trousers'},{role:'Watch',id:s.watchId||null,name:'Watch'}];}
const sel={suitId:'S10',shirtId:'DS035',state:'T022',shoeId:'shoe-8',watchId:'watch-P05'};
ck('All50 shirt,47 tie,35 registered footwear thumbnail IDs match exact source universes',()=>{assert.deepEqual(Object.keys(t.shirts).sort(),Object.keys(m.shirts).sort());assert.deepEqual(Object.keys(t.ties).sort(),Object.keys(m.ties).sort());assert.deepEqual(Object.keys(t.shoes).sort(),Object.keys(p.shoeLayers).sort());return t.counts;});
ck('All132 UI thumbnail hashes and every declared source hash match bytes',()=>{let n=0;for(const g of ['shirts','ties','shoes'])for(const d of Object.values(t[g])){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/'+d.url)).digest('hex'),d.sha256);for(const a of d.source_layers)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/'+a.path)).digest('hex'),a.sha256);n++;}return n;});
ck('All source-supported suit/card selections retain exact IDs and mode',()=>{let n=0;for(let i=1;i<=18;i++)for(const id of m.shirt_order)for(const state of m.shirts[id].available_modes){if(state==='REFERENCE'&&(i!==5||id!=='DS035'))continue;const s={...sel,suitId:'S'+String(i).padStart(2,'0'),shirtId:id,state};const out=model(s,items(s),n%20,20);assert.equal(JSON.stringify(out.selection),JSON.stringify(s));assert.equal(out.rows[1].id,state==='NO_TIE'?null:state);n++;}assert.equal(n,39817);return n;});
ck('Dynamic current,20-option and16-option numbering without hard-coded15',()=>{assert.equal(model(sel,items(sel),19,20).heading,'Option 20');assert.equal(model(sel,items(sel),15,16).count,'16 / 16');assert.equal(model(sel,items(sel),-1,0).heading,'Your outfit');});
ck('Blazer and shirt-only keep separate trouser IDs and correct topwear roles',()=>{for(const s of [{...sel,suitId:undefined,blazerId:'B03',pantId:'PG002'},{...sel,suitId:undefined,shirtOnly:true,pantId:'PN002'}]){const out=model(s,items(s));assert.equal(out.meta[0].id,s.pantId);assert.equal(out.top.role,s.blazerId?'Blazer':'Topwear');}});
ck('No Tie and REFERENCE remain text states,not fabricated tie IDs',()=>{for(const state of ['NO_TIE','REFERENCE']){const s={...sel,state};assert.equal(model(s,items(s)).rows[1].id,state==='NO_TIE'?null:state);}});
ck('Mismatched committed outfit/item labels are rejected',()=>{for(const role of ['Suit / Blazer','Shirt','Tie','Shoes','Bottoms','Watch']){const rows=items(sel);rows.find(x=>x.role===role).id='WRONG';assert.throws(()=>model(sel,rows));}});
ck('Shared image bytes never merge physical IDs',()=>{for(const ids of [['DS001','DS014'],['DS024','DS025'],['DS021','DS047']]){const outs=ids.map(shirtId=>{const s={...sel,shirtId};return model(s,items(s));});assert.notEqual(outs[0].rows[0].id,outs[1].rows[0].id);}});
ck('New view cannot require storage,network or renderer to build item models',()=>{const rows=items(sel),before=JSON.stringify({sel,rows});model(sel,rows,0,20);assert.equal(JSON.stringify({sel,rows}),before);assert(!('localStorage'in ctx));assert(!('fetch'in ctx));});
ck('Every non-presentation runtime source is byte-identical to V1.21.0',()=>{let n=0;const allowed=new Set(['src/application.css','src/application.js','data/option-card-thumbnails.js','src/option-cards.js']);const scripts=fs.readFileSync(R+'/tools/build.py','utf8').match(/SCRIPTS=(\[[^\n]+\])/)[1];for(const rel of JSON.parse(scripts.replaceAll("'",'"'))){if(allowed.has(rel))continue;assert(fs.readFileSync(R+'/'+rel).equals(fs.readFileSync(B+'/'+rel)),rel);n++;}return n;});
ck('Original848 runtime garment image files unchanged',()=>{const manifest=JSON.parse(fs.readFileSync(B+'/PACKAGE_SHA256.json'));const imgs=manifest.files.filter(x=>/^(assets|assemblies)\//.test(x.path)&&/\.(png|webp|jpg|jpeg)$/i.test(x.path));assert.equal(imgs.length,848);for(const x of imgs)assert.equal(crypto.createHash('sha256').update(fs.readFileSync(R+'/'+x.path)).digest('hex'),x.sha256);return imgs.length;});
ck('Application changes only initialize and update the presentation and version',()=>{let now=fs.readFileSync(R+'/src/application.js','utf8');now=now.replace("\nconst optionCards=root.HEWRSOptionCards.create({document});",'').replace(' optionCards.render(current,itemsFor(current),optionIndex,options.length);\n','').replace('weatherSheet,renderer,optionCards,ui,apply','weatherSheet,renderer,ui,apply').replace('HEWRS_CONNECTED_APP_V1_21_1','HEWRS_CONNECTED_APP_V1_21_0');assert.equal(now,fs.readFileSync(B+'/src/application.js','utf8'));});
const result={version:'1.21.1',passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks};fs.writeFileSync(R+'/evidence/option_cards_v1_21_1/FUNCTIONAL.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));if(result.failed)process.exitCode=1;
