'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const R=path.resolve(__dirname,'..'),load=require('./core-loader.cjs'),g=load(R),c=g.HEWRSCleanConnection.create(g.HEWRS_INPUTS),E=R+'/evidence/options_v1_17_3';const checks=[],cases=[];const plain=x=>JSON.parse(JSON.stringify(x));
const day='2026-09-27',env={source:'manual',date:day,temperatureBand:'mildWarm',precipitation:'dry',season:'Fall',locationLabel:'Synthetic audit condition'};
const item=id=>({mode:'item',id}),suit=id=>item(c.aliases.get(id)),blazer=id=>item(c.blazerConnection.knownBlazer(id).historyId);
const p=change=>({...Object.fromEntries(['topwear','shirt','tie','shoes','bottoms','watch'].map(k=>[k,{mode:'any'}])),...change});
const request=(ch={},more={})=>c.makeRequest({automatic:true,preferences:p(ch),style:'AUTO',localDate:day,occasion:'clinic',formality:'any',environment:env,...more});
function test(name,fn){try{checks.push({name,passed:true,result:fn()??null});console.log('PASS',name);}catch(e){checks.push({name,passed:false,error:e.stack});console.log('FAIL',name,e.message);}}
// Deliberately independent counter: do not trust the implementation's counts.
function independentlyCheck(o,q){const counts={},locks=[];for(const [role,pref]of Object.entries(q.prefs||{})){if(pref.mode==='item')locks.push(role==='shirt'?'shirt-'+pref.id:role==='bottoms'?'pants-'+pref.id:pref.id);}let noTie=0,so=0,full=new Set(),clothing=new Set();for(const opt of o.options){for(const [role,obj]of Object.entries(opt.items)){if(obj?.id)counts[obj.id]=(counts[obj.id]||0)+1;}const s=opt._hewrsConnected.canonical_selection,cl=[s.suitId||s.blazerId||'SHIRT_ONLY',s.pantId||'SUIT_TROUSERS',s.shirtId,s.state].join('/');clothing.add(cl);full.add(cl+'/'+s.shoeId+'/'+s.watchId);noTie+=Number(s.state==='NO_TIE');so+=Number(s.shirtOnly===true);assert.equal(c.controller.verifyCachedOption(opt,q,c.catalogue),true);}
 for(const [id,n]of Object.entries(counts))if(!locks.includes(id))assert.ok(n<=2,id+' occurs '+n);if(q.prefs.tie.mode!=='none')assert.ok(noTie<=2);if(q.prefs.topwear.id!=='ui:shirt-only')assert.ok(so<=2);assert.ok(o.options.length<=15);assert.equal(full.size,o.options.length);assert.equal(clothing.size,o.options.length);assert.equal(c.controller.verifyOptionSet(o.options,q),true);return {counts,noTie,shirtOnly:so,locked:locks};}
function run(name,ch={},more={},history=[]){const q=request(ch,more),start=Date.now(),o=c.controller.generate(q,c.catalogue,history),counter=independentlyCheck(o,q);cases.push({name,query:q,milliseconds:Date.now()-start,count:o.options.length,reason:o.reason,status:o.status,policy:o.option_policy,independent:counter,options:o.options.map(x=>({selection:x._hewrsConnected.canonical_selection,score:x._hewrsConnected.compatibility.score,display_score:x._hewrsConnected.compatibility.display_score,source_status:x._hewrsConnected.compatibility.status}))});return {q,o,counter};}
let automatic;
test('Unlocked Engine yields 15 unique clothing configurations; every physical item <=2 and No Tie <=2',()=>{automatic=run('unlocked');assert.equal(automatic.o.options.length,15);assert.ok(Object.values(automatic.counter.counts).every(n=>n<=2));return automatic.counter;});
test('One anchored suit may repeat 15 times; shirt/tie/shoes/watch remain capped',()=>{const r=run('anchor_suit',{topwear:suit('S05')});assert.equal(r.o.options.length,15);assert.ok(r.o.options.every(x=>x._hewrsConnected.canonical_selection.suitId==='S05'));});
test('One anchored shirt may repeat while all other physical items remain capped',()=>{const r=run('anchor_shirt',{shirt:item('DS023')});assert.equal(r.o.options.length,15);assert.ok(r.o.options.every(x=>x.items.shirt.id==='shirt-DS023'));});
test('Anchored tie may repeat without exempting shoes or watch',()=>{const r=run('anchor_tie',{tie:item('T017')});assert.equal(r.o.options.length,15);assert.ok(r.o.options.every(x=>x.items.tie.id==='T017'));});
test('Anchored shoe/watch are the only accessory cap exceptions',()=>{const r=run('anchor_accessories',{shoes:item('shoe-8'),watch:item('watch-P05')});assert.equal(r.o.options.length,15);assert.equal(r.counter.counts['shoe-8'],15);assert.equal(r.counter.counts['watch-P05'],15);});
test('Anchored trousers preserve exact physical ID and choose blazer configurations only',()=>{const r=run('anchor_trousers',{bottoms:item('PG002')});assert.equal(r.o.options.length,15);assert.ok(r.o.options.every(x=>x._hewrsConnected.canonical_selection.pantId==='PG002'&&x._hewrsConnected.canonical_selection.blazerId));});
test('Explicit No Tie permits >2; that does not exempt any unlocked physical item',()=>{const r=run('explicit_no_tie',{tie:{mode:'none'},watch:{mode:'none'}});assert.equal(r.o.options.length,15);assert.equal(r.counter.noTie,15);assert.ok(r.o.options.every(x=>x.items.watch===null));});
test('Allow-open-collar formality does not silently lift the two-No-Tie list cap',()=>{const r=run('open_collar_allowed',{}, {formality:'open_collar_allowed'});assert.ok(r.counter.noTie<=2);assert.equal(r.o.options.length,15);});
test('Explicit tie-required context excludes every No Tie option',()=>{const r=run('tie_required',{}, {formality:'tie_required'});assert.equal(r.o.options.length,15);assert.equal(r.counter.noTie,0);});
test('Each supported colour-family lock uses current canonical tie family; no cap exemption for family selections',()=>{let out=[];for(const family of ['navy','burgundy','grey','blue','pink','brown','gold']){const r=run('tie_family_'+family,{tie:{mode:'family',id:family},watch:{mode:'none'}});assert.ok(r.o.options.every(x=>x.items.tie?.colorFamily===family));assert.ok(!r.counter.locked.some(x=>/^T\d/.test(x)));out.push({family,count:r.o.options.length});}return out;});
test('Blazer and legacy cohort routes retain all 18 and only 18 supported non-suit shirts',()=>{const r=run('blazer_B03',{topwear:blazer('B03')});assert.equal(r.o.options.length,15);assert.ok(r.o.options.every(x=>c.nonSuitSources.connectedIds.includes(x._hewrsConnected.canonical_selection.shirtId)));assert.equal(c.nonSuitSources.connectedIds.length,18);});
test('Deferred non-suit shirt remains eligible only in suit mode',()=>{const r=run('suit_only_DS035',{shirt:item('DS035')});assert.equal(r.o.options.length,15);assert.ok(r.o.options.every(x=>x.items.topwear.formal));});
test('Exact outfit returns one configuration, not padded accessory variants',()=>{const r=run('exact',{topwear:suit('S05'),shirt:item('DS029'),tie:item('T028'),shoes:item('shoe-8'),watch:{mode:'none'}});assert.equal(r.o.options.length,1);assert.match(r.o.reason,/Found 1/);});
test('Source hold does not get an invented score to reach 15',()=>{const r=run('source_hold',{shirt:item('DS011')});assert.equal(r.o.options.length,0);assert.ok(r.o.diagnostics.score_statuses.canonical_data_hold>0);});
test('Unbound physical trousers remain unscored, even with the new cap rule',()=>{const r=run('unbound_pants',{bottoms:item(c.trouserProfiles.unboundIds[0])});assert.equal(r.o.options.length,0);});
test('CLASSIC, HYBRID and MODERN filters preserve the existing style classifier',()=>{for(const style of ['CLASSIC','HYBRID','MODERN']){const r=run('style_'+style,{}, {style});assert.ok(r.o.options.every(x=>x._hewrsConnected.compatibility.style.classification===style));}});
test('Current weather changes eligibility but not frozen compatibility mathematics',()=>{const before=JSON.stringify(c.engine.evaluate({topwearId:'S05',shirtId:'DS029',tieId:'T028',context:{occasion:'clinic',requiredFormality:'any'},versionPolicy:'strict'}));run('heavy_rain',{}, {environment:{...env,precipitation:'heavyRain'}});run('cold_snow',{}, {environment:{...env,season:'Winter',temperatureBand:'veryCold',precipitation:'snowIce'}});assert.equal(JSON.stringify(c.engine.evaluate({topwearId:'S05',shirtId:'DS029',tieId:'T028',context:{occasion:'clinic',requiredFormality:'any'},versionPolicy:'strict'})),before);});
test('None of generation/list policy mutates saved wear, Favorites, raw source or catalogue',()=>{const a=JSON.stringify(g.HEWRS_INPUTS),cat=JSON.stringify(c.catalogue),calls=[];const st=g.HEWRSLocalState.create(c,g.HEWRS_INPUT_SHA256,{getItem:()=>null,setItem:(...x)=>calls.push(x)});c.controller.generate(automatic.q,c.catalogue,st.snapshot().events);assert.equal(calls.length,0);assert.equal(JSON.stringify(g.HEWRS_INPUTS),a);assert.equal(JSON.stringify(c.catalogue),cat);});
test('Confirmed-history rotation remains within the existing near-equivalent band',()=>{const s=automatic.o.options[0]._hewrsConnected.canonical_selection,event=c.createHistoryEvent(s,{id:'wear_policy_audit',localDate:'2026-09-26',origin:'manual'});const r=run('confirmed_history',{}, {},[event]);assert.ok(r.o.rotation);assert.equal(g.HEWRS_INPUTS.logicData.rotationPolicy.nearEquivalentBand,.2);assert.deepEqual(plain(event.canonical_selection),plain(s));});
test('Tampered three-time repeated physical item and duplicate full outfit lists are rejected',()=>{const o=automatic.o.options.map(x=>structuredClone(x));o[1].items.watch=o[0].items.watch;o[2].items.watch=o[0].items.watch;assert.equal(c.controller.verifyOptionSet(o,automatic.q),false);assert.equal(c.controller.verifyOptionSet([automatic.o.options[0],automatic.o.options[0]],automatic.q),false);});
test('No-jacket and No Tie have independent two-option guards in list policy',()=>{const q={prefs:p({})},s=g.HEWRSOptionSetPolicy.create(q);for(let i=0;i<2;i++)s.add({items:{topwear:null,shirt:{id:'shirt-test'+i},pants:{id:'pants-test'+i},shoes:{id:'shoe-test'+i},tie:{id:'tie-test'+i},watch:null}});assert.equal(s.issue({items:{topwear:null,shirt:{id:'third'},pants:{id:'thirdpants'},shoes:{id:'thirdshoe'},tie:{id:'thirdtie'},watch:null}}),'SHIRT_ONLY_OPTION_CAP');assert.equal(s.snapshot().no_tie_options,0);const explicit=g.HEWRSOptionSetPolicy.create({prefs:p({topwear:item('ui:shirt-only')})});for(let i=0;i<3;i++)explicit.add({items:{topwear:null,shirt:{id:'shirt-test'+i},pants:{id:'pants-test'+i},shoes:{id:'shoe-test'+i},tie:{id:'tie-test'+i},watch:null}});assert.equal(explicit.snapshot().shirt_only_options,3);});
test('Shirt-only stays exact manual Anchor; no absent ranking was fabricated',()=>{const ui=g.HEWRSFaceliftModel.create(c),s={shirtOnly:true,pantId:'PG002',shirtId:'DS023',state:'T017',shoeId:'shoe-8',watchId:null};ui.fromSelection(s);assert.equal(ui.operation('anchor',{localDate:day}).kind,'manual');assert.equal(c.scoreSelection(s).score,null);assert.throws(()=>ui.operation('engine',{localDate:day}),/manual|Shirt-only/);});
test('Equal source-image hashes never merge DS001/DS014 or DS024/DS025 physical limits',()=>{const s=g.HEWRSOptionSetPolicy.create({prefs:p({shirt:item('DS001')})});assert.ok(s.snapshot().exact_anchor_exemptions.includes('shirt-DS001'));assert.ok(!s.snapshot().exact_anchor_exemptions.includes('shirt-DS014'));});
test('Legacy non-automatic generator path also respects returned-list caps',()=>{const q=c.makeRequest({suitId:'S05',shirt:'ANY',tie:'ANY',shoeId:'shoe-8',localDate:day}),r=c.controller.generate(q,c.catalogue,[]),count={};for(const o of r.options)for(const v of Object.values(o.items))if(v?.id)count[v.id]=(count[v.id]||0)+1;for(const [id,n]of Object.entries(count))if(!['suit-4','shoe-8'].includes(id))assert.ok(n<=2);assert.ok(r.options.filter(x=>!x.items.tie).length<=2);return {count:r.options.length};});
test('No user override can change core score or sneak arbitrary limit fields into a request',()=>{const q=structuredClone(automatic.q);q.maxUsesPerItem=99;assert.throws(()=>c.controller.generate(q,c.catalogue,[]),/Malformed|changed/);});
(async()=>{try{const r=await c.controller.generateAsync(automatic.q,c.catalogue,[],{isCancelled:()=>true});checks.push({name:'Async cancellation returns no partial unvalidated options',passed:r.status==='cancelled'&&r.options.length===0});}catch(e){checks.push({name:'Async cancellation',passed:false,error:e.stack});}fs.writeFileSync(E+'/PASS3_OPTIONS_POLICY.json',JSON.stringify({audit_pass:3,passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks,cases},null,2));if(checks.some(x=>!x.passed))process.exitCode=1;})();
