'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),crypto=require('crypto');
const R=path.resolve(__dirname,'..'),BASE=process.env.HEWRS_BASELINE_V1174||path.resolve(R,'../baseline'),load=require('./core-loader.cjs');
const g=load(R),old=load(BASE),c=g.HEWRSCleanConnection.create(g.HEWRS_INPUTS),b=old.HEWRSCleanConnection.create(old.HEWRS_INPUTS),checks=[],cases=[],profiles=c.preference.profiles(),E=R+'/evidence/recalibration_v1_18_0';
const plain=x=>JSON.parse(JSON.stringify(x)),eq=(a,b)=>assert.deepEqual(plain(a),plain(b)),day='2026-09-28',p=(change={})=>({...Object.fromEntries(['topwear','shirt','tie','shoes','bottoms','watch'].map(k=>[k,{mode:'any'}])),watch:{mode:'none'},...change});
const req=(cc,ch={},more={})=>cc.makeRequest({automatic:true,preferences:p(ch),localDate:day,style:'AUTO',occasion:'clinic',formality:'any',environment:{source:'not_assessed',date:day},...more});
function save(){fs.mkdirSync(E,{recursive:true});fs.writeFileSync(E+'/PASS2_FUNCTIONAL.json',JSON.stringify({passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks,cases},null,2));}
function test(name,f){try{const result=f();checks.push({name,passed:true,result:result??null});console.log('PASS',name);}catch(e){checks.push({name,passed:false,error:e.stack});console.log('FAIL',name,e.stack);}save();}
const before={inputs:JSON.stringify(g.HEWRS_INPUTS),cat:JSON.stringify(c.catalogue),features:JSON.stringify([...c.features]),wear:JSON.stringify(g.HEWRS_INPUTS.logicData.rotationPolicy)};
function independent(out,q,cc=c){const used={},locked=new Set();for(const [k,v]of Object.entries(q.prefs))if(v.mode==='item')locked.add(k==='shirt'?'shirt-'+v.id:k==='bottoms'?'pants-'+v.id:v.id);let nt=0;const clothing=new Set(),full=new Set();
 for(const o of out.options){const a=o._hewrsConnected,s=a.canonical_selection;for(const it of Object.values(o.items))if(it)used[it.id]=(used[it.id]||0)+1;nt+=s.state==='NO_TIE';clothing.add([s.suitId||s.blazerId,s.pantId||'',s.shirtId,s.state].join('/'));full.add(JSON.stringify(s));assert.ok(cc.controller.verifyCachedOption(o,q,cc.catalogue));if(cc===c){assert.equal(a.preference.revision,c.preference.revision);assert.ok(Number.isFinite(a.preference.score));assert.equal(a.preference.measurement,false);eq(a.compatibility,c.engine.evaluate({topwearId:s.suitId||s.blazerId,shirtId:s.shirtId,tieId:s.state==='NO_TIE'?null:s.state,...(s.pantId?{pantProfileId:c.trouserProfiles.binding(s.pantId).profileId}:{}),context:q.context,versionPolicy:'strict',accessories:{shoeStyle:o.items.shoes.subcategory==='Sneakers'?'sneaker':'other',statementWatch:o.items.watch?['statement','diamondStatement'].includes(g.watchFormalityCategory(o.items.watch)):false,controlled:true,evidence:{source_id:'RECOVERED_ACCESSORY_POLICY_CURRENT_CANONICAL_FEATURE_ADAPTER',shoe_id:s.shoeId,watch_id:s.watchId,evidence_status:'inherited_rule_inference_not_owner_measurement'}}}));}}
 for(const[id,n]of Object.entries(used))if(!locked.has(id))assert.ok(n<=2,id+' repeats '+n);if(q.prefs.tie.mode!=='none')assert.ok(nt<=2);assert.equal(clothing.size,out.options.length);assert.equal(full.size,out.options.length);assert.ok(out.options.length<=15);return {used,noTie:nt,shirts:new Set(out.options.map(o=>o.items.shirt.id)).size};}
function run(name,change={},more={},history=[]){const q=req(c,change,more),start=Date.now(),o=c.controller.generate(q,c.catalogue,history),counters=independent(o,q);cases.push({name,query:q,count:o.options.length,milliseconds:Date.now()-start,counters,options:o.options.map(x=>({selection:x._hewrsConnected.canonical_selection,preference:x._hewrsConnected.preference,legacy:x._hewrsConnected.compatibility.display_score,curation:x._hewrsConnected.curation})),reason:o.reason});return {q,o,counters};}
test('136 exact source profiles plus 24 independent physical trouser interpretations',()=>{assert.equal(profiles.length,160);assert.equal(new Set(profiles.map(x=>x.id)).size,160);for(const[id,row]of c.features){const pr=c.preference.profile(id);assert.equal(pr.id,id);assert.equal(pr.primary.wording,row.primary_text);assert.equal(pr.pattern.wording,row.pattern_text);assert.equal(pr.primary.measurement,false);}return profiles.length;});
test('Beige, mushroom, taupe, chestnut, chocolate and espresso remain distinct interpretations',()=>{const P=id=>c.preference.profile(id);assert.equal(P('S03').primary.shade,'greige');assert.ok(P('S03').primary.value>P('S01').primary.value);assert.equal(new Set(['DS019','DS036','DS037','DS038'].map(id=>P(id).primary.value)).size,4);assert.equal(P('DS035').primary.shade,'ivory');assert.equal(P('DS017').primary.shade,'cream');});
test('All four lavender shirts and mauve preserve depth and pattern distinctions',()=>{const P=id=>c.preference.profile(id);for(const id of ['DS021','DS022','DS031','DS047'])assert.equal(P(id).primary.family,'lavender');assert.ok(P('DS022').primary.value<P('DS021').primary.value);assert.ok(P('DS022').primary.value<P('DS047').primary.value);assert.equal(P('DS031').pattern.compound,true);assert.equal(P('DS031').pattern.quiet,false);assert.equal(P('DS018').primary.shade,'mauve');});
test('Subtle checks, dominant patterns, and source qualifier matching remain distinct',()=>{const P=id=>c.preference.profile(id);assert.equal(P('DS005').pattern.family,'grid');assert.equal(P('DS005').pattern.quiet,true);assert.ok(P('DS031').pattern.contrast>P('DS005').pattern.contrast);assert.equal(g.HEWRSOutfitPreference.colour('Black tonal lattice').shade,'black');assert.ok(g.HEWRSOutfitPreference.colour('Ice blue').value>4);assert.equal(g.HEWRSOutfitPreference.colour('Medium-dark chocolate brown').value,1.95);});
test('New family filters and generator use one profile interpretation',()=>{const ui=g.HEWRSFaceliftModel.create(c);ui.fromSelection({suitId:'S10',shirtId:'DS035',state:'T028',shoeId:'shoe-8',watchId:null});for(const cat of ['shirt','tie'])for(const fam of ui.families[cat]){const out=ui.filter(cat,{color:fam});for(const it of out)assert.ok(c.preference.matchesFamily(it.sourceId||it.id,fam),cat+':'+fam);}});
let s10,auto;
test('S10 considers all 1,921 source-eligible candidates, not only the old Top15',()=>{s10=run('S10',{topwear:{mode:'item',id:c.aliases.get('S10')}});assert.equal(s10.o.options.length,15);assert.equal(s10.o.diagnostics.preference_evaluated,s10.o.diagnostics.numeric_candidates);assert.equal(s10.o.diagnostics.numeric_candidates,1921);return s10.counters;});
test('S10 outcome has greater shirt-depth and palette range, including previously omitted colours',()=>{const out=s10.o.options.map(o=>c.preference.profile(o._hewrsConnected.canonical_selection.shirtId));const families=new Set(out.map(p=>p.primary.family));for(const fam of ['cream','brown','lavender','blue'])assert.ok(families.has(fam),fam);assert.ok(out.filter(p=>p.primary.value<2.3).length<out.length/2);assert.ok(new Set(out.map(p=>p.id)).size>=10);return {families:[...families],darkShirts:out.filter(p=>p.primary.value<2.3).length,uniqueShirts:new Set(out.map(p=>p.id)).size};});
test('Free Engine returns 15 with all exact physical caps, including shoes/watches',()=>{auto=run('unlocked',{watch:{mode:'any'}});assert.equal(auto.o.options.length,15);return auto.counters;});
test('Exact item anchors exempt only their selected physical IDs',()=>{for(const[ch,name]of [[{shirt:{mode:'item',id:'DS023'}},'shirt'],[{tie:{mode:'item',id:'T017'}},'tie'],[{shoes:{mode:'item',id:'shoe-8'},watch:{mode:'item',id:'watch-P05'}},'accessories'],[{bottoms:{mode:'item',id:'PG002'}},'trousers']]){const r=run(name,ch);assert.equal(r.o.options.length,15);} });
test('Explicit No Tie produces 15; tie-required never contains No Tie',()=>{const a=run('no_tie',{tie:{mode:'none'}}),b=run('tie_required',{}, {formality:'tie_required'});assert.equal(a.o.options.length,15);assert.equal(a.counters.noTie,15);assert.equal(b.counters.noTie,0);});
test('No score is fabricated for held sources or unbound trouser profiles',()=>{assert.equal(run('held_DS011',{shirt:{mode:'item',id:'DS011'}}).o.options.length,0);assert.equal(run('unbound_trousers',{bottoms:{mode:'item',id:c.trouserProfiles.unboundIds[0]}}).o.options.length,0);});
test('Same clothing cannot pad a list through accessory variations',()=>{assert.equal(run('exact_clothing',{topwear:{mode:'item',id:c.aliases.get('S10')},shirt:{mode:'item',id:'DS035'},tie:{mode:'item',id:'T028'}}).o.options.length,1);});
test('Personal curation stays within the declared preference band and does not change scores',()=>{for(const o of s10.o.options.slice(1)){const a=o._hewrsConnected;assert.ok(a.curation.best_available_preference-a.preference.score<=.200001);assert.ok(a.curation.redundancy<=.180001);}});
test('Historical preference/calibration cannot masquerade as original compatibility',()=>{const o=plain(s10.o.options[0]);assert.notEqual(o._hewrsConnected.preference.score,o._hewrsConnected.compatibility.display_score);o._hewrsConnected.preference.score+=.1;assert.equal(c.controller.verifyCachedOption(o,s10.q,c.catalogue),false);});
test('Confirmed history affects only near-equivalent personalized rotation; original policy unchanged',()=>{const selected=auto.o.options.find(o=>o._hewrsConnected.is_recommendation)||auto.o.options[0],event=c.createHistoryEvent(selected._hewrsConnected.canonical_selection,{id:'test_personal_wear',localDate:'2026-09-27',origin:'manual'});const r=run('valid_history',{watch:{mode:'any'}},{},[event]);assert.equal(r.o.rotation.ranking_basis,c.preference.revision);eq(g.HEWRS_INPUTS.logicData.rotationPolicy,old.HEWRS_INPUTS.logicData.rotationPolicy);assert.equal(g.HEWRS_INPUTS.logicData.rotationPolicy.nearEquivalentBand,.2);});
test('Weather and exact style restrictions remain active independent of personal preference',()=>{for(const style of ['CLASSIC','HYBRID','MODERN']){const r=run(style,{}, {style});assert.ok(r.o.options.every(o=>o._hewrsConnected.compatibility.style.classification===style));}run('snow',{}, {environment:{source:'manual',date:day,temperatureBand:'veryCold',precipitation:'snowIce',season:'Winter',locationLabel:'synthetic'}});});
test('Palette family requests do not get cap exemptions; no forced colour slots',()=>{for(const fam of ['cream','beige','taupe','brown','lavender']){const r=run('shirt_family_'+fam,{shirt:{mode:'family',id:fam}});assert.ok(r.o.options.every(o=>c.preference.matchesFamily(o._hewrsConnected.canonical_selection.shirtId,fam)));assert.ok(!r.o.option_policy?.exact_anchor_exemptions.some(x=>x.startsWith('shirt-')));} });
test('Corrupt saved history is blocked before generation read and raw data retained',()=>{const mem=new Map([[g.HEWRSLocalState.KEY,'{broken']]),be={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v)},st=g.HEWRSLocalState.create(c,g.HEWRS_INPUT_SHA256,be);assert.throws(()=>st.readForGeneration(),/unavailable/);assert.equal(mem.get(st.key),'{broken');assert.equal(st.exportText(),'{broken');});
test('Other-tab valid history is synchronized on read, but mid-generation changes cancel',()=>{const mem=new Map(),be={getItem:k=>mem.get(k)??null,setItem:(k,v)=>mem.set(k,v)},st=g.HEWRSLocalState.create(c,g.HEWRS_INPUT_SHA256,be),other=g.HEWRSLocalState.create(c,g.HEWRS_INPUT_SHA256,be);const read=st.readForGeneration();const event=c.createHistoryEvent(s10.o.options[0]._hewrsConnected.canonical_selection,{id:'test_cross_tab',localDate:'2026-09-27',origin:'manual'});other.addEvent(event);assert.throws(()=>st.assertCurrent(read.token),/changed/);const now=st.readForGeneration();assert.equal(now.events.length,1);st.assertCurrent(now.token);assert.equal(st.snapshot().events[0].id,'test_cross_tab');});
test('Unavailable storage does not falsely certify a history read',()=>{const be={getItem(){throw Error('denied');},setItem(){throw Error('denied');}},st=g.HEWRSLocalState.create(c,g.HEWRS_INPUT_SHA256,be);assert.throws(()=>st.readForGeneration(),/unavailable/);});
test('Explicit session-memory operation has a valid revision guard, without false persistent claim',()=>{const st=g.HEWRSLocalState.create(c,g.HEWRS_INPUT_SHA256,null),read=st.readForGeneration();assert.equal(st.status().persistent,false);assert.equal(st.assertCurrent(read.token),true);st.addEvent(c.createHistoryEvent(s10.o.options[0]._hewrsConnected.canonical_selection,{id:'test_memory_wear',localDate:'2026-09-27',origin:'manual'}));assert.throws(()=>st.assertCurrent(read.token),/changed/);});
test('All 50 shirts, 18 non-suit IDs, DS041 restriction and every source object preserved',()=>{eq(c.nonSuitSources.connectedIds,b.nonSuitSources.connectedIds);assert.equal(c.nonSuitSources.connectedIds.length,18);assert.equal(c.manifest.shirt_order.length,50);assert.equal(JSON.stringify(g.HEWRS_INPUTS),before.inputs);assert.equal(JSON.stringify(c.catalogue),before.cat);assert.equal(JSON.stringify([...c.features]),before.features);eq(c.catalogue,b.catalogue);assert.equal(JSON.stringify(g.HEWRS_INPUTS.logicData.rotationPolicy),before.wear);});
(async()=>{try{const r=await c.controller.generateAsync(auto.q,c.catalogue,[],{isCancelled:()=>true});assert.equal(r.status,'cancelled');checks.push({name:'Asynchronous cancellation returns no partial candidates',passed:true});}catch(e){checks.push({name:'Asynchronous cancellation',passed:false,error:e.stack});}save();fs.writeFileSync(E+'/SOURCE_PREFERENCE_PROFILES.json',JSON.stringify(profiles,null,2));if(checks.some(x=>!x.passed))process.exitCode=1;})();
