'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const R=path.resolve(__dirname,'..'),E=R+'/evidence/profiles_v1_8',results=[];
const raw=fs.readFileSync(R+'/evidence/profiles_v1_8/source/HEWRS_Trouser_Profile_Bindings.json'),HASH='538cdf147e1af4c83c88a5b7bfbc6cf9bc5128b6461200be3ea01588348cb960';
const scripts=JSON.parse(fs.readFileSync(R+'/tools/build.py','utf8').match(/SCRIPTS=(\[[^\n]+\])/)[1].replaceAll("'",'"')).filter(f=>f!=='src/application.js');
function load(old=false){const cx=vm.createContext({console,structuredClone,Date,Math,JSON,setTimeout,clearTimeout,Uint8ClampedArray});const replacements={'src/controller.js':'vendor/profiles-v1_8/controller_v17.js','src/connection.js':'vendor/profiles-v1_8/connection_v17.js','src/blazer-connection.js':'vendor/profiles-v1_8/blazer_connection_v17.js'};for(const s of scripts){const f=old?(replacements[s]||s):s;vm.runInContext(fs.readFileSync(R+'/'+f,'utf8'),cx,{filename:f});}return cx;}
const cx=load(),oldcx=load(true),before=JSON.stringify(cx.HEWRS_INPUTS),c=cx.HEWRSCleanConnection.create(cx.HEWRS_INPUTS),old=oldcx.HEWRSCleanConnection.create(oldcx.HEWRS_INPUTS),ref=oldcx.HEWRSSuitConnectionV16.create(oldcx.HEWRS_INPUTS);
const equal=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b));
function check(name,fn){try{const detail=fn();results.push({name,pass:true,...(detail===undefined?{}:{detail})});}catch(e){results.push({name,pass:false,error:e.stack});}}
const cfg={blazerId:'B03',pantId:'PG002',shirt:'DS001',tie:'T017',shoeId:'shoe-8',watchId:null,localDate:'2026-09-23',occasion:'clinic',style:'AUTO'};
const sel={blazerId:'B03',pantId:'PG002',shirtId:'DS001',state:'T017',shoeId:'shoe-8',watchId:null};
check('Recovered 15859-byte source matches its original recorded SHA256',()=>{assert.equal(raw.length,15859);assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),HASH);});
check('24 source rows including original prose and states are identical to the exact source',()=>equal(c.trouserProfiles.report,JSON.parse(raw)));
check('15 existing local bindings and nine nulls retained',()=>{assert.equal(c.trouserProfiles.boundIds.length,15);assert.equal(c.trouserProfiles.unboundIds.length,9);for(const id of c.trouserProfiles.unboundIds){assert.equal(c.trouserProfiles.record(id).profile_id,null);assert.equal(c.trouserProfiles.binding(id),null);}});
check('No production approval or new frozen profile judgments added',()=>{assert.equal(c.trouserProfiles.report.production_approval,false);assert.equal(c.trouserProfiles.report.records.filter(r=>r.state==='LOCAL_COLOR_BINDING_NEW').length,4);});
check('All source physical IDs/history IDs and asset hashes match current representations',()=>{for(const row of c.trouserProfiles.report.records){const p=c.blazerConnection.knownPant(row.physical_id);assert.equal(p.historyId,row.app_id);assert.equal(p.layer.sha256,row.asset_sha256);}});
check('Raw V1.7 crosswalk retained separately without overwriting proposals',()=>equal(c.blazerConnection.data.profiles,old.blazerConnection.data.profiles));
check('PN002 uses its existing P07 textual binding, not the shared tan image as evidence',()=>{assert.equal(c.trouserProfiles.binding('PN002').profileId,'P07');assert.equal(c.trouserProfiles.binding('PN001'),null);assert.equal(c.blazerConnection.knownPant('PN002').layer.sha256,c.blazerConnection.knownPant('PN001').layer.sha256);});
check('Brown shade proposals remain null rather than being promoted to P03',()=>{for(const id of ['PBR001','PBR002']){assert.equal(c.trouserProfiles.record(id).candidate_profile_for_review,'P03');assert.equal(c.trouserProfiles.binding(id),null);}});
for(const key of ['asset_sha256','profile_id','app_id','state'])check('Registry rejects tampered source field '+key,()=>{const s=structuredClone(c.trouserProfiles.report);if(key==='asset_sha256')s.records[0][key]='0'.repeat(64);if(key==='profile_id')s.records[0][key]='P07';if(key==='app_id')s.records[0][key]='pants-PT002';if(key==='state')s.records[0][key]='PROPOSAL';assert.throws(()=>cx.HEWRSTrouserProfiles.create(c.blazerConnection.data,cx.HEWRS_INPUTS,s));});
let exact=0,exactOptions=0,hash=crypto.createHash('sha256');
check('705 exact B03/DS001/physical-trouser/tie requests match original controller calculations',()=>{
 for(const pantId of c.trouserProfiles.boundIds)for(const tie of c.blazerConnection.data.available_states){const q=c.makeRequest({...cfg,pantId,tie}),a=c.controller.generate(q,c.catalogue,[]),b=ref.controller.generate(q,c.catalogue,[]);equal(a,b);assert.equal(a.diagnostics.mapping_holds.length,0);assert.equal(q.pants.id,'pants-'+pantId);for(const o of a.options){const s=c.selectionFromOption(o,q).selection;assert.equal(s.pantId,pantId);assert.equal(s.state,tie);assert.equal(c.historyIds(s).pants,'pants-'+pantId);exactOptions++;}hash.update(JSON.stringify(a));exact++;}assert.equal(exact,705);return {requests:exact,returnedOptions:exactOptions,result_sha256:hash.digest('hex')};
});
let pooled=0;
check('Free-tie generation evaluates only the 47 existing tied configurations before ranking',()=>{for(const pantId of c.trouserProfiles.boundIds){const q=c.makeRequest({...cfg,pantId,tie:'ANY'});q.limit=100;const r=c.controller.generate(q,c.catalogue,[]);assert.equal(r.diagnostics.examined,47);assert.equal(r.diagnostics.configuration_counts.independent_no_tie,0);assert.equal(r.diagnostics.unavailable_configurations.length,1);for(const o of r.options){const b=c.selectionFromOption(o,q);assert.ok(b.selection.state.startsWith('T'));assert.equal(b.selection.pantId,pantId);}assert.ok(r.options.length);pooled++;}return {queries:pooled};});
check('Tie-family request retains exact pants and returns only the selected family',()=>{for(const family of ['navy','grey','burgundy']){const q=c.makeRequest({...cfg,tie:'FAMILY:'+family});const r=c.controller.generate(q,c.catalogue,[]);for(const o of r.options){assert.equal(o.items.tie.colorFamily,family);c.selectionFromOption(o,q);}}});
check('Classic/Hybrid/Modern requests preserve inherited style gate',()=>{for(const style of ['CLASSIC','HYBRID','MODERN']){const q=c.makeRequest({...cfg,style,tie:'ANY'}),r=c.controller.generate(q,c.catalogue,[]);for(const o of r.options)assert.equal(o._hewrsConnected.compatibility.style.classification,style);}});
check('Nine unknown bindings remain mapping_required and retain manual display and physical wear identities',()=>{for(const pantId of c.trouserProfiles.unboundIds){const q=c.makeRequest({...cfg,pantId}),r=c.controller.generate(q,c.catalogue,[]);assert.equal(q.pantBindings.length,0);assert.equal(r.status,'mapping_required');assert.equal(r.options.length,0);c.validateSelection({...sel,pantId});assert.equal(c.scoreSelection({...sel,pantId},q.context).score,null);assert.equal(c.historyIds({...sel,pantId}).pants,'pants-'+pantId);}});
const good=c.makeRequest(cfg),option=c.controller.generate(good,c.catalogue,[]).options[0];
const bads={wrong_profile:q=>q.pantBindings[0].profileId='P07',wrong_physical:q=>q.pantBindings[0].physicalId='pants-PT001',wrong_source:q=>q.pantBindings[0].evidence.source_id='fabricated',wrong_source_hash:q=>q.pantBindings[0].evidence.source_sha256='0'.repeat(64),missing_binding:q=>q.pantBindings=[],duplicate_binding:q=>q.pantBindings.push(structuredClone(q.pantBindings[0])),no_tie:q=>q.tie={mode:'none'},wrong_shirt:q=>q.shirt={mode:'item',id:'shirt-DS035'},unknown_promotion:q=>{q.pants.id='pants-PN007';q.pantBindings[0].physicalId='pants-PN007';},production:q=>q.mode='production'};
for(const [name,change]of Object.entries(bads))check('Reject '+name+' without a fallback or stale candidate reuse',()=>{const q=structuredClone(good);change(q);assert.equal(c.controller.generate(q,c.catalogue,[]).status,'request_blocked');assert.equal(c.controller.verifyCachedOption(option,q,c.catalogue),false);assert.throws(()=>c.selectionFromOption(option,q));});
check('Returned bindings are defensive copies; source fields cannot be changed',()=>{const b=c.trouserProfiles.binding('PG002');b.profileId='P07';assert.equal(c.trouserProfiles.binding('PG002').profileId,'P01');assert.ok(Object.isFrozen(c.trouserProfiles.records.PG002));});
check('24 physical identities remain distinct despite shared colors/profiles',()=>{for(const pantId of c.blazerConnection.pantIds){assert.equal(c.makeRequest({...cfg,pantId}).pants.id,'pants-'+pantId);assert.equal(c.historyIds({...sel,pantId}).pants,'pants-'+pantId);}assert.equal(new Set(c.blazerConnection.pantIds).size,24);});
check('All 188 approved shirt-tie records remain unchanged',()=>{for(const r of cx.HEWRS_INPUTS.approved.records)equal(c.source.lookupShirtTie(r.shirt_id,r.tie_id,{versionPolicy:'strict'}),old.source.lookupShirtTie(r.shirt_id,r.tie_id,{versionPolicy:'strict'}));});
check('All 98 frozen blazer-pant values preserved',()=>{equal(cx.HEWRS_INPUTS.logicData.blazerPant,oldcx.HEWRS_INPUTS.logicData.blazerPant);assert.equal(cx.HEWRS_INPUTS.logicData.blazerPant.length,98);});
check('18 representative suit Engine requests remain exactly equal to V1.7',()=>{for(let i=1;i<=18;i++){const cfg2={suitId:'S'+String(i).padStart(2,'0'),shirt:'DS036',tie:'T017',shoeId:'shoe-8',watchId:null,localDate:'2026-09-23'};const qa=c.makeRequest(cfg2),qb=old.makeRequest(cfg2);equal(qa,qb);equal(c.controller.generate(qa,c.catalogue,[]),old.controller.generate(qb,old.catalogue,[]));}});
function backend(){const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),m};}
check('V1.7 mixed suit/blazer backup reopens without any source-lock change or writes',()=>{const db=backend(),s=oldcx.HEWRSLocalState.create(old,oldcx.HEWRS_INPUT_SHA256,db);s.addEvent(old.createHistoryEvent(sel,{id:'manual-old',localDate:'2026-09-22',origin:'manual'}));const txt=s.exportText();const n=cx.HEWRSLocalState.create(c,cx.HEWRS_INPUT_SHA256,db);assert.equal(n.exportText(),txt);equal(n.snapshot(),s.snapshot());});
check('Engine candidate wear event preserves exact physical pants through export/preview/restore',()=>{const db=backend(),s=cx.HEWRSLocalState.create(c,cx.HEWRS_INPUT_SHA256,db),v=c.selectionFromOption(option,good).selection;s.addEvent(c.createHistoryEvent(v,{id:'engine-1',origin:'engine',localDate:'2026-09-23'}));const txt=s.exportText(),before=JSON.stringify(s.snapshot()),preview=s.previewImport(txt);assert.equal(JSON.stringify(s.snapshot()),before);s.restore(preview);assert.equal(s.snapshot().events[0].items.pants.id,'pants-PG002');assert.equal(s.snapshot().events[0].items.topwear.id,'blazer-2');});
check('Source inputs, catalogue, and source lock preserved after calculations',()=>{assert.equal(JSON.stringify(cx.HEWRS_INPUTS),before);equal(c.catalogue,old.catalogue);assert.equal(cx.HEWRS_INPUT_SHA256,oldcx.HEWRS_INPUT_SHA256);});
(async()=>{
 try{const a=await c.controller.generateAsync(good,c.catalogue,[]);equal(a,c.controller.generate(good,c.catalogue,[]));results.push({name:'Asynchronous generation equals synchronous exact result',pass:true});}catch(e){results.push({name:'Asynchronous generation',pass:false,error:e.stack});}
 try{const q=c.makeRequest({...cfg,tie:'ANY'}),r=await c.controller.generateAsync(q,c.catalogue,[],{isCancelled:()=>true});assert.equal(r.status,'cancelled');assert.equal(r.options.length,0);results.push({name:'Cancellation returns no candidate or fabricated wear',pass:true});}catch(e){results.push({name:'Cancellation',pass:false,error:e.stack});}
 const result={passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length,tests:results,exact_queries:exact,pooled_queries:pooled,source_hash:HASH};
 const dest=process.env.HEWRS_TEST_OUTPUT||E+'/FUNCTIONAL.json';fs.writeFileSync(dest,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(result.failed)process.exitCode=1;
})();
