'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const R=path.resolve(__dirname,'..'),E=R+'/evidence/scope18_v1_16_5';fs.mkdirSync(E,{recursive:true});
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),eq=(a,b)=>assert.deepEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)));
function source(n,old=false){const p=R+'/rollback/scope18_v1_16_5/original/'+n;return fs.readFileSync(old&&fs.existsSync(p)?p:R+'/'+n,'utf8');}
function context(old=false){const c=vm.createContext({console,structuredClone,Date,Math,JSON,setTimeout,clearTimeout,Uint8ClampedArray});const names=JSON.parse(source('tools/build.py',old).match(/SCRIPTS=(\[[^\n]+\])/)[1].replaceAll("'",'"'));for(const n of names.filter(n=>n!=='src/application.js'))vm.runInContext(source(n,old),c,{filename:n});return c;}
const g=context(),c=g.HEWRSCleanConnection.create(g.HEWRS_INPUTS),ui=g.HEWRSFaceliftModel.create(c),og=context(true),oc=og.HEWRSCleanConnection.create(og.HEWRS_INPUTS),ou=og.HEWRSFaceliftModel.create(oc);
const scope=JSON.parse(source('RELEASE_SCOPE.json')),old=JSON.parse(source('rollback/scope18_v1_16_5/BASELINE_FILES.json')).files,checks=[];
const ids=scope.enabled_non_suit_shirt_ids,deferred=scope.deferred_non_suit_shirt_ids;
const S=(id='DS023',t='T017',suit='S05')=>({suitId:suit,shirtId:id,state:t,shoeId:'shoe-8',watchId:null}),B=(id='DS023',t='T017',blazer='B03')=>({blazerId:blazer,pantId:'PG002',shirtId:id,state:t,shoeId:'shoe-8',watchId:null}),O=(id='DS023',t='T017')=>({shirtOnly:true,pantId:'PG002',shirtId:id,state:t,shoeId:'shoe-8',watchId:null});
function test(name,fn){try{checks.push({name,passed:true,result:fn()??null});}catch(e){checks.push({name,passed:false,error:e.stack});}}
test('Only the existing 18 IDs are in scope; 32 deferred, none deleted',()=>{assert.equal(ids.length,18);assert.equal(deferred.length,32);assert.equal(new Set([...ids,...deferred]).size,50);eq([...ids].sort(),[...c.nonSuitSources.connectedIds].sort());assert.equal(scope.deferred_shirts_block_this_release,false);eq(scope.inventory_ids_deleted,[]);});
test('Blazer and shirt-only pickers show exactly 18 active choices in inherited order',()=>{for(const s of [B(),O()]){ui.fromSelection(s);ou.fromSelection(s);eq(ui.filter('shirt').map(x=>x.id),ou.filter('shirt').filter(x=>x.available).map(x=>x.id));assert.equal(ui.filter('shirt').length,18);assert.ok(ui.filter('shirt').every(x=>x.available));assert.equal(ui.scope('shirt').deferred_count,32);}});
test('All 50 shirts remain visible for suits and unselected topwear',()=>{ui.fromSelection(S());assert.equal(ui.filter('shirt').length,50);ui.reset();assert.equal(ui.filter('shirt').length,50);assert.equal(ui.scope('shirt').limited,false);});
test('Inventory rows and catalogue records remain exact baseline objects/order',()=>{eq(ui.rows,ou.rows);eq(c.catalogue,oc.catalogue);eq(c.manifest.shirt_order,oc.manifest.shirt_order);eq(c.records,oc.records);});
test('Full 18-suit / Active50 routing remains valid',()=>{let n=0;for(const sid of c.suitSources.ids)for(const id of c.manifest.shirt_order)for(const t of c.manifest.shirts[id].available_modes){if(t==='REFERENCE'&&sid!=='S05')continue;eq(c.validateSelection(S(id,t,sid)),oc.validateSelection(S(id,t,sid)));n++;}assert.equal(n,39817);return n;});
test('All 18 non-suit IDs, 48 states and all 14 blazers retain exact selections',()=>{let n=0;for(const id of ids)for(const t of c.nonSuitSources.registry.shirts[id].states){for(const bid of c.blazerConnection.availableIds){eq(c.validateSelection(B(id,t,bid)),oc.validateSelection(B(id,t,bid)));n++;}eq(c.validateSelection(O(id,t)),oc.validateSelection(O(id,t)));n++;}assert.equal(n,12960);return n;});
test('Deferred non-suit routes stay guarded; suit approval remains independent',()=>{for(const id of deferred){for(const s of [B(id,'NO_TIE'),O(id,'NO_TIE')])assert.throws(()=>c.validateSelection(s));c.validateSelection(S(id,'NO_TIE'));ui.fromSelection(B());ui.begin('shirt');assert.throws(()=>ui.choose({mode:'item',id}));ui.cancel();}});
test('Deferred suit preference survives topwear change and Cancel without substitution',()=>{ui.fromSelection(S('DS036'));ui.set('topwear',{mode:'item',id:ui.rows.topwear.find(x=>x.kind==='blazer'&&x.sourceId==='B03').id});const before=ui.snapshot();assert.equal(before.shirt.id,'DS036');ui.begin('shirt');assert.throws(()=>ui.commit());ui.cancel();eq(ui.snapshot(),before);});
test('Apply changes only the intended shirt; Cancel leaves all preferences intact',()=>{ui.fromSelection(B());const before=ui.snapshot();ui.begin('shirt');ui.choose({mode:'item',id:'DS027'});ui.cancel();eq(ui.snapshot(),before);ui.begin('shirt');ui.choose({mode:'item',id:'DS027'});ui.commit();const after=ui.snapshot();assert.equal(after.shirt.id,'DS027');for(const k in before)if(k!=='shirt')eq(after[k],before[k]);});
test('Search, brand and color filters intersect the scoped list without remapping IDs',()=>{ui.fromSelection(B());assert.equal(ui.filter('shirt',{query:'DS023'}).length,1);assert.equal(ui.filter('shirt',{query:'DS036'}).length,0);for(const row of ui.filter('shirt'))assert.ok(ui.filter('shirt',{brand:row.brand}).some(x=>x.id===row.id));ui.fromSelection(S());assert.equal(ui.filter('shirt',{query:'DS036'}).length,1);});
test('All six categories persist and non-shirt filters remain baseline-equivalent',()=>{eq(ui.categories,['topwear','shirt','tie','shoes','bottoms','watch']);for(const s of [S(),B(),O()]){ui.fromSelection(s);ou.fromSelection(s);for(const cat of ui.categories.filter(x=>x!=='shirt'))eq(ui.filter(cat),ou.filter(cat));}});
test('No Tie, 47 ties and the four No-Tie-only restrictions remain unchanged',()=>{for(const id of ids){ui.fromSelection(O(id));assert.equal(ui.filter('tie').filter(x=>x.available).length,47);}for(const id of ['DS040','DS041','DS042','DS043']){ui.fromSelection(S(id,'NO_TIE'));assert.equal(ui.filter('tie').filter(x=>x.available).length,0);assert.throws(()=>c.validateSelection(S(id,'T017')));}});
test('Blazer Engine scores and source holds equal the untouched baseline',()=>{let n=0;for(const id of ids)for(const t of ['NO_TIE','T017']){eq(c.scoreSelection(B(id,t),{occasion:'clinic',requiredFormality:'any'}),oc.scoreSelection(B(id,t),{occasion:'clinic',requiredFormality:'any'}));n++;}return n;});
test('Blazer Engine queries retain exact shirt/tie choices without fabricated recommendations',()=>{let opts=0;for(const id of ids){const req={blazerId:'B03',pantId:'PG002',shirt:id,tie:'T017',shoeId:'shoe-8',localDate:'2026-09-25'};eq(c.makeRequest(req),oc.makeRequest(req));const q=c.makeRequest(req),out=c.controller.generate(q,c.catalogue,[]);for(const o of out.options){const s=c.selectionFromOption(o,q).selection;assert.equal(s.shirtId,id);assert.equal(s.state,'T017');opts++;}}assert.ok(opts>0);return {requests:18,returned_options:opts};});
test('Shirt-only ranking stays absent; manual Anchor is functional',()=>{for(const id of ids){ui.fromSelection(O(id));eq(ui.operation('anchor',{localDate:'2026-09-25'}).selection,O(id));assert.equal(c.scoreSelection(O(id)).score,null);assert.throws(()=>ui.operation('engine',{localDate:'2026-09-25'}));}});
test('Nine unbound numerical trouser profiles remain null; all physical trouser IDs persist',()=>{eq(c.blazerConnection.pantIds,oc.blazerConnection.pantIds);assert.equal(c.blazerConnection.pantIds.length,24);for(const id of c.trouserProfiles.unboundIds)assert.equal(c.scoreSelection({...B(),pantId:id}).score,null);});
test('All 705 runtime images remain byte-identical with no added artwork',()=>{let n=0;for(const [p,d]of Object.entries(old))if(/^(assets|assemblies)\//.test(p)&&/\.(png|webp|jpe?g)$/.test(p)){assert.equal(sha(fs.readFileSync(R+'/'+p)),d.sha256);n++;}assert.equal(n,705);return n;});
test('All garment data, score code, renderers, geometry, CSS and storage remain untouched',()=>{let n=0;for(const [p,d]of Object.entries(old))if(/^(data|vendor|provenance)\//.test(p)||p==='src/application.css'||(/^src\//.test(p)&&!['src/application.js','src/source-aware-pickers.js'].includes(p))){assert.equal(sha(fs.readFileSync(R+'/'+p)),d.sha256);n++;}return n;});
test('DS023 correction selects the exact same layer references; DS035/DS051 special handling remains',()=>{eq(c.ds023Cleanup,oc.ds023Cleanup);eq(c.ds023Edges,oc.ds023Edges);eq(c.manifest.shirts.DS035,oc.manifest.shirts.DS035);eq(c.manifest.shirts.DS051,oc.manifest.shirts.DS051);});
test('Shared image bytes never merge physical shirt identities',()=>{for(const pair of [['DS001','DS014'],['DS024','DS025'],['DS021','DS047']])assert.notEqual(c.historyIds(O(pair[0])).shirt,c.historyIds(O(pair[1])).shirt);});
test('Synthetic ledger export/import and version rollback preserve every byte and watch ID',()=>{const m=new Map([['sentinel','UNCHANGED']]),be={getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)},s=og.HEWRSLocalState.create(oc,og.HEWRS_INPUT_SHA256,be);const event=oc.createHistoryEvent({...O(),watchId:'watch-P05'},{id:'SYNTHETIC_SCOPE18',localDate:'2026-09-25',origin:'manual'});s.addEvent(event);const raw=s.exportText(),n=g.HEWRSLocalState.create(c,g.HEWRS_INPUT_SHA256,be);assert.equal(n.exportText(),raw);eq(n.previewImport(raw).events,s.snapshot().events);assert.equal(og.HEWRSLocalState.create(oc,og.HEWRS_INPUT_SHA256,be).exportText(),raw);assert.equal(m.get('sentinel'),'UNCHANGED');return 'Synthetic Map only; no owner data or physical browser persistence test';});
test('Existing source lock and storage key remain exact',()=>{assert.equal(g.HEWRS_INPUT_SHA256,og.HEWRS_INPUT_SHA256);const be={getItem:()=>null,setItem:()=>{}};assert.equal(g.HEWRSLocalState.create(c,g.HEWRS_INPUT_SHA256,be).key,og.HEWRSLocalState.create(oc,og.HEWRS_INPUT_SHA256,be).key);});
test('Mobile sheet implementation and CSS remain exact accepted V1.16.4 bytes',()=>{for(const p of ['src/sheet-layout.js','src/application.css'])assert.equal(sha(fs.readFileSync(R+'/'+p)),old[p].sha256);});
test('Owner-reported baseline acceptance is explicit, scoped and not fabricated tool evidence',()=>{assert.equal(scope.owner_reported_acceptance.baseline,'1.16.4');assert.equal(scope.owner_reported_acceptance.iphone_safari_visual_reload_restart_and_unchanged_wear_count.reported,'pass');assert.match(scope.owner_reported_acceptance.scope,/not tool-observed/);});
const result={schema:'hewrs.scope18.functional.v1_16_5',passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length,checks};fs.writeFileSync(E+'/FUNCTIONAL.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(result.failed)process.exitCode=1;
