'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'),load=require('./core-loader.cjs');
const R=path.resolve(__dirname,'..'),B=process.env.HEWRS_BASELINE;assert.ok(B,'Set HEWRS_BASELINE to independently verified V1.19.0');
const root=load(R),c=root.HEWRSCleanConnection.create(root.HEWRS_INPUTS),bg=load(B),b=bg.HEWRSCleanConnection.create(bg.HEWRS_INPUTS),E=R+'/evidence/research_v1_20_0';fs.mkdirSync(E,{recursive:true});
const cp=x=>JSON.parse(JSON.stringify(x)),eq=(a,b)=>assert.deepEqual(cp(a),cp(b)),checks=[],mat=[];
const cfg=(patch={},method='research',extra={})=>({automatic:true,stylistMode:method,preferences:{...Object.fromEntries(['topwear','shirt','tie','shoes','bottoms','watch'].map(k=>[k,{mode:'any'}])),...patch},localDate:'2026-09-28',style:'AUTO',occasion:'clinic',formality:'any',environment:{source:'not_assessed',date:'2026-09-28'},...extra});
function test(name,f){try{const r=f();checks.push({name,passed:true,result:r??null});console.log('PASS',name);}catch(e){checks.push({name,passed:false,error:e.stack});console.log('FAIL',name,e.message);}fs.writeFileSync(E+'/PASS2_RULES_FUNCTIONAL.json',JSON.stringify({checks,passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length},null,2));}
function counters(options,q){const m={},ex=new Set(root.HEWRSOptionSetPolicy.exactLocks(q)),keys=new Set();let nt=0;for(const o of options){for(const a of Object.values(o.items))if(a?.id)m[a.id]=(m[a.id]||0)+1;if(!o.items.tie)nt++;let k=['topwear','shirt','tie','pants'].map(r=>o.items[r]?.id||'-').join('|');assert.ok(!keys.has(k));keys.add(k);}for(let [id,n]of Object.entries(m))assert.ok(ex.has(id)||n<=2,id+': '+n);assert.ok(nt<=2||q.prefs.tie.mode==='none');return {counts:m,no_tie:nt,distinct_topwear:new Set(options.map(o=>o.items.topwear.id)).size,distinct_shirts:new Set(options.map(o=>o.items.shirt.id)).size};}
const cache=new Map();function gen(conn,patch,method,extra={},h=[]){let k=JSON.stringify([conn===c,patch,method,extra,h]);if(cache.has(k))return cache.get(k);const q=conn.makeRequest(cfg(patch,method,extra)),r=conn.controller.generate(q,conn.catalogue,h);assert.ok(conn.controller.verifyOptionSet(r.options,q));const z={q,result:r,counts:counters(r.options,q)};cache.set(k,z);return z;}
const pref=c.hybrid.researchPreference;
test('Preserve inventory, physical IDs, wardrobe source and non-suit scope exactly',()=>{eq(c.records,b.records);eq(c.catalogue,b.catalogue);eq(c.manifest,b.manifest);eq(c.nonSuitSources.connectedIds,b.nonSuitSources.connectedIds);assert.equal(c.nonSuitSources.connectedIds.length,18);eq(root.HEWRS_INPUTS,bg.HEWRS_INPUTS);});
test('Local generator is the new default; curated/visual/old heuristic remain distinct',()=>{assert.equal(c.hybrid.mode(),'research');assert.deepEqual(cp(root.HEWRSHybridStylist.MODES),['research','curated','visual','heuristic']);const q=c.makeRequest({...cfg(),stylistMode:undefined});assert.equal(q.stylist.mode,'research');assert.equal(q.revision,'HEWRS_AUTOMATIC_WORKFLOW_1_20_0');});
test('All160 interpretable wardrobe profiles are covered; no colour is deleted',()=>{assert.equal(pref.profiles().length,160);for(const p of pref.profiles()){assert.equal(p.id,pref.profile(p.id).id);assert.ok(Number.isFinite(p.primary.value)||p.primary.value===null);}for(const id of ['DS017','DS035','DS036','DS037','DS038','DS021','DS022','DS031','DS047','DS005','DS016','DS018'])assert.ok(pref.profile(id));});
test('Sources distinguish warm neutrals, depth qualifiers and compound checks',()=>{assert.equal(pref.profile('S03').primary.shade,'greige');assert.equal(pref.profile('S02').primary.family,'brown');assert.notEqual(pref.profile('DS037').primary.value,pref.profile('DS036').primary.value);assert.equal(pref.profile('DS031').pattern.compound,true);assert.ok(pref.profile('DS005').pattern.quiet);assert.equal(pref.profile('DS015').primary.family,'blue');});
test('Guideline regression: patterned lead with quiet supporting shirt outranks three competing patterns',()=>{const a=pref.clothing('S12','DS035','T022',null,9),z=pref.clothing('S12','DS031','T007',null,9);assert.ok(a.components.pattern_hierarchy>z.components.pattern_hierarchy);return {supporting:a.components.pattern_hierarchy,competing:z.components.pattern_hierarchy};});
test('Guideline regression: tie focal depth is directional, not maximum jacket-shirt contrast',()=>{const a=pref.clothing('S10','DS035','T022',null,9),z=pref.clothing('S10','DS034','T017',null,9);assert.ok(a.components.value_structure>z.components.value_structure);return {light_shirt_dark_tie:a.components.value_structure,reverse:z.components.value_structure};});
test('Footwear tests use trouser depth and context; cognac/suede not banned',()=>{const sh=id=>c.catalogue.shoes.find(x=>x.id===id),q=c.makeRequest(cfg());let d=pref.clothing('S18','DS035','T022',null,9),l=pref.clothing('B10','DS001','NO_TIE','PN002',9);assert.ok(pref.shoe(sh('shoe-3'),d,q).score>pref.shoe(sh('shoe-9'),d,q).score);assert.ok(pref.shoe(sh('shoe-9'),l,q).score>pref.shoe(sh('shoe-9'),d,q).score);assert.ok(pref.shoe(sh('shoe-15'),l,q).score>8);});
test('Rules contain no brand/price bonus and no mandatory shirt-colour quota',()=>{const q=c.makeRequest(cfg()),z=pref.clothing('S10','DS035','T022',null,9),sh=c.catalogue.shoes.find(x=>x.id==='shoe-4');eq(pref.shoe(sh,z,q),pref.shoe({...sh,brand:'CHANGED',name:'Different label',price:999999},z,q));assert.ok(!pref.clothing('S10','DS022','T030',null,9).cautions.some(x=>/lavender/.test(x)));});
test('Preferred-reference influence is property based, bounded and openly counted',()=>{assert.ok(pref.reference_templates>0&&pref.reference_templates<30);const v=pref.clothing('S10','DS035','T022',null,9);assert.equal(v.weights.reference_structure,.10);assert.ok(v.components.reference_structure<=10);assert.equal(Object.values(v.weights).reduce((a,b)=>a+b,0).toFixed(6),'1.000000');return {eligible_property_templates:pref.reference_templates,weight:.10,not_individual_owner_ratings:true};});
test('All18 suits and14 blazers: old curated, old generator, new generator actual counts/locks',()=>{for(const id of [...c.suitSources.ids,...c.blazerConnection.availableIds]){const top=id[0]==='S'?c.aliases.get(id):c.blazerConnection.knownBlazer(id).historyId,patch={topwear:{mode:'item',id:top}};let old=gen(b,patch,'curated'),heur=gen(b,patch,'heuristic'),now=gen(c,patch,'research');assert.equal(now.result.options.length,15,id);for(const o of now.result.options)assert.equal(o.items.topwear.id,top);mat.push({id,baseline_curated:old,baseline_heuristic:heur,research:now});console.log('TOP',id,old.result.options.length,heur.result.options.length,now.result.options.length);fs.writeFileSync(E+'/PASS3_ALL32_OUTPUTS.json',JSON.stringify(mat,null,2));}return mat.map(x=>({id:x.id,curated:x.baseline_curated.result.options.length,heuristic:x.baseline_heuristic.result.options.length,current:x.research.result.options.length}));});
test('True no-anchor engine produces15 with zero anchor exceptions',()=>{const z=gen(c,{},'research');assert.ok(Object.values(z.q.prefs).every(x=>x.mode==='any'));assert.equal(z.result.options.length,15);assert.equal(z.result.option_policy.exact_anchor_exemptions.length,0);fs.writeFileSync(E+'/NO_ANCHOR.json',JSON.stringify({before:gen(b,{},'curated'),heuristic:gen(b,{},'heuristic'),after:z},null,2));return z.counts;});
test('Previously selected curated method is not silently augmented or relabelled',()=>{for(const id of ['S01','S02','S03','S10','B06']){const top=id[0]==='S'?c.aliases.get(id):c.blazerConnection.knownBlazer(id).historyId,z=gen(c,{topwear:{mode:'item',id:top}},'curated'),o=gen(b,{topwear:{mode:'item',id:top}},'curated');eq(z.result.options,o.result.options);}});
test('Old heuristic choice remains available with exact preserved outputs',()=>{for(const id of ['S01','S10','B06']){const patch={topwear:{mode:'item',id:id[0]==='S'?c.aliases.get(id):c.blazerConnection.knownBlazer(id).historyId}};eq(gen(c,patch,'heuristic').result,gen(b,patch,'heuristic').result);}});
test('Family locks remain exact categories, not repetition exceptions',()=>{const output=[];for(const id of ['lavender','cream','beige','brown','pink','blue']){const z=gen(c,{shirt:{mode:'family',id}},'research');assert.ok(z.result.options.length>0,id);for(const o of z.result.options)assert.ok(pref.matchesFamily(o._hewrsConnected.canonical_selection.shirtId,id));assert.equal(z.result.option_policy.exact_anchor_exemptions.length,0);output.push({id,count:z.result.options.length});}return output;});
test('All four seasonal mild/dry fixtures retain all32 topwear eligibility',()=>{const results=[];for(const season of ['Spring','Summer','Fall','Winter'])for(const row of mat){const top=row.research.q.prefs.topwear.id,z=gen(c,{topwear:{mode:'item',id:top}},'research',{environment:{source:'manual',date:'2026-09-28',season,temperatureBand:'mildWarm',precipitation:'dry'}});assert.equal(z.result.options.length,15,row.id+season);results.push({id:row.id,season,returned:z.result.options.length});}fs.writeFileSync(E+'/SEASON_MATRIX.json',JSON.stringify(results,null,2));return {cases:results.length};});
test('Individual anchors only exempt selected IDs; No Tie explicit opt-in keeps remaining caps',()=>{const rows=[];for(const p of [{shirt:{mode:'item',id:'DS022'}},{tie:{mode:'item',id:'T022'}},{shoes:{mode:'item',id:'shoe-4'}},{watch:{mode:'item',id:'watch-P05'}},{tie:{mode:'none'}},{bottoms:{mode:'item',id:'PG002'}}]){const z=gen(c,p,'research');assert.ok(z.result.options.length);rows.push({p,count:z.result.options.length,counts:z.counts});}return rows;});
test('Invalid IDs and unresolved watch are not repaired or introduced',()=>{for(const p of [{shirt:{mode:'item',id:'DS999'}},{watch:{mode:'item',id:'watch-R18'}}])assert.throws(()=>c.makeRequest(cfg(p)));for(const row of mat)assert.ok(row.research.result.options.every(o=>o.items.watch?.id!=='watch-R18'));});
test('Unsupported scoring premise remains a hold, separate from aesthetic ranking',()=>{const ref=c.hybrid.library.records.find(x=>x.id==='REF_FREE_12');assert.equal(c.hybrid.assess(ref.selection,c.makeRequest(cfg({},'curated'))).code,'SOURCE_HOLD');eq(c.scoreSelection(ref.selection),b.scoreSelection(ref.selection));});
test('Tampered preference/request/IDs fail verification',()=>{const z=gen(c,{},'research');let o=cp(z.result.options[0]);o._hewrsConnected.preference.score+=.1;assert.equal(c.controller.verifyCachedOption(o,z.q,c.catalogue),false);let q=cp(z.q);q.stylist.mode='heuristic';assert.equal(c.controller.verifyCachedOption(z.result.options[0],q,c.catalogue),false);o=cp(z.result.options[0]);o.items.shirt.id='shirt-DS999';assert.equal(c.controller.verifyCachedOption(o,z.q,c.catalogue),false);});
test('Generation leaves inventory, history and favorites unchanged',()=>{const before=JSON.stringify([c.catalogue,root.HEWRS_INPUTS]);gen(c,{shirt:{mode:'item',id:'DS006'}},'research');assert.equal(JSON.stringify([c.catalogue,root.HEWRS_INPUTS]),before);for(const f of ['src/local-state.js','src/favorites-state.js','src/rotation-insights.js','src/weather-context.js','src/automatic-weather.js','src/option-set-policy.js'])assert.equal(fs.readFileSync(R+'/'+f,'utf8'),fs.readFileSync(B+'/'+f,'utf8'));});
(async()=>{try{let z=gen(c,{},'research');let called=0,r=await c.controller.generateAsync(z.q,c.catalogue,[],{isCancelled:()=>++called>2});assert.equal(r.status,'cancelled');checks.push({name:'Research generation cancels without a replacement list',passed:true});let q=c.makeRequest(cfg({},'visual'));await assert.rejects(c.controller.generateAsync(q,c.catalogue,[]),/not connected/);checks.push({name:'Paused private service remains disconnected; no paid request',passed:true});}catch(e){checks.push({name:'Async boundaries',passed:false,error:e.stack});}fs.writeFileSync(E+'/PASS2_RULES_FUNCTIONAL.json',JSON.stringify({checks,passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length},null,2));if(checks.some(x=>!x.passed))process.exitCode=1;console.log('FINAL',checks.filter(x=>x.passed).length,checks.filter(x=>!x.passed).length);})();
