'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const R=path.resolve(__dirname,'..'),E=path.resolve(process.env.HEWRS_TEST_OUTPUT||R+'/evidence/shirt_only_v1_10');fs.mkdirSync(E,{recursive:true});
const common=['data/inputs.js','vendor/hewrs-logic.js','vendor/approved-scores.js','vendor/ensemble-completion.js','vendor/release-guards.js','vendor/request-contract.js','src/controller.js','vendor/watch-classification.js','src/canonical-bindings-browser.js','data/approved-suits.js','src/suit-resolver97-browser.js','src/approved-suit-sources.js','data/suit-assembly.js','data/ds035-coverage.js','data/ds035-edge.js','src/suit-assemblies.js','src/connection.js','data/blazer-connection.js','data/trouser-profiles.js','src/trouser-profiles.js','src/blazer-connection.js'];
function context(extra){const cx=vm.createContext({console,structuredClone,Date,Math,JSON,setTimeout,clearTimeout,Uint8ClampedArray});for(const n of [...common,...extra])vm.runInContext(fs.readFileSync(R+'/'+n,'utf8'),cx,{filename:n});return cx;}
const old=context([]),cx=context(['data/shirt-only.js','src/shirt-only-connection.js','src/local-state.js']),a=cx.HEWRSCleanConnection.create(cx.HEWRS_INPUTS),base=old.HEWRSCleanConnection.create(old.HEWRS_INPUTS),tests=[];
function check(name,fn){try{const detail=fn();tests.push({name,pass:true,detail});}catch(e){tests.push({name,pass:false,error:e.stack});}}
const eq=(x,y)=>assert.equal(JSON.stringify(x),JSON.stringify(y));
const S={shirtOnly:true,pantId:'PG002',shirtId:'DS001',state:'T017',shoeId:'shoe-8',watchId:null};
check('Exactly one pre-existing full-shirt ID and all 47 ties bound',()=>{eq(a.shirtOnlyConnection.ids,['DS001']);assert.equal(a.shirtOnlyConnection.states.length,47);for(const s of a.shirtOnlyConnection.states)eq(a.shirtOnlyConnection.data.shirts.DS001.layers[s],a.blazerConnection.data.assembly.ties[s]);});
check('39,480 exact DS001/trouser/tie/shoe selections validate',()=>{let n=0;for(const pantId of a.blazerConnection.pantIds)for(const state of a.shirtOnlyConnection.states)for(const shoeId of Object.keys(a.shoeLayers)){a.validateSelection({...S,pantId,state,shoeId});n++;}assert.equal(n,39480);return n;});
check('No input data, catalogue, scores or asset map changed by the additive connection',()=>{eq(a.catalogue,base.catalogue);eq(a.assetPaths,base.assetPaths);eq(cx.HEWRS_INPUTS,old.HEWRS_INPUTS);eq(a.registry,base.registry);});
check('Original 39,817 suit requests retain exact validation/history identities',()=>{let n=0;for(const suitId of base.suitSources.ids)for(const shirtId of base.manifest.shirt_order){const states=['NO_TIE',...(base.manifest.shirts[shirtId].mode_policy==='NO_TIE_ONLY'?[]:Object.keys(base.manifest.ties))];if(suitId==='S05'&&shirtId==='DS035')states.push('REFERENCE');for(const state of states){const s={suitId,shirtId,state,shoeId:'shoe-8',watchId:null};eq(a.validateSelection(s),base.validateSelection(s));eq(a.historyIds(s),base.historyIds(s));n++;}}assert.equal(n,39817);return n;});
check('Original 13,536 blazer requests retain exact validation and history identities',()=>{let n=0;for(const blazerId of a.blazerConnection.availableIds)for(const pantId of a.blazerConnection.pantIds)for(const state of a.shirtOnlyConnection.states){const s={blazerId,pantId,shirtId:'DS001',state,shoeId:'shoe-8',watchId:null};eq(a.validateSelection(s),base.validateSelection(s));eq(a.historyIds(s),base.historyIds(s));n++;}assert.equal(n,13536);return n;});
for(const [name,patch] of [['no tie',{state:'NO_TIE'}],['reference',{state:'REFERENCE'}],['different shirt',{shirtId:'DS036'}],['retired shirt',{shirtId:'DS049'}],['unknown shoe',{shoeId:'shoe-50'}],['unknown trousers',{pantId:'PW001'}],['unknown watch',{watchId:'watch-NONE'}],['mixed suit',{suitId:'S05'}],['mixed blazer',{blazerId:'B03'}],['false discriminator',{shirtOnly:false}],['string discriminator',{shirtOnly:'true'}],['extra score',{score:10}],['missing key',{watchId:undefined}]])check('Reject '+name+' without fallback',()=>{let s={...S,...patch};if(name==='missing key')delete s.watchId;assert.throws(()=>a.validateSelection(s));});
check('No shirt-only numerical score is invented',()=>{const score=a.scoreSelection(S,{occasion:'clinic'});assert.equal(score.score,null);assert.equal(score.candidate_eligible,false);assert.throws(()=>a.makeRequest({shirtOnly:true,pantId:S.pantId,shirt:S.shirtId,tie:S.state,shoeId:S.shoeId}));});
check('History has no fabricated topwear and preserves physical trouser identity',()=>eq(a.historyIds(S),{topwear:null,shirt:'shirt-DS001',tie:'T017',shoes:'shoe-8',watch:null,pants:'pants-PG002'}));
function backend(){const values=new Map([['production_sentinel','untouched']]),writes=[];return {getItem:k=>values.get(k)??null,setItem:(k,v)=>{values.set(k,v);writes.push([k,v]);},values,writes};}
const db=backend(),store=cx.HEWRSLocalState.create(a,cx.HEWRS_INPUT_SHA256,db),session={selection:S,origin:'manual',mode:'anchor',localDate:'2026-09-23',context:{occasion:'clinic',requiredFormality:'any'}};
const event=a.createHistoryEvent(S,{id:'shirt_only_001',localDate:'2026-09-23',origin:'manual'});
check('Viewing/session saving does not fabricate wear',()=>{store.saveSession(session);assert.equal(store.snapshot().events.length,0);eq(store.snapshot().session,session);});
check('Explicit wear adds exact shirt-only event',()=>{store.addEvent(event);assert.equal(store.snapshot().events.length,1);eq(store.snapshot().events[0],event);});
check('Existing suit/blazer backup structure remains readable in new validator',()=>{const s={suitId:'S05',shirtId:'DS036',state:'T017',shoeId:'shoe-8',watchId:null};const b={blazerId:'B06',pantId:'PG002',shirtId:'DS001',state:'T017',shoeId:'shoe-8',watchId:null};for(const x of [s,b]){const v={...store.snapshot(),session:{...session,selection:x},events:[base.createHistoryEvent(x,{id:'legacy_'+(x.suitId||x.blazerId),localDate:'2026-09-23',origin:'manual'})]};eq(store.validate(v),v);}});
check('Fresh storage-interface instance reopens mixed ledger exactly',()=>{const reopened=cx.HEWRSLocalState.create(a,cx.HEWRS_INPUT_SHA256,db);eq(reopened.snapshot(),store.snapshot());});
check('Preview is read-only; explicit restore writes only candidate namespace',()=>{const n=db.writes.length,preview=store.previewImport(store.exportText());assert.equal(db.writes.length,n);store.restore(preview);assert.equal(db.writes.length,n+1);assert.equal(db.values.get('production_sentinel'),'untouched');assert.ok(db.writes.every(x=>x[0]===store.key));});
check('Reject fake Engine shirt-only session/event and injected identities',()=>{const v=store.snapshot();for(const x of [{...v,session:{...v.session,mode:'engine'}},{...v,session:{...v.session,origin:'engine'}},{...v,events:[{...event,origin:'engine'}]},{...v,events:[{...event,items:{...event.items,topwear:{id:'suit-4'}}}]}])assert.throws(()=>store.validate(x));assert.throws(()=>a.createHistoryEvent(S,{id:'fake',localDate:'2026-09-23',origin:'engine'}));});
check('Suit and blazer scoring/requests unchanged, including after shirt-only wear',()=>{let n=0;for(const cfg of [{suitId:'S05',shirt:'DS036',tie:'T017'},{suitId:'S18',shirt:'DS017',tie:'ANY'},{blazerId:'B03',pantId:'PG002',shirt:'DS001',tie:'T017'},{blazerId:'B14',pantId:'PT001',shirt:'DS001',tie:'ANY'}]){const c={...cfg,shoeId:'shoe-8',watchId:null,localDate:'2026-09-23',occasion:'clinic',style:'AUTO'},q=a.makeRequest(c);eq(q,base.makeRequest(c));const aa=a.controller.generate(q,a.catalogue,[event]),bb=base.controller.generate(q,base.catalogue,[event]);eq(aa,bb);assert.equal(aa.options.length,bb.options.length);for(const o of aa.options){eq(a.selectionFromOption(o,q),base.selectionFromOption(o,q));n++;}}return n;});
const out={schema:'hewrs.shirt-only-functional.v1_10',passed:tests.filter(t=>t.pass).length,failed:tests.filter(t=>!t.pass).length,tests,scope:'Application wiring and isolated storage interface; not native device persistence or garment reapproval'};fs.writeFileSync(E+'/FUNCTIONAL.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));if(out.failed)process.exitCode=1;
