'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('node:assert/strict');
const R=path.resolve(__dirname,'..'),B=process.env.HEWRS_BASELINE;
if(!B)throw Error('Set HEWRS_BASELINE to the intact V1.23.0 source tree');
const load=require('./core-loader.cjs'),g=load(R),gb=load(B),c=g.HEWRSCleanConnection.create(g.HEWRS_INPUTS),b=gb.HEWRSCleanConnection.create(gb.HEWRS_INPUTS);
const d=g.HEWRSShoePhotoCorrections.record(),norm=x=>JSON.parse(JSON.stringify(x));
const checks=[];function test(name,fn){try{let detail=fn();checks.push({name,passed:true,detail:detail??null});console.log('PASS',name);}catch(e){checks.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.message);}}
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
test('Original input bytes and identity lock are unchanged',()=>{assert.equal(hash(R+'/data/inputs.json'),hash(B+'/data/inputs.json'));assert.equal(hash(R+'/data/inputs.js'),hash(B+'/data/inputs.js'));assert.equal(g.HEWRS_INPUT_SHA256,gb.HEWRS_INPUT_SHA256);});
test('Only shoe-15 descriptor changes; exact shoe universe and order retained',()=>{assert.deepEqual(Object.keys(c.shoeLayers),Object.keys(b.shoeLayers));for(const id of Object.keys(b.shoeLayers)){if(id!=='shoe-15')assert.deepEqual(norm(c.shoeLayers[id]),norm(b.shoeLayers[id]));}assert.equal(c.shoeLayers['shoe-15'].sha256,d.layer.sha256);assert.equal(c.assetPaths[d.layer.sha256],d.layer.url);return {registered_shoes:Object.keys(c.shoeLayers).length};});
test('All 18 suit routes receive corrected shoe-15 and no other shoe substitutions',()=>{for(const id of c.assemblies.dynamicSuitIds){assert.equal(c.assemblies.forSelection(id,'shoe-15','DS001').static.shoe.sha256,d.layer.sha256);assert.deepEqual(norm(c.assemblies.forSelection(id,'shoe-8','DS001').static.shoe),norm(b.assemblies.forSelection(id,'shoe-8','DS001').static.shoe));}return {suits:c.assemblies.dynamicSuitIds.length};});
test('Broad brown color, material/category, availability and old score premises retained',()=>{const x=norm(c.catalogue.shoes.find(x=>x.id==='shoe-15')),y=norm(b.catalogue.shoes.find(x=>x.id==='shoe-15'));assert.equal(x.color,y.color);assert.equal(g.HEWRSLegacyAccessories.shoeFamily(x),gb.HEWRSLegacyAccessories.shoeFamily(y));for(const[k,v]of Object.entries(y))if(k!=='name')assert.deepEqual(x[k],v);assert.equal(x.name,d.display_name);return {color:x.color,name:x.name};});
test('Other catalogue entries, canonical source profiles and limits are identical',()=>{for(const k of Object.keys(b.catalogue)){const x=norm(c.catalogue[k]),y=norm(b.catalogue[k]);if(k==='shoes'){assert.deepEqual(x.filter(i=>i.id!=='shoe-15'),y.filter(i=>i.id!=='shoe-15'));}else assert.deepEqual(x,y);}assert.deepEqual(norm([...c.features]),norm([...b.features]));assert.deepEqual(norm(c.limits),norm(b.limits));});
test('Only shoe-15 thumbnail changes and it is explicitly the owner reference',()=>{const x=norm(g.HEWRS_OPTION_CARD_THUMBNAILS),y=norm(gb.HEWRS_OPTION_CARD_THUMBNAILS);assert.equal(x.shoes['shoe-15'].source_kind,'owner_reference_photo');x.shoes['shoe-15']=y.shoes['shoe-15'];assert.deepEqual(x,y);assert.equal(hash(R+'/'+d.thumbnail.src),d.thumbnail.sha256);assert.equal(hash(R+'/'+d.source.path),d.source.sha256);});
test('Exact selection, history identity and original clothing compatibility unchanged',()=>{for(const state of ['T017','NO_TIE']){const s={suitId:'S05',shirtId:'DS001',state,shoeId:'shoe-15',watchId:null};assert.deepEqual(norm(c.validateSelection(s)),norm(b.validateSelection(s)));assert.deepEqual(norm(c.historyIds(s)),norm(b.historyIds(s)));assert.deepEqual(norm(c.scoreSelection(s)),norm(b.scoreSelection(s)));}return {cases:2};});
test('Missing or wrong baseline source fails, never silently substitutes',()=>{const p=norm(g.HEWRSSourceCorrections.apply(g.HEWRS_INPUTS));p.shoeLayers['shoe-15'].sha256='0'.repeat(64);assert.throws(()=>g.HEWRSShoePhotoCorrections.apply(p),/baseline has changed/);});
test('Every original asset remains byte-identical at its original path',()=>{let count=0;for(const entry of JSON.parse(fs.readFileSync(B+'/PACKAGE_SHA256.json')).files){if(/^(assets|assemblies)\//.test(entry.path)){assert.equal(hash(R+'/'+entry.path),entry.sha256,entry.path);count++;}}return {original_assets_unchanged:count};});
const out={schema:'hewrs.shoe15.tests.v1',scope:'New local source/runtime checks; not production deployment or owner approval',passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length,checks};fs.mkdirSync(R+'/evidence/shoe15_v1_23_1',{recursive:true});fs.writeFileSync(R+'/evidence/shoe15_v1_23_1/SOURCE_TESTS.json',JSON.stringify(out,null,2)+'\n');if(out.failed)process.exitCode=1;
