'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const R=path.resolve(__dirname,'..'),B=process.env.HEWRS_BASELINE_V1174||path.resolve(R,'../baseline'),load=require('./core-loader.cjs'),g=load(R),old=load(B),c=g.HEWRSCleanConnection.create(g.HEWRS_INPUTS),b=old.HEWRSCleanConnection.create(old.HEWRS_INPUTS),E=R+'/evidence/recalibration_v1_18_0';
const cases=[],checks=[],day='2026-09-28';const pref=ch=>({...Object.fromEntries(['topwear','shirt','tie','shoes','bottoms','watch'].map(k=>[k,{mode:'any'}])),watch:{mode:'none'},...ch});
function query(cc,ch){return cc.makeRequest({automatic:true,preferences:pref(ch),style:'AUTO',localDate:day,occasion:'clinic',formality:'any',environment:{source:'not_assessed',date:day}});}
function items(r){return r.options.map(o=>({selection:o._hewrsConnected.canonical_selection,legacy:o._hewrsConnected.compatibility.display_score,preference:o._hewrsConnected.preference?.score??null,curation:o._hewrsConnected.curation??null}));}
function counts(r,q){const cs={},ids=new Set(),locks=new Set();for(const[k,v]of Object.entries(q.prefs))if(v.mode==='item')locks.add(k==='shirt'?'shirt-'+v.id:k==='bottoms'?'pants-'+v.id:v.id);let nt=0;for(const o of r.options){const s=o._hewrsConnected.canonical_selection;for(const v of Object.values(o.items))if(v)cs[v.id]=(cs[v.id]||0)+1;const id=[s.suitId||s.blazerId,s.pantId||'',s.shirtId,s.state].join('|');assert.ok(!ids.has(id));ids.add(id);nt+=s.state==='NO_TIE';assert.ok(c.controller.verifyCachedOption(o,q,c.catalogue));}for(const[id,n]of Object.entries(cs))if(!locks.has(id))assert.ok(n<=2,id);if(q.prefs.tie.mode!=='none')assert.ok(nt<=2);return {counts:cs,noTie:nt};}
function save(){fs.writeFileSync(E+'/PASS2_WARDROBE_MATRIX.json',JSON.stringify({cases,checks,passed:checks.filter(x=>x.passed).length,failed:checks.filter(x=>!x.passed).length},null,2));}
function run(type,id,ch,compare=false){const start=Date.now();try{const q=query(c,ch),r=c.controller.generate(q,c.catalogue,[]),cc=counts(r,q);if(compare)assert.equal(r.options.length,15);const before=compare?b.controller.generate(query(b,ch),b.catalogue,[]):null;cases.push({type,id,query:q,baseline:before?items(before):null,updated:items(r),count:r.options.length,counters:cc,diagnostics:r.diagnostics,reason:r.reason,milliseconds:Date.now()-start});checks.push({name:type+':'+id,passed:true});console.log('PASS',type,id,r.options.length,Date.now()-start);}catch(e){checks.push({name:type+':'+id,passed:false,error:e.stack});console.log('FAIL',type,id,e.stack);}save();}
for(const id of c.suitSources.ids)run('suit',id,{topwear:{mode:'item',id:c.aliases.get(id)}},true);
for(const id of c.blazerConnection.availableIds)run('blazer',id,{topwear:{mode:'item',id:c.blazerConnection.knownBlazer(id).historyId}},true);
for(const id of c.manifest.shirt_order)run('shirt',id,{shirt:{mode:'item',id}});
for(const id of Object.keys(c.manifest.ties))run('tie',id,{tie:{mode:'item',id}});
if(checks.some(x=>!x.passed))process.exitCode=1;
