/* V1.11 presentation adapter for the approved original-palette facelift.
 * Source authority: V1.10 connection, renderer, catalogue and local-state module.
 * This file does not score outfits, modify garment data or own a storage schema. */
(function(root){'use strict';
const $=id=>document.getElementById(id),copy=x=>structuredClone(x),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const need=(v,m)=>{if(!v)throw Error(m);};
const connection=root.HEWRSCleanConnection.create(root.HEWRS_INPUTS);
let backend;try{backend=root.localStorage;}catch{backend=null;}
const store=root.HEWRSLocalState.create(connection,root.HEWRS_INPUT_SHA256,backend),ui=root.HEWRSFaceliftModel.create(connection),urlCache=new Map();
function resolveUrl(d){need(Object.hasOwn(connection.assetPaths,d.sha256),'Unbound image hash; no fallback');if(root.HEWRS_EMBEDDED_IMAGES){if(!urlCache.has(d.sha256)){const v=root.HEWRS_EMBEDDED_IMAGES[d.sha256];need(v,'Embedded image missing');urlCache.set(d.sha256,'data:image/png;base64,'+v);}return urlCache.get(d.sha256);}return connection.assetPaths[d.sha256];}
const renderer=root.HEWRSAtomicRenderer.create($('avatar'),connection,{resolveUrl});
const defaultSelection={suitId:'S05',shirtId:'DS036',state:'T017',shoeId:'shoe-8',watchId:null};
const names={topwear:'Suit / Blazer',shirt:'Shirt',tie:'Tie',shoes:'Shoes',bottoms:'Bottoms',watch:'Watch'};
const groupLabels={suits:'Suits',blazers:'Blazers',shirts:'Dress Shirts',ties:'Ties',shoes:'Shoes',pants:'Pants',jeans:'Jeans',tshirts:'T-Shirts',watches:'Watches'};
const styleLabels={AUTO:'Automatic',CLASSIC:'Classical',HYBRID:'Hybrid',MODERN:'Modern'};
let current=null,currentOption=null,score=null,origin='manual',mode='anchor',pageName='home',generation=0,report=null,lastRequest=null,options=[],optionIndex=-1,producing=null,restorePreview=null,modal=null,modalEpoch=0,logTransaction=null,busy=false;
let ctx={occasion:'clinic',formality:'any',style:'AUTO',localDate:localToday()};
function localToday(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function icon(name){const n=document.createElementNS('http://www.w3.org/2000/svg','svg');for(const[k,v]of Object.entries({class:'fx-icon',viewBox:'0 0 24 24',fill:'none',stroke:'currentColor','stroke-width':'1.5','stroke-linecap':'round','stroke-linejoin':'round','aria-hidden':'true'}))n.setAttribute(k,v);const u=document.createElementNS(n.namespaceURI,'use');u.setAttribute('href','#fx-icon-'+name);n.append(u);return n;}
function ids(s){if(!s)return 'No outfit selected';return (s.shirtOnly?'Shirt only · '+s.pantId:s.blazerId?s.blazerId+' · '+s.pantId:s.suitId)+' · '+s.shirtId+' · '+(s.state==='NO_TIE'?'No Tie':s.state);}
function status(text,error=false){$('status').textContent=text;$('home-notice').textContent=text;$('home-notice').dataset.error=String(error);}
function errorText(error){return error instanceof Error?error.message:String(error);}
function setMode(v){need(['anchor','engine'].includes(v),'Unknown selection workflow');mode=v;for(const k of ['anchor','engine'])$('mode-'+k).setAttribute('aria-pressed',String(v===k));}
function updateHome(){
 for(const cat of ui.categories){const q=ui.label(cat),b=$('pref-'+cat);b.dataset.choice=q.mode;$('pref-'+cat+'-mode').textContent=q.mode==='any'?'Engine':q.mode==='family'?'Category preference':q.mode==='included'?'Matching trousers':'My selection';$('pref-'+cat+'-id').textContent=q.id||'';$('pref-'+cat+'-value').textContent=q.name;b.title=names[cat]+': '+(q.id?q.id+' — ':'')+q.name;b.disabled=q.mode==='included';b.setAttribute('aria-label',b.title+(q.mode==='included'?'; separate Bottoms inactive':''));}
 $('lock-count').textContent=ui.lockCount()+' selected';$('work-label').textContent={clinic:'Clinic',hospital:'Hospital',work:'Work'}[ctx.occasion]||ctx.occasion;$('style-label').textContent=styleLabels[ctx.style]||ctx.style;$('header-date').textContent=ctx.localDate;$('view-current').hidden=!current;
}
function showPage(name){need(['home','outfits','wardrobe','rotation'].includes(name),'Unknown route');pageName=name;for(const k of ['home','outfits','wardrobe','rotation'])$('page-'+k).hidden=k!==name;for(const n of document.querySelectorAll('[data-page]')){if(n.dataset.page===name)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current');}$('back-home').hidden=name==='home';$('weather-button').hidden=name!=='home';$('quick-log').hidden=name!=='outfits';if(name==='wardrobe')renderGroups();if(name==='rotation')refreshHistory();if(name==='home')updateHome();}
function dismissSheet(cancel=true){if(!modal){if($('fx-sheet').open)$('fx-sheet').close();return;}const old=modal;modal=null;modalEpoch++;if(cancel)old.cancel?.();if($('fx-sheet').open)$('fx-sheet').close();old.focus?.focus?.();}
function openSheet(title,{cancel}={}){dismissSheet();const focus=document.activeElement,token=++modalEpoch;modal={token,cancel,focus};$('fx-sheet-title').textContent=title;$('fx-sheet-body').replaceChildren();$('fx-sheet-actions').replaceChildren();$('fx-sheet-error').textContent='';$('fx-sheet').showModal();return {body:$('fx-sheet-body'),actions:$('fx-sheet-actions'),token};}
function sheetError(e){$('fx-sheet-error').textContent=errorText(e);}
function button(text,fn,primary=false){const n=el('button',text,primary?'fx-primary':'');n.type='button';n.onclick=async()=>{try{await fn();}catch(e){sheetError(e);}};return n;}
function message(title,text){const{body,actions}=openSheet(title);body.append(el('p',text,'fx-caption'));actions.append(button('Close',()=>dismissSheet()));}
function selectField(label,rows,value,id){const wrap=el('label',label),sel=el('select');if(id)sel.id=id;for(const r of rows){const o=new Option(r.label,r.value);o.disabled=!!r.disabled;sel.add(o);}sel.value=value;wrap.append(sel);return {wrap,input:sel};}
function currentContext(){return {occasion:ctx.occasion,requiredFormality:ctx.formality};}
function contextSheet(kind){
 if(kind==='weather'||kind==='season'){message(kind==='weather'?'Weather':'Season','The current application has no connected '+kind+' provider or manual-band handler. No sample reading is shown and no '+kind+' eligibility rule is added by the facelift.');return;}
 const{body,actions}=openSheet(kind==='style'?'Style':'Work & date'),form=el('div',undefined,'fx-context-form'),draft=copy(ctx);body.append(form);
 if(kind==='style'){const s=selectField('Existing style profile',Object.entries(styleLabels).map(([value,label])=>({value,label})),draft.style,'style-select');form.append(s.wrap);s.input.onchange=()=>draft.style=s.input.value;}
 else{const s=selectField('Setting',[{value:'clinic',label:'Clinic'},{value:'hospital',label:'Hospital'},{value:'work',label:'Work'},{value:'dinner',label:'Dinner — not connected in current build',disabled:true},{value:'weekend',label:'Weekend — not connected in current build',disabled:true}],draft.occasion,'occasion-select');const f=selectField('Required formality',[{value:'any',label:'Unspecified'},{value:'tie_required',label:'Tie required'},{value:'suit_required',label:'Suit required'},{value:'open_collar_allowed',label:'Open collar allowed'}],draft.formality,'formality-select');const l=el('label','Wear / rotation date'),d=el('input');d.type='date';d.id='local-date';d.value=draft.localDate;l.append(d);form.append(s.wrap,f.wrap,l);s.input.onchange=()=>draft.occasion=s.input.value;f.input.onchange=()=>draft.formality=f.input.value;d.onchange=()=>draft.localDate=d.value;}
 actions.append(button('Cancel',()=>dismissSheet()),button('Apply',()=>{need(root.HEWRSLocalState.date(draft.localDate),'Enter a valid local calendar date');ctx=draft;dismissSheet(false);updateHome();},true));
}
function openPicker(cat){
 if(cat==='bottoms'&&ui.included())return;
 const{body,actions}=openSheet(names[cat],{cancel:()=>ui.cancel()});ui.begin(cat);
 const seg=el('div',undefined,'fx-segment'),engine=button('Engine Choice',()=>{ui.choose({mode:'any'});setSegment(true);renderChoices();}),mine=button('My Selection',()=>{if(ui.draft().choice?.mode==='any')ui.choose(null);setSegment(false);renderChoices();});engine.id='picker-engine';mine.id='picker-mine';seg.append(engine,mine);body.append(seg);
 const note=el('p','Apply changes only this preference. Cancel discards the draft.','fx-caption');body.append(note);
 const search=el('input',undefined,'fx-search');search.type='search';search.id='picker-search';search.placeholder='Search actual name or ID';search.setAttribute('aria-label','Search '+names[cat]);
 const filters=el('div',undefined,'fx-picker-filter');let filter={query:'',type:'',brand:'',color:''};
 const typeRows=[{value:'',label:'All types'},...([...new Set(ui.rows[cat].map(x=>x.kind))].map(v=>({value:v,label:({'suit':'Suits',blazer:'Blazers','shirt-only':'Shirt only'})[v]||v})))];const types=selectField('Type',typeRows,'','picker-type');
 const brands=selectField('Brand',[{value:'',label:'All brands'},...[...new Set(ui.rows[cat].map(x=>x.brand).filter(Boolean))].sort().map(v=>({value:v,label:v}))],'','picker-brand');filters.append(types.wrap,brands.wrap);
 const family=ui.families[cat]?selectField('Color',[{value:'',label:'All colors'},...ui.families[cat].map(v=>({value:v,label:v.charAt(0).toUpperCase()+v.slice(1)}))],'','picker-color'):null;if(family)filters.append(family.wrap);
 const list=el('div',undefined,'fx-picker-list');list.id='picker-list';const count=el('p','', 'fx-caption');count.id='picker-count';body.append(search,filters,count,list);
 const apply=button('Apply',()=>{ui.commit();dismissSheet(false);updateHome();status('Preference applied. Generate to display the resulting outfit.');},true);apply.id='picker-apply';actions.append(button('Cancel',()=>dismissSheet()),apply);
 function setSegment(isEngine){engine.setAttribute('aria-pressed',String(isEngine));mine.setAttribute('aria-pressed',String(!isEngine));}
 function addChoice(c,label,id,extra='',disabled=false){const n=el('button',undefined,'fx-choice');n.type='button';if(id){n.dataset.itemId=id;n.append(el('span',id,'fx-choice-id'));}n.append(el('span',label,'fx-choice-name'));if(extra)n.append(el('small',extra));n.disabled=disabled;n.setAttribute('aria-pressed',String(JSON.stringify(c)===JSON.stringify(ui.draft()?.choice)));n.onclick=()=>{ui.choose(c);setSegment(c.mode==='any');renderChoices();};list.append(n);}
 function renderChoices(){const d=ui.draft();if(!d)return;list.replaceChildren();const selected=d.choice;setSegment(selected?.mode==='any');apply.disabled=!selected;
  if(cat==='tie')addChoice({mode:'none'},'No Tie','NO_TIE','Intentional open-collar selection; not Engine / Any');
  if(cat==='watch')addChoice({mode:'none'},'No watch selected','NO_WATCH','Watch ID and name are sufficient for this release');
  if(family&&filter.color)addChoice({mode:'family',id:filter.color},'Engine chooses within '+filter.color+' family','CATEGORY: '+filter.color,'Category preference, not an exact item');
  const found=ui.filter(cat,filter);count.textContent=found.length+' current items. '+(cat==='shoes'?'An exact registered shoe is required by the current generator.':cat==='topwear'?'An exact outfit type/item is required by the current generator.':cat==='watch'?'Watch photos are deferred.':'Filters narrow this list; Apply a family preference explicitly to constrain Engine.');
  for(const r of found)addChoice({mode:'item',id:r.id},r.label,r.sourceId||r.id,r.available?'':'Source connection unavailable; catalogue identity retained',!r.available);
  if(!found.length)list.append(el('div','No current item matches these filters.','fx-empty'));
 }
 function changed(){filter={query:search.value,type:types.input.value,brand:brands.input.value,color:family?.input.value||''};const chosen=ui.draft()?.choice;if(chosen?.mode==='item'&&!ui.filter(cat,filter).some(x=>x.id===chosen.id)){ui.choose(null);$('fx-sheet-error').textContent='The previous draft item is outside these filters. Choose an item or family before Apply.';}else if(chosen?.mode==='family'&&filter.color!==chosen.id){ui.choose(null);}renderChoices();}
 search.oninput=changed;types.input.onchange=changed;brands.input.onchange=changed;if(family)family.input.onchange=changed;renderChoices();search.focus();
}
function setBusy(value){busy=value;$('cancel-work').hidden=!value;$('generate-options').disabled=value;$('generate-options').textContent=value?'Building outfits…':'Generate Options →';$('stage').classList.toggle('busy',value);$('regenerate').disabled=value||!producing;updateLogButtons();}
function updateLogButtons(){const blocked=busy||!current||current.state==='REFERENCE'||!!logTransaction?.pending||$('outfit-output').hidden;$('record-wear').disabled=blocked;$('quick-log').disabled=blocked;}
function itemsFor(s){if(!s)return [];
 const top=s.shirtOnly?{id:null,name:'Shirt only — no jacket'}:s.blazerId?{id:s.blazerId,name:connection.blazerConnection.knownBlazer(s.blazerId).label}:{id:s.suitId,name:connection.features.get(s.suitId)?.description||s.suitId};
 const pants=s.pantId?{id:s.pantId,name:connection.blazerConnection.knownPant(s.pantId).label}:{id:null,name:'Included with suit'};
 const shoe=connection.catalogue.shoes.find(x=>x.id===s.shoeId),watch=connection.catalogue.watches.find(x=>x.id===s.watchId);
 return [{role:'Suit / Blazer',...top},{role:'Shirt',id:s.shirtId,name:connection.records[s.shirtId].label},{role:'Tie',id:s.state==='NO_TIE'?null:s.state,name:s.state==='NO_TIE'?'No Tie':s.state==='REFERENCE'?'Retained reference':connection.features.get(s.state)?.description||s.state},{role:'Shoes',id:s.shoeId,name:shoe?.name||s.shoeId},{role:'Bottoms',...pants},{role:'Watch',id:s.watchId,name:watch?.name||'No watch selected'}];
}
function selectionKey(s){return JSON.stringify(connection.historyIds(s));}
function displayCurrent(){if(!current)return;
 $('selection-ids').textContent=ids(current);$('selection-origin').textContent=origin==='engine'?(currentOption?._hewrsConnected?.is_recommendation?'Local rotation choice':'Compatibility option'):'Your selection';
 $('score-value').textContent=Number.isFinite(score?.display_score)?score.display_score.toFixed(2):'—';$('score-label').textContent=score?.style?.classification||score?.status||'Unavailable';
 const summary=$('item-summary');summary.replaceChildren();for(const r of itemsFor(current)){const t=el('span',undefined,'fx-item-mini');t.title=r.role+': '+(r.id?r.id+' — ':'')+r.name;t.append(el('span',r.id||r.role,'fx-mini-id'),el('span',r.name,'fx-mini-name'));summary.append(t);}
 const w=itemsFor(current).find(x=>x.role==='Watch');$('representation').textContent=w.id?w.id+' · '+w.name:'No watch selected';
 $('option-count').textContent=options.length&&optionIndex>=0?'Option '+(optionIndex+1)+' of '+options.length:'Current selection';$('prev-option').disabled=busy||options.length<2||optionIndex<=0;$('next-option').disabled=busy||options.length<2||optionIndex>=options.length-1;$('open-results').disabled=!options.length;
 updateLogButtons();$('view-current').hidden=false;
}
function presentFrame(){ $('outfit-empty').hidden=true;$('outfit-output').hidden=false; }
function presentEmpty(text){$('outfit-empty').textContent=text;$('outfit-empty').hidden=false;$('outfit-output').hidden=true;$('option-count').textContent='0 options';updateLogButtons();}
function sessionValue(s,o,date,context){return {selection:copy(s),origin:o,mode,localDate:date,context:copy(context)};}
async function apply(s,opts={}){
 const token=opts.token??++generation;if(opts.token===undefined)renderer.cancel();connection.validateSelection(s);if(s.shirtOnly&&opts.origin&&opts.origin!=='manual')throw Error('Shirt-only is an exact manual selection');
 const priorBusy=busy;setBusy(true);status(current?'Loading next outfit…':'Loading approved source layers…');
 try{const out=await renderer.render(s);if(token!==generation||out.cancelled)return {cancelled:true};
  current=copy(s);origin=opts.origin||'manual';currentOption=opts.option||null;score=opts.score||connection.scoreSelection(s,opts.context||currentContext());
  if(s.shirtOnly)setMode('anchor');if(opts.localDate)ctx.localDate=opts.localDate;if(opts.context){ctx.occasion=opts.context.occasion;ctx.formality=opts.context.requiredFormality;}
  if(!opts.keepPreferences)ui.fromSelection(s);presentFrame();displayCurrent();updateHome();
  if(opts.save!==false){try{store.saveSession(sessionValue(s,origin,ctx.localDate,opts.context||currentContext()));}catch(e){status('Outfit ready. '+e.message,true);refreshHistory();return out;}}
  refreshHistory();status(origin==='engine'?'Engine result ready.':'Selection ready.');return out;
 }catch(e){if(token===generation)status('Selection not applied: '+e.message,true);throw e;}
 finally{if(token===generation){setBusy(priorBusy&&opts.token!==undefined);displayCurrent();}}
}
async function selectOption(index){need(index>=0&&index<options.length,'Option unavailable');const o=options[index],q=lastRequest;need(connection.controller.verifyCachedOption(o,q,connection.catalogue),'Results are no longer current; generate again');const b=connection.selectionFromOption(o,q);const out=await apply(b.selection,{origin:'engine',option:o,score:o._hewrsConnected.compatibility,context:q.context,localDate:q.localDate,keepPreferences:true});if(!out.cancelled){optionIndex=index;displayCurrent();}return out;}
async function generate(c,extra={}){
 const q=connection.makeRequest(c),previousKey=current?selectionKey(current):null,previousRequest=lastRequest?JSON.stringify(lastRequest):null,token=++generation;renderer.cancel();lastRequest=copy(q);options=[];report=null;optionIndex=-1;currentOption=null;
 producing={kind:'engine',config:copy(c),prefs:copy(extra.prefs||ui.snapshot()),mode,context:copy(ctx)};setBusy(true);status('Building outfits…');
 try{const r=await connection.controller.generateAsync(q,connection.catalogue,store.snapshot().events,{isCancelled:()=>token!==generation,onProgress:p=>{if(token===generation)status('Building outfits… '+p.examined+' combinations evaluated.');}});if(token!==generation||r.status==='cancelled')return {cancelled:true};
  report=r;options=r.options||[];$('outfit-summary').textContent=options.length+' options · '+(r.diagnostics?.examined||0)+' combinations evaluated. Existing local-history rules.';
  if(!options.length){presentEmpty(r.reason||(r.status==='mapping_required'?'No recorded numeric profile for these exact trousers. Anchor remains available.':'No scored result for these preferences. No item was substituted.'));status('No scored result. Preferences retained.');showPage('outfits');return r;}
  let index=0;if(previousKey&&previousRequest===JSON.stringify(q)){const match=options.findIndex(o=>selectionKey(connection.selectionFromOption(o,q).selection)===previousKey);if(match>=0)index=match;}
  const o=options[index],b=connection.selectionFromOption(o,q);const frame=await apply(b.selection,{token,origin:'engine',option:o,score:o._hewrsConnected.compatibility,context:q.context,localDate:q.localDate,keepPreferences:true});if(token!==generation||frame.cancelled)return {cancelled:true};optionIndex=index;presentFrame();displayCurrent();showPage('outfits');return r;
 }catch(e){if(token===generation){options=[];report={status:'error',reason:e.message};optionIndex=-1;presentEmpty('Generation failed: '+e.message);status('Generation failed: '+e.message,true);showPage('outfits');}throw e;}
 finally{if(token===generation){setBusy(false);displayCurrent();}}
}
async function submit(){if(busy)return;try{need(root.HEWRSLocalState.date(ctx.localDate),'Enter a valid local date');const op=ui.operation(mode,ctx);if(op.kind==='manual'){options=[];optionIndex=-1;lastRequest=null;report=null;producing={kind:'manual',selection:copy(op.selection),prefs:copy(op.prefs),mode,context:copy(ctx)};$('outfit-summary').textContent='Exact manual selection; existing score-source holds do not block supported rendering.';const r=await apply(op.selection,{origin:'manual',keepPreferences:true,context:currentContext(),localDate:ctx.localDate});if(!r.cancelled)showPage('outfits');}else await generate(op.config,{prefs:op.prefs});}catch(e){status(e.message,true);}}
function cancel(){generation++;renderer.cancel();setBusy(false);status('Pending work cancelled. Previous complete outfit retained.');if(current){presentFrame();displayCurrent();}}
function invalidateRecommendations(){options=[];lastRequest=null;report=null;optionIndex=-1;currentOption=null;origin='manual';producing=null;$('outfit-summary').textContent='Local history changed. Generate again for a current rotation recommendation.';displayCurrent();}
function details(){if(!current)return;const{body,actions}=openSheet('Outfit details');for(const r of itemsFor(current)){const row=el('div',undefined,'fx-details-item');row.append(el('strong',r.role+(r.id?' · '+r.id:'')),el('span',r.name));body.append(row);}body.append(el('p','Watch ID and name are shown; watch imagery is deferred.','fx-caption'));actions.append(button('Close',()=>dismissSheet()));}
function scoreDetails(){const{body,actions}=openSheet('Score details');body.append(el('p',Number.isFinite(score?.display_score)?score.display_score.toFixed(2)+' / 10 — '+(score.style?.classification||score.status):'A score is unavailable for this selection. It is not zero.','fx-caption'),el('pre',JSON.stringify(score,null,2)));actions.append(button('Close',()=>dismissSheet()));}
function resultSheet(){const{body,actions}=openSheet('Outfit options');if(!options.length)body.append(el('p',report?.reason||'No current Engine options.','fx-caption'));for(const [i,o]of options.entries()){const s=connection.selectionFromOption(o,lastRequest).selection;const b=el('button',undefined,'fx-choice');b.append(el('span',(i+1)+' · '+ids(s),'fx-choice-id'),el('span',connection.records[s.shirtId].label,'fx-choice-name'),el('span',o._hewrsConnected.compatibility.display_score.toFixed(2)+' / 10','fx-option-score'));b.onclick=async()=>{try{dismissSheet();await selectOption(i);showPage('outfits');}catch(e){status(e.message,true);}};body.append(b);}actions.append(button('Close',()=>dismissSheet()));}
function canLog(){return !!current&&!busy&&!$('outfit-output').hidden&&current.state!=='REFERENCE';}
function startLog(){if(!canLog()||logTransaction?.pending)return;if(modal?.kind==='wear')return;
 const sel=copy(current),o=origin,date=ctx.localDate,id='wear_'+(root.crypto?.randomUUID?.()||Date.now()+'_'+Math.random().toString(16).slice(2));const{body,actions,token}=openSheet('Log This Outfit',{cancel:()=>{if(!logTransaction?.pending)logTransaction=null;updateLogButtons();}});modal.kind='wear';
 logTransaction={id,selection:sel,origin:o,done:false,pending:false,token};body.append(el('p',ids(sel),'fx-caption'));const label=el('label','Actual wear date','fx-context-form'),d=el('input');d.type='date';d.id='wear-date';d.value=date;label.append(d);const check=el('label',undefined,'fx-check-row'),c=el('input');c.type='checkbox';c.id='repeat-incident';check.append(c,el('span','Record a controlled repetition incident'));body.append(label,check,el('p','Confirm only an outfit actually worn. Viewing or generating never logs wear.','fx-caption'));
 const confirm=button('Confirm actual wear',async()=>{const tx=logTransaction;if(!tx||tx.done||tx.pending||tx.token!==token)return;need(root.HEWRSLocalState.date(d.value),'Enter a valid wear date');tx.pending=true;confirm.disabled=true;updateLogButtons();try{store.addEvent(connection.createHistoryEvent(tx.selection,{id:tx.id,localDate:d.value,origin:tx.origin==='engine'?'engine':'manual',controlledRepetition:c.checked}));tx.done=true;dismissSheet(false);logTransaction=null;invalidateRecommendations();refreshHistory();status(store.status().persistent?'Wear recorded.':'Wear recorded in session memory. Export to retain it.');}catch(e){tx.pending=false;confirm.disabled=false;sheetError(e);}finally{updateLogButtons();}},true);confirm.id='confirm-wear';actions.append(button('Cancel',()=>dismissSheet()),confirm);
}
function wardrobeRows(group){
 if(group==='suits')return ui.rows.topwear.filter(r=>r.kind==='suit').map(r=>({...r,id:r.sourceId,category:'topwear',choiceId:r.id,view:connection.assemblies.registeredView(r.sourceId),detail:connection.suitSources.resolveCanonical(r.sourceId)}));
 if(group==='blazers')return ui.rows.topwear.filter(r=>r.kind==='blazer').map(r=>({...r,id:r.sourceId,category:'topwear',choiceId:r.id,detail:connection.blazerConnection.knownBlazer(r.sourceId)}));
 if(group==='shirts')return ui.rows.shirt.map(r=>({...r,category:'shirt',choiceId:r.id}));
 if(group==='ties')return ui.rows.tie.map(r=>({...r,category:'tie',choiceId:r.id}));
 if(group==='watches')return ui.rows.watch.map(r=>({...r,category:'watch',choiceId:r.id}));
 if(group==='pants'){
  const active=new Map(ui.rows.bottoms.map(r=>[connection.blazerConnection.knownPant(r.id).historyId,r]));
  return connection.catalogue.pants.map(r=>active.has(r.id)?{...active.get(r.id),historyId:r.id,category:'bottoms',choiceId:active.get(r.id).id}:({id:r.id,label:r.name||r.id,available:false,detail:r,kind:'retained catalogue record'}));
 }
 if(group==='shoes'){const registered=new Map(ui.rows.shoes.map(r=>[r.id,r]));return connection.catalogue.shoes.map(r=>registered.has(r.id)?({...registered.get(r.id),category:'shoes',choiceId:r.id}):({id:r.id,label:r.name||r.id,available:false,detail:r,kind:r.disabled?'Inactive / retained record':'No registered image connection'}));}
 return (connection.catalogue[group]||[]).map(r=>({id:r.id,label:r.name||r.brand||r.id,available:false,detail:r,kind:'Catalogue record; rendering unconnected'}));
}
function wardrobeGroups(){const preferred=Object.keys(groupLabels);return [...preferred,...Object.keys(connection.catalogue).filter(k=>Array.isArray(connection.catalogue[k])&&!preferred.includes(k))];}
function renderGroups(){const box=$('wardrobe-groups');box.replaceChildren();const groups=wardrobeGroups();$('group-count').textContent=groups.length+' groups';for(const k of groups){const rows=wardrobeRows(k),b=el('button',undefined,'fx-category-card');b.type='button';b.dataset.category=k;const txt=el('span');txt.append(el('strong',groupLabels[k]||k),el('small',rows.length+' records'));b.append(icon(groupLabels[k]?k:'wardrobe'),txt,el('span','›'));b.onclick=()=>browseCategory(k);box.append(b);}}
function browseCategory(group){const{body,actions}=openSheet(groupLabels[group]||group),search=el('input',undefined,'fx-search'),list=el('div',undefined,'fx-picker-list');search.type='search';search.placeholder='Search actual name or ID';search.id='wardrobe-search';search.setAttribute('aria-label','Search wardrobe');list.id='wardrobe-list';const rows=wardrobeRows(group);body.append(search,list);function draw(){list.replaceChildren();const q=search.value.trim().toLowerCase();for(const r of rows.filter(x=>(x.id+' '+x.label).toLowerCase().includes(q))){const b=el('button',undefined,'fx-choice');b.type='button';b.dataset.recordId=r.id;b.append(el('span',r.id,'fx-choice-id'),el('span',r.label,'fx-choice-name'));if(!r.available)b.append(el('small',r.kind||'Image route not connected'));b.onclick=()=>itemDetails(r,group);list.append(b);}if(!list.children.length)list.append(el('p','No current item matches.','fx-caption'));}search.oninput=draw;draw();actions.append(button('Close',()=>dismissSheet()));search.focus();}
function itemDetails(r,group){const{body,actions,token}=openSheet((groupLabels[group]||group)+' · '+r.id);body.append(el('h3',r.label),el('p',r.id,'fx-caption'));if(r.view){const img=el('img',undefined,'fx-bound-image');img.alt=r.id+' saved suit control; not current selection';img.src=resolveUrl(r.view);body.append(img,el('p','Saved DS001 / T001 / shoe-8 assembly. This is a read-only reference, not a newly selected outfit.','fx-caption'));}
 else body.append(el('p',group==='watches'?'Watch ID/name display; images deferred.':'This item detail view does not substitute an unbound image.','fx-caption'));
 if(r.detail){const d=el('details'),summary=el('summary','Source record');d.append(summary,el('pre',JSON.stringify(r.detail,null,2)));body.append(d);}
 if(r.category&&r.available){actions.append(button('Use exact item',()=>{ui.set(r.category,{mode:'item',id:r.choiceId});setMode('anchor');dismissSheet(false);showPage('home');updateHome();status('Exact '+(groupLabels[group]||group)+' preference applied. Generate to display the resulting outfit.');},true));}
 actions.append(button('Back to category',()=>browseCategory(group)));body.append(el('p','Renaming is unavailable: the current build has no persistent rename handler.','fx-caption'));
}
function historyRow(event,withButton=false){const row=el('article',undefined,'fx-history-row');row.append(el('strong',event.localDate+' · '+event.origin),el('p',ids(event.canonical_selection)));const watch=connection.catalogue.watches.find(w=>w.id===event.items.watch?.id);row.append(el('p',event.items.shoes.id+(watch?' · '+watch.id+' — '+watch.name:'')));if(withButton)row.append(button('View recorded selection',async()=>{dismissSheet();options=[];optionIndex=-1;report=null;lastRequest=null;producing=null;await apply(event.canonical_selection,{origin:'manual',localDate:event.localDate});showPage('outfits');}));return row;}
function refreshHistory(){const s=store.snapshot(),st=store.status();$('wear-count').textContent=s.events.length;$('repeat-limit').textContent=Number.isFinite(root.HEWRS_INPUTS.logicData.rotationPolicy?.maxMonthlyRepeatIncidents)?String(root.HEWRS_INPUTS.logicData.rotationPolicy.maxMonthlyRepeatIncidents):'—';$('storage-banner').textContent=st.blocked||(st.persistent?'Saved in this browser’s existing candidate ledger.':'Session memory only. Export to retain records.');const list=$('history-preview');list.replaceChildren();if(!s.events.length)list.append(el('p','No wear recorded in this application.','fx-caption'));for(const e of s.events.slice(-2).reverse())list.append(historyRow(e));$('clear-log').disabled=!s.events.length||!!st.blocked;}
function logSheet(){const{body,actions}=openSheet('Recent Log');const s=store.snapshot();if(!s.events.length)body.append(el('p','No confirmed wear records.','fx-caption'));for(const e of [...s.events].reverse())body.append(historyRow(e,true));actions.append(button('Close',()=>dismissSheet()));}
function confirmClear(){const before=store.snapshot();const{body,actions}=openSheet('Clear Wear Log');body.append(el('p','Remove '+before.events.length+' confirmed wear records from this application’s ledger? This does not alter the catalogue, current outfit or production history.','fx-warning'));actions.append(button('Cancel',()=>dismissSheet()),button('Confirm clear',()=>{const now=store.snapshot();need(now.revision===before.revision,'History changed; reopen Clear before proceeding');const preview=store.previewImport(JSON.stringify({...now,events:[]}));store.restore(preview);dismissSheet(false);invalidateRecommendations();refreshHistory();status('Local wear log cleared.');}));}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function backup(){restorePreview=null;const{body,actions,token}=openSheet('Backup & Restore');const st=store.status();body.append(el('p',st.blocked||(st.persistent?'Using the existing application ledger and source lock.':'Session memory only. Export to retain current records.'),'fx-caption'));
 const exportButton=button('Export current backup',()=>download('HEWRS_LOCAL_BACKUP_'+localToday()+'.json',store.exportText()));exportButton.id='export-backup';const f=el('input');f.type='file';f.accept='.json,application/json';f.id='backup-file';f.setAttribute('aria-label','Select existing application backup');const pre=el('pre');pre.id='import-preview';pre.hidden=true;const restore=button('Confirm restore',async()=>{need(restorePreview,'Select a validated backup first');const preview=restorePreview;store.restore(preview);restorePreview=null;restore.disabled=true;dismissSheet(false);invalidateRecommendations();refreshHistory();const s=store.snapshot().session;if(s){setMode(s.mode);ctx={occasion:s.context.occasion,formality:s.context.requiredFormality,style:'AUTO',localDate:s.localDate};await apply(s.selection,{origin:'manual',context:s.context,localDate:s.localDate,save:false});}updateHome();status('Validated backup restored through the existing application handler.');},true);restore.id='confirm-restore';restore.disabled=true;
 f.onchange=async()=>{restorePreview=null;restore.disabled=true;pre.hidden=true;try{const file=f.files[0];if(!file)return;const v=store.previewImport(await file.text());if(modal?.token!==token)return;restorePreview=v;pre.textContent=JSON.stringify({current_records:store.snapshot().events.length,backup_records:v.events.length,selection:v.session?.selection||null,action:'Replace this candidate ledger only after confirmation; no merge or production migration.'},null,2);pre.hidden=false;restore.disabled=false;$('fx-sheet-error').textContent='';}catch(e){sheetError(e);}};
 const content=el('div',undefined,'fx-data-actions');content.append(exportButton,el('label','Import a current-format backup'),f,pre);body.append(content);actions.append(button('Cancel',()=>dismissSheet()),restore);
}
function resetPreferences(){const{body,actions}=openSheet('Reset preferences');body.append(el('p','Clear all six Home preferences? Your current outfit and wear history will remain unchanged.','fx-caption'));actions.append(button('Cancel',()=>dismissSheet()),button('Confirm reset',()=>{ui.reset();producing=null;dismissSheet(false);updateHome();status('Preferences cleared. Choose the topwear and footwear required by this build; no garment is selected automatically.');}));}
// One modal owner, one router and one logging transaction for both buttons.
$('fx-sheet-close').onclick=()=>dismissSheet();$('fx-sheet').addEventListener('cancel',e=>{e.preventDefault();dismissSheet();});$('fx-sheet').addEventListener('click',e=>{if(e.target!==$('fx-sheet'))return;const r=$('fx-sheet').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dismissSheet();});
for(const n of document.querySelectorAll('[data-page]'))n.onclick=()=>showPage(n.dataset.page);$('back-home').onclick=()=>showPage('home');for(const n of document.querySelectorAll('[data-picker]'))n.onclick=()=>openPicker(n.dataset.picker);
$('mode-engine').onclick=()=>{setMode('engine');status('Engine Choice. Existing preferences are kept; Reset clears them explicitly.');};$('mode-anchor').onclick=()=>{setMode('anchor');status(ui.lockCount()?'Anchor Choice. Exact pieces or category preferences remain selected.':'Choose at least one preference; switching modes does not select an item.');};
$('cancel-work').onclick=cancel;$('reset-preferences').onclick=resetPreferences;$('work-button').onclick=()=>contextSheet('work');$('style-button').onclick=()=>contextSheet('style');$('weather-button').onclick=()=>contextSheet('weather');$('season-button').onclick=()=>contextSheet('season');$('generate-options').onclick=submit;
$('view-current').onclick=()=>{if(current){presentFrame();displayCurrent();showPage('outfits');}};$('prev-option').onclick=()=>selectOption(optionIndex-1).catch(e=>status(e.message,true));$('next-option').onclick=()=>selectOption(optionIndex+1).catch(e=>status(e.message,true));$('open-results').onclick=resultSheet;
$('full-view').onclick=()=>{$('stage').classList.remove('detail');$('full-view').setAttribute('aria-pressed','true');$('detail-view').setAttribute('aria-pressed','false');};$('detail-view').onclick=()=>{$('stage').classList.add('detail');$('full-view').setAttribute('aria-pressed','false');$('detail-view').setAttribute('aria-pressed','true');};
$('details-button').onclick=details;$('score-button').onclick=scoreDetails;$('record-wear').onclick=startLog;$('quick-log').onclick=startLog;
$('regenerate').onclick=async()=>{if(busy||!producing)return;const p=copy(producing);ui.replace(p.prefs);ctx=copy(p.context);setMode(p.mode);updateHome();try{if(p.kind==='engine')await generate(p.config,{prefs:p.prefs});else{await apply(p.selection,{origin:'manual',keepPreferences:true});showPage('outfits');}}catch(e){status(e.message,true);}};
$('data-button').onclick=backup;$('open-log').onclick=logSheet;$('clear-log').onclick=confirmClear;$('favorites-button').onclick=()=>message('Favorites','The current source has no connected Favorites persistence handler. This view does not invent favorites or log wear.');$('insights-button').onclick=()=>{const{body,actions}=openSheet('Insights');body.append(el('p','Existing engine output; no additional rotation statistics are calculated by this view.','fx-caption'),el('pre',JSON.stringify(report?.rotation||{status:'unavailable',reason:'No current computed rotation report'},null,2)));actions.append(button('Close',()=>dismissSheet()));};
root.HEWRSApp=Object.freeze({version:'HEWRS_CONNECTED_APP_V1_16_1',connection,store,renderer,ui,apply,generate,cancel,showPage,setMode,openPicker,submit,resolveUrl,state:()=>({selection:copy(current),origin,mode,report:copy(report),request:copy(lastRequest),optionCount:options.length,optionIndex,page:pageName,score:copy(score),sourceLock:root.HEWRS_INPUT_SHA256,preferences:ui.snapshot(),context:copy(ctx),busy})});
const saved=store.snapshot().session;if(saved){setMode(saved.mode);ctx={occasion:saved.context.occasion,formality:saved.context.requiredFormality,style:'AUTO',localDate:saved.localDate};}ui.fromSelection(saved?.selection||defaultSelection);setMode(mode);updateHome();renderGroups();refreshHistory();for(const b of document.querySelectorAll('[data-runtime]'))if(b.dataset.choice!=='included')b.disabled=false;
apply(saved?.selection||defaultSelection,{origin:'manual',context:saved?.context||currentContext(),localDate:saved?.localDate||ctx.localDate,save:false,keepPreferences:true}).then(()=>{root.HEWRS_READY=true;setBusy(false);updateHome();status(saved?'Saved outfit restored. Full generating preferences are not stored by the current source schema.':'');showPage('home');}).catch(e=>{root.HEWRS_LOAD_ERROR=e.message;status('Initial view failed: '+e.message,true);setBusy(false);});
})(globalThis);
